/*
 * Flow Experimental API
 *
 * Experimental API endpoints for the Flow Access Node. These endpoints are subject to change without notice. Endpoints may be moved to a permanent API once they are stable. 
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Role string

// List of Role
const (
	AUTHORIZER_Role Role = "authorizer"
	PAYER_Role Role = "payer"
	PROPOSER_Role Role = "proposer"
	INTERACTED_Role Role = "interacted"
)
