// Code generated by protoc-gen-go. DO NOT EDIT.
// source: flow/executiondata/executiondata.proto

package access

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	entities "github.com/onflow/flow/protobuf/go/flow/entities"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetExecutionDataByBlockIDRequest struct {
	BlockId              []byte   `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetExecutionDataByBlockIDRequest) Reset()         { *m = GetExecutionDataByBlockIDRequest{} }
func (m *GetExecutionDataByBlockIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetExecutionDataByBlockIDRequest) ProtoMessage()    {}
func (*GetExecutionDataByBlockIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_da469632570513fb, []int{0}
}

func (m *GetExecutionDataByBlockIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetExecutionDataByBlockIDRequest.Unmarshal(m, b)
}
func (m *GetExecutionDataByBlockIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetExecutionDataByBlockIDRequest.Marshal(b, m, deterministic)
}
func (m *GetExecutionDataByBlockIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetExecutionDataByBlockIDRequest.Merge(m, src)
}
func (m *GetExecutionDataByBlockIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetExecutionDataByBlockIDRequest.Size(m)
}
func (m *GetExecutionDataByBlockIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetExecutionDataByBlockIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetExecutionDataByBlockIDRequest proto.InternalMessageInfo

func (m *GetExecutionDataByBlockIDRequest) GetBlockId() []byte {
	if m != nil {
		return m.BlockId
	}
	return nil
}

type GetExecutionDataByBlockIDResponse struct {
	BlockExecutionData   *entities.BlockExecutionData `protobuf:"bytes,1,opt,name=block_execution_data,json=blockExecutionData,proto3" json:"block_execution_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *GetExecutionDataByBlockIDResponse) Reset()         { *m = GetExecutionDataByBlockIDResponse{} }
func (m *GetExecutionDataByBlockIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetExecutionDataByBlockIDResponse) ProtoMessage()    {}
func (*GetExecutionDataByBlockIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_da469632570513fb, []int{1}
}

func (m *GetExecutionDataByBlockIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetExecutionDataByBlockIDResponse.Unmarshal(m, b)
}
func (m *GetExecutionDataByBlockIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetExecutionDataByBlockIDResponse.Marshal(b, m, deterministic)
}
func (m *GetExecutionDataByBlockIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetExecutionDataByBlockIDResponse.Merge(m, src)
}
func (m *GetExecutionDataByBlockIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetExecutionDataByBlockIDResponse.Size(m)
}
func (m *GetExecutionDataByBlockIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetExecutionDataByBlockIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetExecutionDataByBlockIDResponse proto.InternalMessageInfo

func (m *GetExecutionDataByBlockIDResponse) GetBlockExecutionData() *entities.BlockExecutionData {
	if m != nil {
		return m.BlockExecutionData
	}
	return nil
}

type SubscribeExecutionDataRequest struct {
	StartBlockId         []byte   `protobuf:"bytes,1,opt,name=start_block_id,json=startBlockId,proto3" json:"start_block_id,omitempty"`
	StartBlockHeight     uint64   `protobuf:"varint,2,opt,name=start_block_height,json=startBlockHeight,proto3" json:"start_block_height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeExecutionDataRequest) Reset()         { *m = SubscribeExecutionDataRequest{} }
func (m *SubscribeExecutionDataRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeExecutionDataRequest) ProtoMessage()    {}
func (*SubscribeExecutionDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_da469632570513fb, []int{2}
}

func (m *SubscribeExecutionDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeExecutionDataRequest.Unmarshal(m, b)
}
func (m *SubscribeExecutionDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeExecutionDataRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeExecutionDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeExecutionDataRequest.Merge(m, src)
}
func (m *SubscribeExecutionDataRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeExecutionDataRequest.Size(m)
}
func (m *SubscribeExecutionDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeExecutionDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeExecutionDataRequest proto.InternalMessageInfo

func (m *SubscribeExecutionDataRequest) GetStartBlockId() []byte {
	if m != nil {
		return m.StartBlockId
	}
	return nil
}

func (m *SubscribeExecutionDataRequest) GetStartBlockHeight() uint64 {
	if m != nil {
		return m.StartBlockHeight
	}
	return 0
}

type SubscribeExecutionDataResponse struct {
	BlockHeight          uint64                       `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	BlockExecutionData   *entities.BlockExecutionData `protobuf:"bytes,2,opt,name=block_execution_data,json=blockExecutionData,proto3" json:"block_execution_data,omitempty"`
	BlockTimestamp       *timestamppb.Timestamp       `protobuf:"bytes,3,opt,name=block_timestamp,json=blockTimestamp,proto3" json:"block_timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *SubscribeExecutionDataResponse) Reset()         { *m = SubscribeExecutionDataResponse{} }
func (m *SubscribeExecutionDataResponse) String() string { return proto.CompactTextString(m) }
func (*SubscribeExecutionDataResponse) ProtoMessage()    {}
func (*SubscribeExecutionDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_da469632570513fb, []int{3}
}

func (m *SubscribeExecutionDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeExecutionDataResponse.Unmarshal(m, b)
}
func (m *SubscribeExecutionDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeExecutionDataResponse.Marshal(b, m, deterministic)
}
func (m *SubscribeExecutionDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeExecutionDataResponse.Merge(m, src)
}
func (m *SubscribeExecutionDataResponse) XXX_Size() int {
	return xxx_messageInfo_SubscribeExecutionDataResponse.Size(m)
}
func (m *SubscribeExecutionDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeExecutionDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeExecutionDataResponse proto.InternalMessageInfo

func (m *SubscribeExecutionDataResponse) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *SubscribeExecutionDataResponse) GetBlockExecutionData() *entities.BlockExecutionData {
	if m != nil {
		return m.BlockExecutionData
	}
	return nil
}

func (m *SubscribeExecutionDataResponse) GetBlockTimestamp() *timestamppb.Timestamp {
	if m != nil {
		return m.BlockTimestamp
	}
	return nil
}

type SubscribeEventsRequest struct {
	StartBlockId         []byte       `protobuf:"bytes,1,opt,name=start_block_id,json=startBlockId,proto3" json:"start_block_id,omitempty"`
	StartBlockHeight     uint64       `protobuf:"varint,2,opt,name=start_block_height,json=startBlockHeight,proto3" json:"start_block_height,omitempty"`
	Filter               *EventFilter `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SubscribeEventsRequest) Reset()         { *m = SubscribeEventsRequest{} }
func (m *SubscribeEventsRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeEventsRequest) ProtoMessage()    {}
func (*SubscribeEventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_da469632570513fb, []int{4}
}

func (m *SubscribeEventsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeEventsRequest.Unmarshal(m, b)
}
func (m *SubscribeEventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeEventsRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeEventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeEventsRequest.Merge(m, src)
}
func (m *SubscribeEventsRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeEventsRequest.Size(m)
}
func (m *SubscribeEventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeEventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeEventsRequest proto.InternalMessageInfo

func (m *SubscribeEventsRequest) GetStartBlockId() []byte {
	if m != nil {
		return m.StartBlockId
	}
	return nil
}

func (m *SubscribeEventsRequest) GetStartBlockHeight() uint64 {
	if m != nil {
		return m.StartBlockHeight
	}
	return 0
}

func (m *SubscribeEventsRequest) GetFilter() *EventFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

type SubscribeEventsResponse struct {
	BlockId              []byte                 `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	BlockHeight          uint64                 `protobuf:"varint,2,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	Events               []*entities.Event      `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	BlockTimestamp       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=block_timestamp,json=blockTimestamp,proto3" json:"block_timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SubscribeEventsResponse) Reset()         { *m = SubscribeEventsResponse{} }
func (m *SubscribeEventsResponse) String() string { return proto.CompactTextString(m) }
func (*SubscribeEventsResponse) ProtoMessage()    {}
func (*SubscribeEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_da469632570513fb, []int{5}
}

func (m *SubscribeEventsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeEventsResponse.Unmarshal(m, b)
}
func (m *SubscribeEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeEventsResponse.Marshal(b, m, deterministic)
}
func (m *SubscribeEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeEventsResponse.Merge(m, src)
}
func (m *SubscribeEventsResponse) XXX_Size() int {
	return xxx_messageInfo_SubscribeEventsResponse.Size(m)
}
func (m *SubscribeEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeEventsResponse proto.InternalMessageInfo

func (m *SubscribeEventsResponse) GetBlockId() []byte {
	if m != nil {
		return m.BlockId
	}
	return nil
}

func (m *SubscribeEventsResponse) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *SubscribeEventsResponse) GetEvents() []*entities.Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *SubscribeEventsResponse) GetBlockTimestamp() *timestamppb.Timestamp {
	if m != nil {
		return m.BlockTimestamp
	}
	return nil
}

type EventFilter struct {
	EventType            []string `protobuf:"bytes,1,rep,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Address              []string `protobuf:"bytes,2,rep,name=address,proto3" json:"address,omitempty"`
	Contract             []string `protobuf:"bytes,3,rep,name=contract,proto3" json:"contract,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventFilter) Reset()         { *m = EventFilter{} }
func (m *EventFilter) String() string { return proto.CompactTextString(m) }
func (*EventFilter) ProtoMessage()    {}
func (*EventFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_da469632570513fb, []int{6}
}

func (m *EventFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventFilter.Unmarshal(m, b)
}
func (m *EventFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventFilter.Marshal(b, m, deterministic)
}
func (m *EventFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventFilter.Merge(m, src)
}
func (m *EventFilter) XXX_Size() int {
	return xxx_messageInfo_EventFilter.Size(m)
}
func (m *EventFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_EventFilter.DiscardUnknown(m)
}

var xxx_messageInfo_EventFilter proto.InternalMessageInfo

func (m *EventFilter) GetEventType() []string {
	if m != nil {
		return m.EventType
	}
	return nil
}

func (m *EventFilter) GetAddress() []string {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *EventFilter) GetContract() []string {
	if m != nil {
		return m.Contract
	}
	return nil
}

func init() {
	proto.RegisterType((*GetExecutionDataByBlockIDRequest)(nil), "flow.access.GetExecutionDataByBlockIDRequest")
	proto.RegisterType((*GetExecutionDataByBlockIDResponse)(nil), "flow.access.GetExecutionDataByBlockIDResponse")
	proto.RegisterType((*SubscribeExecutionDataRequest)(nil), "flow.access.SubscribeExecutionDataRequest")
	proto.RegisterType((*SubscribeExecutionDataResponse)(nil), "flow.access.SubscribeExecutionDataResponse")
	proto.RegisterType((*SubscribeEventsRequest)(nil), "flow.access.SubscribeEventsRequest")
	proto.RegisterType((*SubscribeEventsResponse)(nil), "flow.access.SubscribeEventsResponse")
	proto.RegisterType((*EventFilter)(nil), "flow.access.EventFilter")
}

func init() {
	proto.RegisterFile("flow/executiondata/executiondata.proto", fileDescriptor_da469632570513fb)
}

var fileDescriptor_da469632570513fb = []byte{
	// 573 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0xe5, 0xa4, 0x4a, 0x9b, 0x49, 0xd4, 0x56, 0xab, 0x0a, 0x1c, 0x4b, 0x05, 0xc7, 0x54,
	0x28, 0x82, 0xb2, 0xae, 0xc2, 0x99, 0x03, 0xa1, 0x7c, 0x44, 0xe2, 0x80, 0xdc, 0x9e, 0x38, 0x10,
	0xf9, 0x63, 0xe3, 0x58, 0x24, 0xde, 0xe0, 0xdd, 0x40, 0xc3, 0xc3, 0xf0, 0x40, 0xbc, 0x03, 0x27,
	0x5e, 0x04, 0x65, 0xd6, 0x76, 0xe2, 0x24, 0x0e, 0x45, 0xa8, 0x17, 0x4b, 0x33, 0xfb, 0x9b, 0xff,
	0xcc, 0xce, 0xcc, 0x1a, 0x1e, 0x0f, 0xc7, 0xfc, 0x9b, 0xcd, 0x6e, 0x98, 0x3f, 0x93, 0x11, 0x8f,
	0x03, 0x57, 0xba, 0x45, 0x8b, 0x4e, 0x13, 0x2e, 0x39, 0x69, 0x2c, 0x38, 0xea, 0xfa, 0x3e, 0x13,
	0xc2, 0xe8, 0xa8, 0xa0, 0x58, 0x46, 0x32, 0x62, 0xc2, 0xf6, 0xc6, 0xdc, 0xff, 0x3c, 0xc8, 0xa3,
	0x06, 0xcb, 0x30, 0xc3, 0xdc, 0x46, 0x8e, 0x98, 0x1b, 0xb0, 0x24, 0x25, 0x5a, 0x45, 0x82, 0x7d,
	0x65, 0xb1, 0x4c, 0x8f, 0x1e, 0x86, 0x9c, 0x87, 0x63, 0x66, 0xa3, 0xe5, 0xcd, 0x86, 0xb6, 0x8c,
	0x26, 0x4c, 0x48, 0x77, 0x32, 0x55, 0x80, 0xf5, 0x02, 0xcc, 0xb7, 0x4c, 0xbe, 0xce, 0x12, 0x5f,
	0xba, 0xd2, 0xed, 0xcd, 0x7b, 0x8b, 0x1c, 0xfd, 0x4b, 0x87, 0x7d, 0x99, 0x31, 0x21, 0x49, 0x0b,
	0x0e, 0x54, 0xd6, 0x28, 0xd0, 0x35, 0x53, 0xeb, 0x34, 0x9d, 0x7d, 0xb4, 0xfb, 0x81, 0x75, 0x03,
	0xed, 0x1d, 0xe1, 0x62, 0xca, 0x63, 0xc1, 0xc8, 0x15, 0x9c, 0x6c, 0xbb, 0x1f, 0x6a, 0x35, 0xba,
	0x6d, 0x8a, 0x7d, 0xc9, 0xca, 0xa7, 0x18, 0x5d, 0x50, 0x74, 0x88, 0xb7, 0xe1, 0xb3, 0x04, 0x9c,
	0x5e, 0xcd, 0x3c, 0xe1, 0x27, 0x91, 0xc7, 0x8a, 0x74, 0x5a, 0xf5, 0x19, 0x1c, 0x0a, 0xe9, 0x26,
	0x72, 0xb0, 0x56, 0x7b, 0x13, 0xbd, 0xaa, 0xc6, 0x80, 0x9c, 0x03, 0x59, 0xa5, 0x46, 0x2c, 0x0a,
	0x47, 0x52, 0xaf, 0x98, 0x5a, 0x67, 0xcf, 0x39, 0x5e, 0x92, 0xef, 0xd0, 0x6f, 0xfd, 0xd2, 0xe0,
	0x41, 0x59, 0xd6, 0xf4, 0xb2, 0x6d, 0x68, 0x16, 0xa4, 0x34, 0x94, 0x6a, 0x78, 0x4b, 0x95, 0xd2,
	0x7e, 0x54, 0xfe, 0xa3, 0x1f, 0xe4, 0x15, 0x1c, 0x29, 0xd1, 0x7c, 0xc2, 0x7a, 0x15, 0xf5, 0x0c,
	0xaa, 0x76, 0x80, 0x66, 0x3b, 0x40, 0xaf, 0x33, 0xc2, 0x39, 0xc4, 0x90, 0xdc, 0xb6, 0x7e, 0x68,
	0x70, 0x6f, 0x79, 0xbf, 0xc5, 0x1e, 0x89, 0x3b, 0x6c, 0x27, 0xb9, 0x80, 0xda, 0x30, 0x1a, 0x4b,
	0x96, 0xa4, 0xa5, 0xea, 0x74, 0xe5, 0x89, 0x50, 0xcc, 0xff, 0x06, 0xcf, 0x9d, 0x94, 0xb3, 0x7e,
	0x6a, 0x70, 0x7f, 0xa3, 0xc0, 0xb4, 0xf3, 0xe5, 0x6b, 0xba, 0x31, 0x94, 0xca, 0xe6, 0x50, 0xce,
	0xa1, 0x86, 0x0f, 0x47, 0xe8, 0x55, 0xb3, 0xda, 0x69, 0x74, 0x4f, 0xd6, 0xc6, 0x80, 0xc9, 0x9c,
	0x94, 0xd9, 0xd6, 0xed, 0xbd, 0x7f, 0xee, 0xb6, 0x07, 0x8d, 0x95, 0x3b, 0x92, 0x53, 0x00, 0x54,
	0x1f, 0xc8, 0xf9, 0x94, 0xe9, 0x9a, 0x59, 0xed, 0xd4, 0x9d, 0x3a, 0x7a, 0xae, 0xe7, 0x53, 0x46,
	0x74, 0xd8, 0x77, 0x83, 0x20, 0x61, 0x42, 0xe8, 0x15, 0x3c, 0xcb, 0x4c, 0x62, 0xc0, 0x81, 0xcf,
	0x63, 0x99, 0xb8, 0xbe, 0xc4, 0xe2, 0xeb, 0x4e, 0x6e, 0x77, 0x7f, 0x57, 0xe0, 0xb8, 0xb0, 0x28,
	0x2f, 0x3f, 0xf4, 0xc9, 0x77, 0x68, 0x95, 0xbe, 0x5a, 0xf2, 0xac, 0x30, 0x84, 0xbf, 0xfd, 0x1c,
	0x0c, 0x7a, 0x5b, 0x3c, 0x9d, 0x92, 0x58, 0xdd, 0xb0, 0xc2, 0x06, 0x3f, 0x29, 0x28, 0xed, 0x7c,
	0xdc, 0xc6, 0xd3, 0x5b, 0xb1, 0x2a, 0xe5, 0x85, 0x46, 0x3e, 0xc1, 0xd1, 0xda, 0xd6, 0x90, 0x47,
	0x25, 0x0a, 0xab, 0x4b, 0x6f, 0x9c, 0xed, 0x86, 0x32, 0xfd, 0xde, 0x7b, 0x30, 0x78, 0x12, 0x52,
	0x1e, 0x23, 0x9e, 0x8f, 0x5e, 0xc5, 0x7d, 0xa4, 0x61, 0x24, 0x47, 0x33, 0x8f, 0xfa, 0x7c, 0x62,
	0x2b, 0xc4, 0xc6, 0x4f, 0xfe, 0x53, 0x0e, 0xb9, 0x72, 0x28, 0xde, 0xab, 0xe1, 0xc1, 0xf3, 0x3f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x1f, 0x46, 0x34, 0x5c, 0x59, 0x06, 0x00, 0x00,
}
