// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: flow/executiondata/executiondata.proto

package executiondata

import (
	entities "github.com/onflow/flow/protobuf/go/flow/entities"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request for GetExecutionDataByBlockID
type GetExecutionDataByBlockIDRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Block ID of the block to get execution data for.
	BlockId []byte `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	// Preferred event encoding version of the block events payload.
	// Possible variants:
	// 1. CCF
	// 2. JSON-CDC
	EventEncodingVersion entities.EventEncodingVersion `protobuf:"varint,2,opt,name=event_encoding_version,json=eventEncodingVersion,proto3,enum=flow.entities.EventEncodingVersion" json:"event_encoding_version,omitempty"`
	// Criteria for selecting which executors to use when fetching data.
	ExecutionStateQuery *entities.ExecutionStateQuery `protobuf:"bytes,3,opt,name=execution_state_query,json=executionStateQuery,proto3" json:"execution_state_query,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetExecutionDataByBlockIDRequest) Reset() {
	*x = GetExecutionDataByBlockIDRequest{}
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionDataByBlockIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionDataByBlockIDRequest) ProtoMessage() {}

func (x *GetExecutionDataByBlockIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionDataByBlockIDRequest.ProtoReflect.Descriptor instead.
func (*GetExecutionDataByBlockIDRequest) Descriptor() ([]byte, []int) {
	return file_flow_executiondata_executiondata_proto_rawDescGZIP(), []int{0}
}

func (x *GetExecutionDataByBlockIDRequest) GetBlockId() []byte {
	if x != nil {
		return x.BlockId
	}
	return nil
}

func (x *GetExecutionDataByBlockIDRequest) GetEventEncodingVersion() entities.EventEncodingVersion {
	if x != nil {
		return x.EventEncodingVersion
	}
	return entities.EventEncodingVersion(0)
}

func (x *GetExecutionDataByBlockIDRequest) GetExecutionStateQuery() *entities.ExecutionStateQuery {
	if x != nil {
		return x.ExecutionStateQuery
	}
	return nil
}

// The response for GetExecutionDataByBlockID
type GetExecutionDataByBlockIDResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// BlockExecutionData for the block.
	BlockExecutionData *entities.BlockExecutionData `protobuf:"bytes,1,opt,name=block_execution_data,json=blockExecutionData,proto3" json:"block_execution_data,omitempty"`
	// Metadata about the execution result that was used to produce this response.
	ExecutorMetadata *entities.ExecutorMetadata `protobuf:"bytes,2,opt,name=executor_metadata,json=executorMetadata,proto3" json:"executor_metadata,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetExecutionDataByBlockIDResponse) Reset() {
	*x = GetExecutionDataByBlockIDResponse{}
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionDataByBlockIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionDataByBlockIDResponse) ProtoMessage() {}

func (x *GetExecutionDataByBlockIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionDataByBlockIDResponse.ProtoReflect.Descriptor instead.
func (*GetExecutionDataByBlockIDResponse) Descriptor() ([]byte, []int) {
	return file_flow_executiondata_executiondata_proto_rawDescGZIP(), []int{1}
}

func (x *GetExecutionDataByBlockIDResponse) GetBlockExecutionData() *entities.BlockExecutionData {
	if x != nil {
		return x.BlockExecutionData
	}
	return nil
}

func (x *GetExecutionDataByBlockIDResponse) GetExecutorMetadata() *entities.ExecutorMetadata {
	if x != nil {
		return x.ExecutorMetadata
	}
	return nil
}

// The request for SubscribeExecutionData
type SubscribeExecutionDataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Block ID of the first block to get execution data for.
	// Only one of start_block_id and start_block_height may be provided,
	// otherwise an InvalidArgument error is returned. If neither are provided,
	// the latest sealed block is used.
	StartBlockId []byte `protobuf:"bytes,1,opt,name=start_block_id,json=startBlockId,proto3" json:"start_block_id,omitempty"`
	// Block height of the first block to get execution data for.
	// Only one of start_block_id and start_block_height may be provided,
	// otherwise an InvalidArgument error is returned. If neither are provided,
	// the latest sealed block is used.
	StartBlockHeight uint64 `protobuf:"varint,2,opt,name=start_block_height,json=startBlockHeight,proto3" json:"start_block_height,omitempty"`
	// Preferred event encoding version of the block events payload.
	// Possible variants:
	// 1. CCF
	// 2. JSON-CDC
	EventEncodingVersion entities.EventEncodingVersion `protobuf:"varint,3,opt,name=event_encoding_version,json=eventEncodingVersion,proto3,enum=flow.entities.EventEncodingVersion" json:"event_encoding_version,omitempty"`
	// Criteria for selecting which executors to use when fetching data.
	ExecutionStateQuery *entities.ExecutionStateQuery `protobuf:"bytes,4,opt,name=execution_state_query,json=executionStateQuery,proto3" json:"execution_state_query,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SubscribeExecutionDataRequest) Reset() {
	*x = SubscribeExecutionDataRequest{}
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeExecutionDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeExecutionDataRequest) ProtoMessage() {}

func (x *SubscribeExecutionDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeExecutionDataRequest.ProtoReflect.Descriptor instead.
func (*SubscribeExecutionDataRequest) Descriptor() ([]byte, []int) {
	return file_flow_executiondata_executiondata_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeExecutionDataRequest) GetStartBlockId() []byte {
	if x != nil {
		return x.StartBlockId
	}
	return nil
}

func (x *SubscribeExecutionDataRequest) GetStartBlockHeight() uint64 {
	if x != nil {
		return x.StartBlockHeight
	}
	return 0
}

func (x *SubscribeExecutionDataRequest) GetEventEncodingVersion() entities.EventEncodingVersion {
	if x != nil {
		return x.EventEncodingVersion
	}
	return entities.EventEncodingVersion(0)
}

func (x *SubscribeExecutionDataRequest) GetExecutionStateQuery() *entities.ExecutionStateQuery {
	if x != nil {
		return x.ExecutionStateQuery
	}
	return nil
}

// The response for SubscribeExecutionData
type SubscribeExecutionDataResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Block height of the block containing the execution data.
	BlockHeight uint64 `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	// BlockExecutionData for the block.
	// Note: The block's ID is included within the BlockExecutionData.
	BlockExecutionData *entities.BlockExecutionData `protobuf:"bytes,2,opt,name=block_execution_data,json=blockExecutionData,proto3" json:"block_execution_data,omitempty"`
	// Timestamp from the block containing the execution data.
	BlockTimestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=block_timestamp,json=blockTimestamp,proto3" json:"block_timestamp,omitempty"`
	// Metadata about the execution result that was used to produce this response.
	ExecutorMetadata *entities.ExecutorMetadata `protobuf:"bytes,4,opt,name=executor_metadata,json=executorMetadata,proto3" json:"executor_metadata,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SubscribeExecutionDataResponse) Reset() {
	*x = SubscribeExecutionDataResponse{}
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeExecutionDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeExecutionDataResponse) ProtoMessage() {}

func (x *SubscribeExecutionDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeExecutionDataResponse.ProtoReflect.Descriptor instead.
func (*SubscribeExecutionDataResponse) Descriptor() ([]byte, []int) {
	return file_flow_executiondata_executiondata_proto_rawDescGZIP(), []int{3}
}

func (x *SubscribeExecutionDataResponse) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *SubscribeExecutionDataResponse) GetBlockExecutionData() *entities.BlockExecutionData {
	if x != nil {
		return x.BlockExecutionData
	}
	return nil
}

func (x *SubscribeExecutionDataResponse) GetBlockTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.BlockTimestamp
	}
	return nil
}

func (x *SubscribeExecutionDataResponse) GetExecutorMetadata() *entities.ExecutorMetadata {
	if x != nil {
		return x.ExecutorMetadata
	}
	return nil
}

// The request for SubscribeExecutionDataFromStartBlockIDRequest
type SubscribeExecutionDataFromStartBlockIDRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Block ID of the first block to get execution data for.
	StartBlockId []byte `protobuf:"bytes,1,opt,name=start_block_id,json=startBlockId,proto3" json:"start_block_id,omitempty"`
	// Preferred event encoding version of the block events payload.
	// Possible variants:
	// 1. CCF
	// 2. JSON-CDC
	EventEncodingVersion entities.EventEncodingVersion `protobuf:"varint,2,opt,name=event_encoding_version,json=eventEncodingVersion,proto3,enum=flow.entities.EventEncodingVersion" json:"event_encoding_version,omitempty"`
	// Criteria for selecting which executors to use when fetching data.
	ExecutionStateQuery *entities.ExecutionStateQuery `protobuf:"bytes,3,opt,name=execution_state_query,json=executionStateQuery,proto3" json:"execution_state_query,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SubscribeExecutionDataFromStartBlockIDRequest) Reset() {
	*x = SubscribeExecutionDataFromStartBlockIDRequest{}
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeExecutionDataFromStartBlockIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeExecutionDataFromStartBlockIDRequest) ProtoMessage() {}

func (x *SubscribeExecutionDataFromStartBlockIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeExecutionDataFromStartBlockIDRequest.ProtoReflect.Descriptor instead.
func (*SubscribeExecutionDataFromStartBlockIDRequest) Descriptor() ([]byte, []int) {
	return file_flow_executiondata_executiondata_proto_rawDescGZIP(), []int{4}
}

func (x *SubscribeExecutionDataFromStartBlockIDRequest) GetStartBlockId() []byte {
	if x != nil {
		return x.StartBlockId
	}
	return nil
}

func (x *SubscribeExecutionDataFromStartBlockIDRequest) GetEventEncodingVersion() entities.EventEncodingVersion {
	if x != nil {
		return x.EventEncodingVersion
	}
	return entities.EventEncodingVersion(0)
}

func (x *SubscribeExecutionDataFromStartBlockIDRequest) GetExecutionStateQuery() *entities.ExecutionStateQuery {
	if x != nil {
		return x.ExecutionStateQuery
	}
	return nil
}

// The request for SubscribeExecutionDataFromStartBlockHeightRequest
type SubscribeExecutionDataFromStartBlockHeightRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Block height of the first block to get execution data for.
	StartBlockHeight uint64 `protobuf:"varint,1,opt,name=start_block_height,json=startBlockHeight,proto3" json:"start_block_height,omitempty"`
	// Preferred event encoding version of the block events payload.
	// Possible variants:
	// 1. CCF
	// 2. JSON-CDC
	EventEncodingVersion entities.EventEncodingVersion `protobuf:"varint,2,opt,name=event_encoding_version,json=eventEncodingVersion,proto3,enum=flow.entities.EventEncodingVersion" json:"event_encoding_version,omitempty"`
	// Criteria for selecting which executors to use when fetching data.
	ExecutionStateQuery *entities.ExecutionStateQuery `protobuf:"bytes,3,opt,name=execution_state_query,json=executionStateQuery,proto3" json:"execution_state_query,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SubscribeExecutionDataFromStartBlockHeightRequest) Reset() {
	*x = SubscribeExecutionDataFromStartBlockHeightRequest{}
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeExecutionDataFromStartBlockHeightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeExecutionDataFromStartBlockHeightRequest) ProtoMessage() {}

func (x *SubscribeExecutionDataFromStartBlockHeightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeExecutionDataFromStartBlockHeightRequest.ProtoReflect.Descriptor instead.
func (*SubscribeExecutionDataFromStartBlockHeightRequest) Descriptor() ([]byte, []int) {
	return file_flow_executiondata_executiondata_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribeExecutionDataFromStartBlockHeightRequest) GetStartBlockHeight() uint64 {
	if x != nil {
		return x.StartBlockHeight
	}
	return 0
}

func (x *SubscribeExecutionDataFromStartBlockHeightRequest) GetEventEncodingVersion() entities.EventEncodingVersion {
	if x != nil {
		return x.EventEncodingVersion
	}
	return entities.EventEncodingVersion(0)
}

func (x *SubscribeExecutionDataFromStartBlockHeightRequest) GetExecutionStateQuery() *entities.ExecutionStateQuery {
	if x != nil {
		return x.ExecutionStateQuery
	}
	return nil
}

// The request for SubscribeExecutionDataFromLatestRequest
type SubscribeExecutionDataFromLatestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Preferred event encoding version of the block events payload.
	// Possible variants:
	// 1. CCF
	// 2. JSON-CDC
	EventEncodingVersion entities.EventEncodingVersion `protobuf:"varint,1,opt,name=event_encoding_version,json=eventEncodingVersion,proto3,enum=flow.entities.EventEncodingVersion" json:"event_encoding_version,omitempty"`
	// Criteria for selecting which executors to use when fetching data.
	ExecutionStateQuery *entities.ExecutionStateQuery `protobuf:"bytes,2,opt,name=execution_state_query,json=executionStateQuery,proto3" json:"execution_state_query,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SubscribeExecutionDataFromLatestRequest) Reset() {
	*x = SubscribeExecutionDataFromLatestRequest{}
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeExecutionDataFromLatestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeExecutionDataFromLatestRequest) ProtoMessage() {}

func (x *SubscribeExecutionDataFromLatestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeExecutionDataFromLatestRequest.ProtoReflect.Descriptor instead.
func (*SubscribeExecutionDataFromLatestRequest) Descriptor() ([]byte, []int) {
	return file_flow_executiondata_executiondata_proto_rawDescGZIP(), []int{6}
}

func (x *SubscribeExecutionDataFromLatestRequest) GetEventEncodingVersion() entities.EventEncodingVersion {
	if x != nil {
		return x.EventEncodingVersion
	}
	return entities.EventEncodingVersion(0)
}

func (x *SubscribeExecutionDataFromLatestRequest) GetExecutionStateQuery() *entities.ExecutionStateQuery {
	if x != nil {
		return x.ExecutionStateQuery
	}
	return nil
}

// The request for SubscribeEvents
type SubscribeEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Block ID of the first block to search for events.
	// Only one of start_block_id and start_block_height may be provided,
	// otherwise an InvalidArgument error is returned. If neither are provided,
	// the latest sealed block is used.
	StartBlockId []byte `protobuf:"bytes,1,opt,name=start_block_id,json=startBlockId,proto3" json:"start_block_id,omitempty"`
	// Block height of the first block to search for events.
	// Only one of start_block_id and start_block_height may be provided,
	// otherwise an InvalidArgument error is returned. If neither are provided,
	// the latest sealed block is used.
	StartBlockHeight uint64 `protobuf:"varint,2,opt,name=start_block_height,json=startBlockHeight,proto3" json:"start_block_height,omitempty"`
	// Filter to apply to events for each block searched.
	// If no filter is provided, all events are returned.
	Filter *EventFilter `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	// Interval in block heights at which the server should return a heartbeat
	// message to the client. The heartbeat is a normal SubscribeEventsResponse
	// with no events, and allows clients to track which blocks were searched.
	// Clients can use this information to determine which block to start from
	// when reconnecting.
	//
	// The interval is calculated from the last response returned, which could be
	// either another heartbeat or a response containing events.
	HeartbeatInterval uint64 `protobuf:"varint,4,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"`
	// Preferred event encoding version of the block events payload.
	// Possible variants:
	// 1. CCF
	// 2. JSON-CDC
	EventEncodingVersion entities.EventEncodingVersion `protobuf:"varint,5,opt,name=event_encoding_version,json=eventEncodingVersion,proto3,enum=flow.entities.EventEncodingVersion" json:"event_encoding_version,omitempty"`
	// Criteria for selecting which executors to use when fetching data.
	ExecutionStateQuery *entities.ExecutionStateQuery `protobuf:"bytes,6,opt,name=execution_state_query,json=executionStateQuery,proto3" json:"execution_state_query,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SubscribeEventsRequest) Reset() {
	*x = SubscribeEventsRequest{}
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEventsRequest) ProtoMessage() {}

func (x *SubscribeEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeEventsRequest) Descriptor() ([]byte, []int) {
	return file_flow_executiondata_executiondata_proto_rawDescGZIP(), []int{7}
}

func (x *SubscribeEventsRequest) GetStartBlockId() []byte {
	if x != nil {
		return x.StartBlockId
	}
	return nil
}

func (x *SubscribeEventsRequest) GetStartBlockHeight() uint64 {
	if x != nil {
		return x.StartBlockHeight
	}
	return 0
}

func (x *SubscribeEventsRequest) GetFilter() *EventFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *SubscribeEventsRequest) GetHeartbeatInterval() uint64 {
	if x != nil {
		return x.HeartbeatInterval
	}
	return 0
}

func (x *SubscribeEventsRequest) GetEventEncodingVersion() entities.EventEncodingVersion {
	if x != nil {
		return x.EventEncodingVersion
	}
	return entities.EventEncodingVersion(0)
}

func (x *SubscribeEventsRequest) GetExecutionStateQuery() *entities.ExecutionStateQuery {
	if x != nil {
		return x.ExecutionStateQuery
	}
	return nil
}

// The request for SubscribeEventsFromStartBlockID
type SubscribeEventsFromStartBlockIDRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Block ID of the first block to search for events.
	StartBlockId []byte `protobuf:"bytes,1,opt,name=start_block_id,json=startBlockId,proto3" json:"start_block_id,omitempty"`
	// Filter to apply to events for each block searched.
	// If no filter is provided, all events are returned.
	Filter *EventFilter `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	// Interval in block heights at which the server should return a heartbeat
	// message to the client. The heartbeat is a normal SubscribeEventsResponse
	// with no events, and allows clients to track which blocks were searched.
	// Clients can use this information to determine which block to start from
	// when reconnecting.
	//
	// The interval is calculated from the last response returned, which could be
	// either another heartbeat or a response containing events.
	HeartbeatInterval uint64 `protobuf:"varint,3,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"`
	// Preferred event encoding version of the block events payload.
	// Possible variants:
	// 1. CCF
	// 2. JSON-CDC
	EventEncodingVersion entities.EventEncodingVersion `protobuf:"varint,4,opt,name=event_encoding_version,json=eventEncodingVersion,proto3,enum=flow.entities.EventEncodingVersion" json:"event_encoding_version,omitempty"`
	// Criteria for selecting which executors to use when fetching data.
	ExecutionStateQuery *entities.ExecutionStateQuery `protobuf:"bytes,5,opt,name=execution_state_query,json=executionStateQuery,proto3" json:"execution_state_query,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SubscribeEventsFromStartBlockIDRequest) Reset() {
	*x = SubscribeEventsFromStartBlockIDRequest{}
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEventsFromStartBlockIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEventsFromStartBlockIDRequest) ProtoMessage() {}

func (x *SubscribeEventsFromStartBlockIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEventsFromStartBlockIDRequest.ProtoReflect.Descriptor instead.
func (*SubscribeEventsFromStartBlockIDRequest) Descriptor() ([]byte, []int) {
	return file_flow_executiondata_executiondata_proto_rawDescGZIP(), []int{8}
}

func (x *SubscribeEventsFromStartBlockIDRequest) GetStartBlockId() []byte {
	if x != nil {
		return x.StartBlockId
	}
	return nil
}

func (x *SubscribeEventsFromStartBlockIDRequest) GetFilter() *EventFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *SubscribeEventsFromStartBlockIDRequest) GetHeartbeatInterval() uint64 {
	if x != nil {
		return x.HeartbeatInterval
	}
	return 0
}

func (x *SubscribeEventsFromStartBlockIDRequest) GetEventEncodingVersion() entities.EventEncodingVersion {
	if x != nil {
		return x.EventEncodingVersion
	}
	return entities.EventEncodingVersion(0)
}

func (x *SubscribeEventsFromStartBlockIDRequest) GetExecutionStateQuery() *entities.ExecutionStateQuery {
	if x != nil {
		return x.ExecutionStateQuery
	}
	return nil
}

// The request for SubscribeEventsFromStartHeight
type SubscribeEventsFromStartHeightRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Block height of the first block to search for events.
	StartBlockHeight uint64 `protobuf:"varint,1,opt,name=start_block_height,json=startBlockHeight,proto3" json:"start_block_height,omitempty"`
	// Filter to apply to events for each block searched.
	// If no filter is provided, all events are returned.
	Filter *EventFilter `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	// Interval in block heights at which the server should return a heartbeat
	// message to the client. The heartbeat is a normal SubscribeEventsResponse
	// with no events, and allows clients to track which blocks were searched.
	// Clients can use this information to determine which block to start from
	// when reconnecting.
	//
	// The interval is calculated from the last response returned, which could be
	// either another heartbeat or a response containing events.
	HeartbeatInterval uint64 `protobuf:"varint,3,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"`
	// Preferred event encoding version of the block events payload.
	// Possible variants:
	// 1. CCF
	// 2. JSON-CDC
	EventEncodingVersion entities.EventEncodingVersion `protobuf:"varint,4,opt,name=event_encoding_version,json=eventEncodingVersion,proto3,enum=flow.entities.EventEncodingVersion" json:"event_encoding_version,omitempty"`
	// Criteria for selecting which executors to use when fetching data.
	ExecutionStateQuery *entities.ExecutionStateQuery `protobuf:"bytes,5,opt,name=execution_state_query,json=executionStateQuery,proto3" json:"execution_state_query,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SubscribeEventsFromStartHeightRequest) Reset() {
	*x = SubscribeEventsFromStartHeightRequest{}
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEventsFromStartHeightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEventsFromStartHeightRequest) ProtoMessage() {}

func (x *SubscribeEventsFromStartHeightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEventsFromStartHeightRequest.ProtoReflect.Descriptor instead.
func (*SubscribeEventsFromStartHeightRequest) Descriptor() ([]byte, []int) {
	return file_flow_executiondata_executiondata_proto_rawDescGZIP(), []int{9}
}

func (x *SubscribeEventsFromStartHeightRequest) GetStartBlockHeight() uint64 {
	if x != nil {
		return x.StartBlockHeight
	}
	return 0
}

func (x *SubscribeEventsFromStartHeightRequest) GetFilter() *EventFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *SubscribeEventsFromStartHeightRequest) GetHeartbeatInterval() uint64 {
	if x != nil {
		return x.HeartbeatInterval
	}
	return 0
}

func (x *SubscribeEventsFromStartHeightRequest) GetEventEncodingVersion() entities.EventEncodingVersion {
	if x != nil {
		return x.EventEncodingVersion
	}
	return entities.EventEncodingVersion(0)
}

func (x *SubscribeEventsFromStartHeightRequest) GetExecutionStateQuery() *entities.ExecutionStateQuery {
	if x != nil {
		return x.ExecutionStateQuery
	}
	return nil
}

// The request for SubscribeEventsFromLatest
type SubscribeEventsFromLatestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter to apply to events for each block searched.
	// If no filter is provided, all events are returned.
	Filter *EventFilter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	// Interval in block heights at which the server should return a heartbeat
	// message to the client. The heartbeat is a normal SubscribeEventsResponse
	// with no events, and allows clients to track which blocks were searched.
	// Clients can use this information to determine which block to start from
	// when reconnecting.
	//
	// The interval is calculated from the last response returned, which could be
	// either another heartbeat or a response containing events.
	HeartbeatInterval uint64 `protobuf:"varint,2,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"`
	// Preferred event encoding version of the block events payload.
	// Possible variants:
	// 1. CCF
	// 2. JSON-CDC
	EventEncodingVersion entities.EventEncodingVersion `protobuf:"varint,3,opt,name=event_encoding_version,json=eventEncodingVersion,proto3,enum=flow.entities.EventEncodingVersion" json:"event_encoding_version,omitempty"`
	// Criteria for selecting which executors to use when fetching data.
	ExecutionStateQuery *entities.ExecutionStateQuery `protobuf:"bytes,4,opt,name=execution_state_query,json=executionStateQuery,proto3" json:"execution_state_query,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SubscribeEventsFromLatestRequest) Reset() {
	*x = SubscribeEventsFromLatestRequest{}
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEventsFromLatestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEventsFromLatestRequest) ProtoMessage() {}

func (x *SubscribeEventsFromLatestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEventsFromLatestRequest.ProtoReflect.Descriptor instead.
func (*SubscribeEventsFromLatestRequest) Descriptor() ([]byte, []int) {
	return file_flow_executiondata_executiondata_proto_rawDescGZIP(), []int{10}
}

func (x *SubscribeEventsFromLatestRequest) GetFilter() *EventFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *SubscribeEventsFromLatestRequest) GetHeartbeatInterval() uint64 {
	if x != nil {
		return x.HeartbeatInterval
	}
	return 0
}

func (x *SubscribeEventsFromLatestRequest) GetEventEncodingVersion() entities.EventEncodingVersion {
	if x != nil {
		return x.EventEncodingVersion
	}
	return entities.EventEncodingVersion(0)
}

func (x *SubscribeEventsFromLatestRequest) GetExecutionStateQuery() *entities.ExecutionStateQuery {
	if x != nil {
		return x.ExecutionStateQuery
	}
	return nil
}

// The response for SubscribeEvents
type SubscribeEventsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Block ID of the block containing the events.
	BlockId []byte `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	// Block height of the block containing the events.
	BlockHeight uint64 `protobuf:"varint,2,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	// Events matching the EventFilter in the request.
	// The API may return no events which signals a periodic heartbeat. This
	// allows clients to track which blocks were searched. Client can use this
	// information to determine which block to start from when reconnecting.
	Events []*entities.Event `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	// Timestamp from the block containing the events.
	BlockTimestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=block_timestamp,json=blockTimestamp,proto3" json:"block_timestamp,omitempty"`
	// The message index of the response message. Used by the client to ensure
	// they received all messages. Starts from "0".
	MessageIndex uint64 `protobuf:"varint,5,opt,name=message_index,json=messageIndex,proto3" json:"message_index,omitempty"`
	// Metadata about the execution result that was used to produce this response.
	ExecutorMetadata *entities.ExecutorMetadata `protobuf:"bytes,6,opt,name=executor_metadata,json=executorMetadata,proto3" json:"executor_metadata,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SubscribeEventsResponse) Reset() {
	*x = SubscribeEventsResponse{}
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEventsResponse) ProtoMessage() {}

func (x *SubscribeEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEventsResponse.ProtoReflect.Descriptor instead.
func (*SubscribeEventsResponse) Descriptor() ([]byte, []int) {
	return file_flow_executiondata_executiondata_proto_rawDescGZIP(), []int{11}
}

func (x *SubscribeEventsResponse) GetBlockId() []byte {
	if x != nil {
		return x.BlockId
	}
	return nil
}

func (x *SubscribeEventsResponse) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *SubscribeEventsResponse) GetEvents() []*entities.Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *SubscribeEventsResponse) GetBlockTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.BlockTimestamp
	}
	return nil
}

func (x *SubscribeEventsResponse) GetMessageIndex() uint64 {
	if x != nil {
		return x.MessageIndex
	}
	return 0
}

func (x *SubscribeEventsResponse) GetExecutorMetadata() *entities.ExecutorMetadata {
	if x != nil {
		return x.ExecutorMetadata
	}
	return nil
}

// EventFilter defines the filter to apply to block events.
// Filters are applied as an OR operation, i.e. any event matching any of the
// filters is returned. If no filters are provided, all events are returned. If
// there are any invalid filters, the API will return an InvalidArgument error.
type EventFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of full event types to include.
	//
	// All events exactly matching any of the provided event types will be
	// returned.
	//
	// Event types have 2 formats:
	//   - Protocol events:
	//     flow.[event name]
	//   - Smart contract events:
	//     A.[contract address].[contract name].[event name]
	EventType []string `protobuf:"bytes,1,rep,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// A list of contracts who's events should be included.
	//
	// All events emitted by any of the provided contracts will be returned.
	//
	// Contracts have the following name formats:
	//   - Protocol events:
	//     flow
	//   - Smart contract events:
	//     A.[contract address].[contract name]
	//
	// This filter matches on the full contract including its address, not just
	// the contract's name.
	Contract []string `protobuf:"bytes,2,rep,name=contract,proto3" json:"contract,omitempty"`
	// A list of addresses who's events should be included.
	//
	// All events emitted by any contract held by any of the provided addresses
	// will be returned.
	//
	// Addresses must be Flow account addresses in hex format and valid for the
	// network the node is connected to. i.e. only a mainnet address is valid for
	// a mainnet node. Addresses may optionally include the 0x prefix.
	Address       []string `protobuf:"bytes,3,rep,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventFilter) Reset() {
	*x = EventFilter{}
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventFilter) ProtoMessage() {}

func (x *EventFilter) ProtoReflect() protoreflect.Message {
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventFilter.ProtoReflect.Descriptor instead.
func (*EventFilter) Descriptor() ([]byte, []int) {
	return file_flow_executiondata_executiondata_proto_rawDescGZIP(), []int{12}
}

func (x *EventFilter) GetEventType() []string {
	if x != nil {
		return x.EventType
	}
	return nil
}

func (x *EventFilter) GetContract() []string {
	if x != nil {
		return x.Contract
	}
	return nil
}

func (x *EventFilter) GetAddress() []string {
	if x != nil {
		return x.Address
	}
	return nil
}

// request for GetRegisterValues
type GetRegisterValuesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Block height of the execution state being queried.
	BlockHeight uint64 `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	// Register IDs of the Ledger.RegisterID format with an owner and key.
	RegisterIds []*entities.RegisterID `protobuf:"bytes,2,rep,name=register_ids,json=registerIds,proto3" json:"register_ids,omitempty"`
	// Criteria for selecting which executors to use when fetching data.
	ExecutionStateQuery *entities.ExecutionStateQuery `protobuf:"bytes,3,opt,name=execution_state_query,json=executionStateQuery,proto3" json:"execution_state_query,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetRegisterValuesRequest) Reset() {
	*x = GetRegisterValuesRequest{}
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRegisterValuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegisterValuesRequest) ProtoMessage() {}

func (x *GetRegisterValuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegisterValuesRequest.ProtoReflect.Descriptor instead.
func (*GetRegisterValuesRequest) Descriptor() ([]byte, []int) {
	return file_flow_executiondata_executiondata_proto_rawDescGZIP(), []int{13}
}

func (x *GetRegisterValuesRequest) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *GetRegisterValuesRequest) GetRegisterIds() []*entities.RegisterID {
	if x != nil {
		return x.RegisterIds
	}
	return nil
}

func (x *GetRegisterValuesRequest) GetExecutionStateQuery() *entities.ExecutionStateQuery {
	if x != nil {
		return x.ExecutionStateQuery
	}
	return nil
}

// response for GetRegisterValues
type GetRegisterValuesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// raw register values at the given height.
	Values [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	// Metadata about the execution result that was used to produce this response.
	ExecutorMetadata *entities.ExecutorMetadata `protobuf:"bytes,2,opt,name=executor_metadata,json=executorMetadata,proto3" json:"executor_metadata,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetRegisterValuesResponse) Reset() {
	*x = GetRegisterValuesResponse{}
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRegisterValuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegisterValuesResponse) ProtoMessage() {}

func (x *GetRegisterValuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegisterValuesResponse.ProtoReflect.Descriptor instead.
func (*GetRegisterValuesResponse) Descriptor() ([]byte, []int) {
	return file_flow_executiondata_executiondata_proto_rawDescGZIP(), []int{14}
}

func (x *GetRegisterValuesResponse) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *GetRegisterValuesResponse) GetExecutorMetadata() *entities.ExecutorMetadata {
	if x != nil {
		return x.ExecutorMetadata
	}
	return nil
}

// The request for SubscribeAccountStatusesFromStartBlockID
type SubscribeAccountStatusesFromStartBlockIDRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Block ID of the first block to search for events.
	// Only one of start_block_id and start_block_height may be provided,
	// otherwise an InvalidArgument error is returned. If neither are provided,
	// the latest sealed block is used.
	StartBlockId []byte `protobuf:"bytes,1,opt,name=start_block_id,json=startBlockId,proto3" json:"start_block_id,omitempty"`
	// Filter to apply to events for each block searched.
	// If no filter is provided, all statuses are returned.
	Filter *StatusFilter `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	// Interval in block heights at which the server should return a heartbeat
	// message to the client. The heartbeat is a normal
	// SubscribeAccountStatusesResponse with no events, and allows clients to
	// track which blocks were searched. Clients can use this information to
	// determine which block to start from when reconnecting.
	//
	// The interval is calculated from the last response returned, which could be
	// either another heartbeat or a response containing events.
	HeartbeatInterval uint64 `protobuf:"varint,3,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"`
	// Preferred event encoding version of the block events payload.
	// Possible variants:
	// 1. CCF
	// 2. JSON-CDC
	EventEncodingVersion entities.EventEncodingVersion `protobuf:"varint,4,opt,name=event_encoding_version,json=eventEncodingVersion,proto3,enum=flow.entities.EventEncodingVersion" json:"event_encoding_version,omitempty"`
	// Criteria for selecting which executors to use when fetching data.
	ExecutionStateQuery *entities.ExecutionStateQuery `protobuf:"bytes,5,opt,name=execution_state_query,json=executionStateQuery,proto3" json:"execution_state_query,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SubscribeAccountStatusesFromStartBlockIDRequest) Reset() {
	*x = SubscribeAccountStatusesFromStartBlockIDRequest{}
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeAccountStatusesFromStartBlockIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeAccountStatusesFromStartBlockIDRequest) ProtoMessage() {}

func (x *SubscribeAccountStatusesFromStartBlockIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeAccountStatusesFromStartBlockIDRequest.ProtoReflect.Descriptor instead.
func (*SubscribeAccountStatusesFromStartBlockIDRequest) Descriptor() ([]byte, []int) {
	return file_flow_executiondata_executiondata_proto_rawDescGZIP(), []int{15}
}

func (x *SubscribeAccountStatusesFromStartBlockIDRequest) GetStartBlockId() []byte {
	if x != nil {
		return x.StartBlockId
	}
	return nil
}

func (x *SubscribeAccountStatusesFromStartBlockIDRequest) GetFilter() *StatusFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *SubscribeAccountStatusesFromStartBlockIDRequest) GetHeartbeatInterval() uint64 {
	if x != nil {
		return x.HeartbeatInterval
	}
	return 0
}

func (x *SubscribeAccountStatusesFromStartBlockIDRequest) GetEventEncodingVersion() entities.EventEncodingVersion {
	if x != nil {
		return x.EventEncodingVersion
	}
	return entities.EventEncodingVersion(0)
}

func (x *SubscribeAccountStatusesFromStartBlockIDRequest) GetExecutionStateQuery() *entities.ExecutionStateQuery {
	if x != nil {
		return x.ExecutionStateQuery
	}
	return nil
}

// The request for SubscribeAccountStatusesFromStartHeight
type SubscribeAccountStatusesFromStartHeightRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Block height of the first block to search for events.
	// Only one of start_block_id and start_block_height may be provided,
	// otherwise an InvalidArgument error is returned. If neither are provided,
	// the latest sealed block is used.
	StartBlockHeight uint64 `protobuf:"varint,1,opt,name=start_block_height,json=startBlockHeight,proto3" json:"start_block_height,omitempty"`
	// Filter to apply to events for each block searched.
	// If no filter is provided, all statuses are returned.
	Filter *StatusFilter `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	// Interval in block heights at which the server should return a heartbeat
	// message to the client. The heartbeat is a normal
	// SubscribeAccountStatusesResponse with no events, and allows clients to
	// track which blocks were searched. Clients can use this information to
	// determine which block to start from when reconnecting.
	//
	// The interval is calculated from the last response returned, which could be
	// either another heartbeat or a response containing events.
	HeartbeatInterval uint64 `protobuf:"varint,3,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"`
	// Preferred event encoding version of the block events payload.
	// Possible variants:
	// 1. CCF
	// 2. JSON-CDC
	EventEncodingVersion entities.EventEncodingVersion `protobuf:"varint,4,opt,name=event_encoding_version,json=eventEncodingVersion,proto3,enum=flow.entities.EventEncodingVersion" json:"event_encoding_version,omitempty"`
	// Criteria for selecting which executors to use when fetching data.
	ExecutionStateQuery *entities.ExecutionStateQuery `protobuf:"bytes,5,opt,name=execution_state_query,json=executionStateQuery,proto3" json:"execution_state_query,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SubscribeAccountStatusesFromStartHeightRequest) Reset() {
	*x = SubscribeAccountStatusesFromStartHeightRequest{}
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeAccountStatusesFromStartHeightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeAccountStatusesFromStartHeightRequest) ProtoMessage() {}

func (x *SubscribeAccountStatusesFromStartHeightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeAccountStatusesFromStartHeightRequest.ProtoReflect.Descriptor instead.
func (*SubscribeAccountStatusesFromStartHeightRequest) Descriptor() ([]byte, []int) {
	return file_flow_executiondata_executiondata_proto_rawDescGZIP(), []int{16}
}

func (x *SubscribeAccountStatusesFromStartHeightRequest) GetStartBlockHeight() uint64 {
	if x != nil {
		return x.StartBlockHeight
	}
	return 0
}

func (x *SubscribeAccountStatusesFromStartHeightRequest) GetFilter() *StatusFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *SubscribeAccountStatusesFromStartHeightRequest) GetHeartbeatInterval() uint64 {
	if x != nil {
		return x.HeartbeatInterval
	}
	return 0
}

func (x *SubscribeAccountStatusesFromStartHeightRequest) GetEventEncodingVersion() entities.EventEncodingVersion {
	if x != nil {
		return x.EventEncodingVersion
	}
	return entities.EventEncodingVersion(0)
}

func (x *SubscribeAccountStatusesFromStartHeightRequest) GetExecutionStateQuery() *entities.ExecutionStateQuery {
	if x != nil {
		return x.ExecutionStateQuery
	}
	return nil
}

// The request for SubscribeAccountStatusesFromLatestBlock
type SubscribeAccountStatusesFromLatestBlockRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter to apply to events for each block searched.
	// If no filter is provided, all statuses are returned.
	Filter *StatusFilter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	// Interval in block heights at which the server should return a heartbeat
	// message to the client. The heartbeat is a normal
	// SubscribeAccountStatusesResponse with no events, and allows clients to
	// track which blocks were searched. Clients can use this information to
	// determine which block to start from when reconnecting.
	//
	// The interval is calculated from the last response returned, which could be
	// either another heartbeat or a response containing events.
	HeartbeatInterval uint64 `protobuf:"varint,2,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"`
	// Preferred event encoding version of the block events payload.
	// Possible variants:
	// 1. CCF
	// 2. JSON-CDC
	EventEncodingVersion entities.EventEncodingVersion `protobuf:"varint,3,opt,name=event_encoding_version,json=eventEncodingVersion,proto3,enum=flow.entities.EventEncodingVersion" json:"event_encoding_version,omitempty"`
	// Criteria for selecting which executors to use when fetching data.
	ExecutionStateQuery *entities.ExecutionStateQuery `protobuf:"bytes,4,opt,name=execution_state_query,json=executionStateQuery,proto3" json:"execution_state_query,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SubscribeAccountStatusesFromLatestBlockRequest) Reset() {
	*x = SubscribeAccountStatusesFromLatestBlockRequest{}
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeAccountStatusesFromLatestBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeAccountStatusesFromLatestBlockRequest) ProtoMessage() {}

func (x *SubscribeAccountStatusesFromLatestBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeAccountStatusesFromLatestBlockRequest.ProtoReflect.Descriptor instead.
func (*SubscribeAccountStatusesFromLatestBlockRequest) Descriptor() ([]byte, []int) {
	return file_flow_executiondata_executiondata_proto_rawDescGZIP(), []int{17}
}

func (x *SubscribeAccountStatusesFromLatestBlockRequest) GetFilter() *StatusFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *SubscribeAccountStatusesFromLatestBlockRequest) GetHeartbeatInterval() uint64 {
	if x != nil {
		return x.HeartbeatInterval
	}
	return 0
}

func (x *SubscribeAccountStatusesFromLatestBlockRequest) GetEventEncodingVersion() entities.EventEncodingVersion {
	if x != nil {
		return x.EventEncodingVersion
	}
	return entities.EventEncodingVersion(0)
}

func (x *SubscribeAccountStatusesFromLatestBlockRequest) GetExecutionStateQuery() *entities.ExecutionStateQuery {
	if x != nil {
		return x.ExecutionStateQuery
	}
	return nil
}

// The response for SubscribeAccountStatuses
type SubscribeAccountStatusesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Block ID of the block containing the events.
	BlockId []byte `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	// Block height of the block containing the events.
	BlockHeight uint64 `protobuf:"varint,2,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	// The message index of the response message. Used by the client to ensure
	// they received all messages. Starts from "0".
	MessageIndex uint64 `protobuf:"varint,3,opt,name=message_index,json=messageIndex,proto3" json:"message_index,omitempty"`
	// The API may return no results which signals a periodic heartbeat. This
	// allows clients to track which blocks were searched. Client can use this
	// information to determine which block to start from when reconnecting.
	Results []*SubscribeAccountStatusesResponse_Result `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty"`
	// Metadata about the execution result that was used to produce this response.
	ExecutorMetadata *entities.ExecutorMetadata `protobuf:"bytes,5,opt,name=executor_metadata,json=executorMetadata,proto3" json:"executor_metadata,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SubscribeAccountStatusesResponse) Reset() {
	*x = SubscribeAccountStatusesResponse{}
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeAccountStatusesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeAccountStatusesResponse) ProtoMessage() {}

func (x *SubscribeAccountStatusesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeAccountStatusesResponse.ProtoReflect.Descriptor instead.
func (*SubscribeAccountStatusesResponse) Descriptor() ([]byte, []int) {
	return file_flow_executiondata_executiondata_proto_rawDescGZIP(), []int{18}
}

func (x *SubscribeAccountStatusesResponse) GetBlockId() []byte {
	if x != nil {
		return x.BlockId
	}
	return nil
}

func (x *SubscribeAccountStatusesResponse) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *SubscribeAccountStatusesResponse) GetMessageIndex() uint64 {
	if x != nil {
		return x.MessageIndex
	}
	return 0
}

func (x *SubscribeAccountStatusesResponse) GetResults() []*SubscribeAccountStatusesResponse_Result {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SubscribeAccountStatusesResponse) GetExecutorMetadata() *entities.ExecutorMetadata {
	if x != nil {
		return x.ExecutorMetadata
	}
	return nil
}

// StatusesFilter defines the filter to apply to block events.
// Filters match for events with types in the included event_type list, that are
// related to at least one address from the provided address list. An event
// who's type matches but address does not is ignored, and vice versa. If no
// event_types are provided, all account related protocol event types are
// matched. If no addresses are provided, any address matches. If there are any
// invalid filters, the API will return an InvalidArgument error.
type StatusFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of full event types to include.
	//
	// All events exactly matching any of the provided event types will be
	// returned.
	//
	// Event types must be protocol events. e.g.
	//
	//	flow.[event name]
	EventType []string `protobuf:"bytes,1,rep,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// A list of addresses who's events should be included.
	//
	// All events matching the provided event_types that are related to any of the
	// provided addresses will be returned. If no addresses are provided, all
	// events matching event_types will be returned.
	//
	// Addresses must be Flow account addresses in hex format and valid for the
	// network the node is connected to. i.e. only a mainnet address is valid for
	// a mainnet node. Addresses may optionally include the 0x prefix.
	Address       []string `protobuf:"bytes,3,rep,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusFilter) Reset() {
	*x = StatusFilter{}
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusFilter) ProtoMessage() {}

func (x *StatusFilter) ProtoReflect() protoreflect.Message {
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusFilter.ProtoReflect.Descriptor instead.
func (*StatusFilter) Descriptor() ([]byte, []int) {
	return file_flow_executiondata_executiondata_proto_rawDescGZIP(), []int{19}
}

func (x *StatusFilter) GetEventType() []string {
	if x != nil {
		return x.EventType
	}
	return nil
}

func (x *StatusFilter) GetAddress() []string {
	if x != nil {
		return x.Address
	}
	return nil
}

type SubscribeAccountStatusesResponse_Result struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the account being streamed
	Address []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Events matching the StatusFilter in the request.
	Events        []*entities.Event `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeAccountStatusesResponse_Result) Reset() {
	*x = SubscribeAccountStatusesResponse_Result{}
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeAccountStatusesResponse_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeAccountStatusesResponse_Result) ProtoMessage() {}

func (x *SubscribeAccountStatusesResponse_Result) ProtoReflect() protoreflect.Message {
	mi := &file_flow_executiondata_executiondata_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeAccountStatusesResponse_Result.ProtoReflect.Descriptor instead.
func (*SubscribeAccountStatusesResponse_Result) Descriptor() ([]byte, []int) {
	return file_flow_executiondata_executiondata_proto_rawDescGZIP(), []int{18, 0}
}

func (x *SubscribeAccountStatusesResponse_Result) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *SubscribeAccountStatusesResponse_Result) GetEvents() []*entities.Event {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_flow_executiondata_executiondata_proto protoreflect.FileDescriptor

const file_flow_executiondata_executiondata_proto_rawDesc = "" +
	"\n" +
	"&flow/executiondata/executiondata.proto\x12\x12flow.executiondata\x1a(flow/entities/block_execution_data.proto\x1a\x19flow/entities/event.proto\x1a\x1cflow/entities/register.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#flow/entities/execution_state.proto\x1a\x1cflow/entities/metadata.proto\"\xf0\x01\n" +
	" GetExecutionDataByBlockIDRequest\x12\x19\n" +
	"\bblock_id\x18\x01 \x01(\fR\ablockId\x12Y\n" +
	"\x16event_encoding_version\x18\x02 \x01(\x0e2#.flow.entities.EventEncodingVersionR\x14eventEncodingVersion\x12V\n" +
	"\x15execution_state_query\x18\x03 \x01(\v2\".flow.entities.ExecutionStateQueryR\x13executionStateQuery\"\xc6\x01\n" +
	"!GetExecutionDataByBlockIDResponse\x12S\n" +
	"\x14block_execution_data\x18\x01 \x01(\v2!.flow.entities.BlockExecutionDataR\x12blockExecutionData\x12L\n" +
	"\x11executor_metadata\x18\x02 \x01(\v2\x1f.flow.entities.ExecutorMetadataR\x10executorMetadata\"\xa6\x02\n" +
	"\x1dSubscribeExecutionDataRequest\x12$\n" +
	"\x0estart_block_id\x18\x01 \x01(\fR\fstartBlockId\x12,\n" +
	"\x12start_block_height\x18\x02 \x01(\x04R\x10startBlockHeight\x12Y\n" +
	"\x16event_encoding_version\x18\x03 \x01(\x0e2#.flow.entities.EventEncodingVersionR\x14eventEncodingVersion\x12V\n" +
	"\x15execution_state_query\x18\x04 \x01(\v2\".flow.entities.ExecutionStateQueryR\x13executionStateQuery\"\xab\x02\n" +
	"\x1eSubscribeExecutionDataResponse\x12!\n" +
	"\fblock_height\x18\x01 \x01(\x04R\vblockHeight\x12S\n" +
	"\x14block_execution_data\x18\x02 \x01(\v2!.flow.entities.BlockExecutionDataR\x12blockExecutionData\x12C\n" +
	"\x0fblock_timestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0eblockTimestamp\x12L\n" +
	"\x11executor_metadata\x18\x04 \x01(\v2\x1f.flow.entities.ExecutorMetadataR\x10executorMetadata\"\x88\x02\n" +
	"-SubscribeExecutionDataFromStartBlockIDRequest\x12$\n" +
	"\x0estart_block_id\x18\x01 \x01(\fR\fstartBlockId\x12Y\n" +
	"\x16event_encoding_version\x18\x02 \x01(\x0e2#.flow.entities.EventEncodingVersionR\x14eventEncodingVersion\x12V\n" +
	"\x15execution_state_query\x18\x03 \x01(\v2\".flow.entities.ExecutionStateQueryR\x13executionStateQuery\"\x94\x02\n" +
	"1SubscribeExecutionDataFromStartBlockHeightRequest\x12,\n" +
	"\x12start_block_height\x18\x01 \x01(\x04R\x10startBlockHeight\x12Y\n" +
	"\x16event_encoding_version\x18\x02 \x01(\x0e2#.flow.entities.EventEncodingVersionR\x14eventEncodingVersion\x12V\n" +
	"\x15execution_state_query\x18\x03 \x01(\v2\".flow.entities.ExecutionStateQueryR\x13executionStateQuery\"\xdc\x01\n" +
	"'SubscribeExecutionDataFromLatestRequest\x12Y\n" +
	"\x16event_encoding_version\x18\x01 \x01(\x0e2#.flow.entities.EventEncodingVersionR\x14eventEncodingVersion\x12V\n" +
	"\x15execution_state_query\x18\x02 \x01(\v2\".flow.entities.ExecutionStateQueryR\x13executionStateQuery\"\x87\x03\n" +
	"\x16SubscribeEventsRequest\x12$\n" +
	"\x0estart_block_id\x18\x01 \x01(\fR\fstartBlockId\x12,\n" +
	"\x12start_block_height\x18\x02 \x01(\x04R\x10startBlockHeight\x127\n" +
	"\x06filter\x18\x03 \x01(\v2\x1f.flow.executiondata.EventFilterR\x06filter\x12-\n" +
	"\x12heartbeat_interval\x18\x04 \x01(\x04R\x11heartbeatInterval\x12Y\n" +
	"\x16event_encoding_version\x18\x05 \x01(\x0e2#.flow.entities.EventEncodingVersionR\x14eventEncodingVersion\x12V\n" +
	"\x15execution_state_query\x18\x06 \x01(\v2\".flow.entities.ExecutionStateQueryR\x13executionStateQuery\"\xe9\x02\n" +
	"&SubscribeEventsFromStartBlockIDRequest\x12$\n" +
	"\x0estart_block_id\x18\x01 \x01(\fR\fstartBlockId\x127\n" +
	"\x06filter\x18\x02 \x01(\v2\x1f.flow.executiondata.EventFilterR\x06filter\x12-\n" +
	"\x12heartbeat_interval\x18\x03 \x01(\x04R\x11heartbeatInterval\x12Y\n" +
	"\x16event_encoding_version\x18\x04 \x01(\x0e2#.flow.entities.EventEncodingVersionR\x14eventEncodingVersion\x12V\n" +
	"\x15execution_state_query\x18\x05 \x01(\v2\".flow.entities.ExecutionStateQueryR\x13executionStateQuery\"\xf0\x02\n" +
	"%SubscribeEventsFromStartHeightRequest\x12,\n" +
	"\x12start_block_height\x18\x01 \x01(\x04R\x10startBlockHeight\x127\n" +
	"\x06filter\x18\x02 \x01(\v2\x1f.flow.executiondata.EventFilterR\x06filter\x12-\n" +
	"\x12heartbeat_interval\x18\x03 \x01(\x04R\x11heartbeatInterval\x12Y\n" +
	"\x16event_encoding_version\x18\x04 \x01(\x0e2#.flow.entities.EventEncodingVersionR\x14eventEncodingVersion\x12V\n" +
	"\x15execution_state_query\x18\x05 \x01(\v2\".flow.entities.ExecutionStateQueryR\x13executionStateQuery\"\xbd\x02\n" +
	" SubscribeEventsFromLatestRequest\x127\n" +
	"\x06filter\x18\x01 \x01(\v2\x1f.flow.executiondata.EventFilterR\x06filter\x12-\n" +
	"\x12heartbeat_interval\x18\x02 \x01(\x04R\x11heartbeatInterval\x12Y\n" +
	"\x16event_encoding_version\x18\x03 \x01(\x0e2#.flow.entities.EventEncodingVersionR\x14eventEncodingVersion\x12V\n" +
	"\x15execution_state_query\x18\x04 \x01(\v2\".flow.entities.ExecutionStateQueryR\x13executionStateQuery\"\xbd\x02\n" +
	"\x17SubscribeEventsResponse\x12\x19\n" +
	"\bblock_id\x18\x01 \x01(\fR\ablockId\x12!\n" +
	"\fblock_height\x18\x02 \x01(\x04R\vblockHeight\x12,\n" +
	"\x06events\x18\x03 \x03(\v2\x14.flow.entities.EventR\x06events\x12C\n" +
	"\x0fblock_timestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0eblockTimestamp\x12#\n" +
	"\rmessage_index\x18\x05 \x01(\x04R\fmessageIndex\x12L\n" +
	"\x11executor_metadata\x18\x06 \x01(\v2\x1f.flow.entities.ExecutorMetadataR\x10executorMetadata\"b\n" +
	"\vEventFilter\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x03(\tR\teventType\x12\x1a\n" +
	"\bcontract\x18\x02 \x03(\tR\bcontract\x12\x18\n" +
	"\aaddress\x18\x03 \x03(\tR\aaddress\"\xd3\x01\n" +
	"\x18GetRegisterValuesRequest\x12!\n" +
	"\fblock_height\x18\x01 \x01(\x04R\vblockHeight\x12<\n" +
	"\fregister_ids\x18\x02 \x03(\v2\x19.flow.entities.RegisterIDR\vregisterIds\x12V\n" +
	"\x15execution_state_query\x18\x03 \x01(\v2\".flow.entities.ExecutionStateQueryR\x13executionStateQuery\"\x81\x01\n" +
	"\x19GetRegisterValuesResponse\x12\x16\n" +
	"\x06values\x18\x01 \x03(\fR\x06values\x12L\n" +
	"\x11executor_metadata\x18\x02 \x01(\v2\x1f.flow.entities.ExecutorMetadataR\x10executorMetadata\"\xf3\x02\n" +
	"/SubscribeAccountStatusesFromStartBlockIDRequest\x12$\n" +
	"\x0estart_block_id\x18\x01 \x01(\fR\fstartBlockId\x128\n" +
	"\x06filter\x18\x02 \x01(\v2 .flow.executiondata.StatusFilterR\x06filter\x12-\n" +
	"\x12heartbeat_interval\x18\x03 \x01(\x04R\x11heartbeatInterval\x12Y\n" +
	"\x16event_encoding_version\x18\x04 \x01(\x0e2#.flow.entities.EventEncodingVersionR\x14eventEncodingVersion\x12V\n" +
	"\x15execution_state_query\x18\x05 \x01(\v2\".flow.entities.ExecutionStateQueryR\x13executionStateQuery\"\xfa\x02\n" +
	".SubscribeAccountStatusesFromStartHeightRequest\x12,\n" +
	"\x12start_block_height\x18\x01 \x01(\x04R\x10startBlockHeight\x128\n" +
	"\x06filter\x18\x02 \x01(\v2 .flow.executiondata.StatusFilterR\x06filter\x12-\n" +
	"\x12heartbeat_interval\x18\x03 \x01(\x04R\x11heartbeatInterval\x12Y\n" +
	"\x16event_encoding_version\x18\x04 \x01(\x0e2#.flow.entities.EventEncodingVersionR\x14eventEncodingVersion\x12V\n" +
	"\x15execution_state_query\x18\x05 \x01(\v2\".flow.entities.ExecutionStateQueryR\x13executionStateQuery\"\xcc\x02\n" +
	".SubscribeAccountStatusesFromLatestBlockRequest\x128\n" +
	"\x06filter\x18\x01 \x01(\v2 .flow.executiondata.StatusFilterR\x06filter\x12-\n" +
	"\x12heartbeat_interval\x18\x02 \x01(\x04R\x11heartbeatInterval\x12Y\n" +
	"\x16event_encoding_version\x18\x03 \x01(\x0e2#.flow.entities.EventEncodingVersionR\x14eventEncodingVersion\x12V\n" +
	"\x15execution_state_query\x18\x04 \x01(\v2\".flow.entities.ExecutionStateQueryR\x13executionStateQuery\"\xfc\x02\n" +
	" SubscribeAccountStatusesResponse\x12\x19\n" +
	"\bblock_id\x18\x01 \x01(\fR\ablockId\x12!\n" +
	"\fblock_height\x18\x02 \x01(\x04R\vblockHeight\x12#\n" +
	"\rmessage_index\x18\x03 \x01(\x04R\fmessageIndex\x12U\n" +
	"\aresults\x18\x04 \x03(\v2;.flow.executiondata.SubscribeAccountStatusesResponse.ResultR\aresults\x12L\n" +
	"\x11executor_metadata\x18\x05 \x01(\v2\x1f.flow.entities.ExecutorMetadataR\x10executorMetadata\x1aP\n" +
	"\x06Result\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\x12,\n" +
	"\x06events\x18\x02 \x03(\v2\x14.flow.entities.EventR\x06events\"G\n" +
	"\fStatusFilter\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x03(\tR\teventType\x12\x18\n" +
	"\aaddress\x18\x03 \x03(\tR\aaddress2\x8c\x0f\n" +
	"\x10ExecutionDataAPI\x12\x88\x01\n" +
	"\x19GetExecutionDataByBlockID\x124.flow.executiondata.GetExecutionDataByBlockIDRequest\x1a5.flow.executiondata.GetExecutionDataByBlockIDResponse\x12\x86\x01\n" +
	"\x16SubscribeExecutionData\x121.flow.executiondata.SubscribeExecutionDataRequest\x1a2.flow.executiondata.SubscribeExecutionDataResponse\"\x03\x88\x02\x010\x01\x12\xa1\x01\n" +
	"&SubscribeExecutionDataFromStartBlockID\x12A.flow.executiondata.SubscribeExecutionDataFromStartBlockIDRequest\x1a2.flow.executiondata.SubscribeExecutionDataResponse0\x01\x12\xa9\x01\n" +
	"*SubscribeExecutionDataFromStartBlockHeight\x12E.flow.executiondata.SubscribeExecutionDataFromStartBlockHeightRequest\x1a2.flow.executiondata.SubscribeExecutionDataResponse0\x01\x12\x95\x01\n" +
	" SubscribeExecutionDataFromLatest\x12;.flow.executiondata.SubscribeExecutionDataFromLatestRequest\x1a2.flow.executiondata.SubscribeExecutionDataResponse0\x01\x12q\n" +
	"\x0fSubscribeEvents\x12*.flow.executiondata.SubscribeEventsRequest\x1a+.flow.executiondata.SubscribeEventsResponse\"\x03\x88\x02\x010\x01\x12\x8c\x01\n" +
	"\x1fSubscribeEventsFromStartBlockID\x12:.flow.executiondata.SubscribeEventsFromStartBlockIDRequest\x1a+.flow.executiondata.SubscribeEventsResponse0\x01\x12\x8a\x01\n" +
	"\x1eSubscribeEventsFromStartHeight\x129.flow.executiondata.SubscribeEventsFromStartHeightRequest\x1a+.flow.executiondata.SubscribeEventsResponse0\x01\x12\x80\x01\n" +
	"\x19SubscribeEventsFromLatest\x124.flow.executiondata.SubscribeEventsFromLatestRequest\x1a+.flow.executiondata.SubscribeEventsResponse0\x01\x12p\n" +
	"\x11GetRegisterValues\x12,.flow.executiondata.GetRegisterValuesRequest\x1a-.flow.executiondata.GetRegisterValuesResponse\x12\xa7\x01\n" +
	"(SubscribeAccountStatusesFromStartBlockID\x12C.flow.executiondata.SubscribeAccountStatusesFromStartBlockIDRequest\x1a4.flow.executiondata.SubscribeAccountStatusesResponse0\x01\x12\xa5\x01\n" +
	"'SubscribeAccountStatusesFromStartHeight\x12B.flow.executiondata.SubscribeAccountStatusesFromStartHeightRequest\x1a4.flow.executiondata.SubscribeAccountStatusesResponse0\x01\x12\xa5\x01\n" +
	"'SubscribeAccountStatusesFromLatestBlock\x12B.flow.executiondata.SubscribeAccountStatusesFromLatestBlockRequest\x1a4.flow.executiondata.SubscribeAccountStatusesResponse0\x01BZ\n" +
	"!org.onflow.protobuf.executiondataZ5github.com/onflow/flow/protobuf/go/flow/executiondatab\x06proto3"

var (
	file_flow_executiondata_executiondata_proto_rawDescOnce sync.Once
	file_flow_executiondata_executiondata_proto_rawDescData []byte
)

func file_flow_executiondata_executiondata_proto_rawDescGZIP() []byte {
	file_flow_executiondata_executiondata_proto_rawDescOnce.Do(func() {
		file_flow_executiondata_executiondata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flow_executiondata_executiondata_proto_rawDesc), len(file_flow_executiondata_executiondata_proto_rawDesc)))
	})
	return file_flow_executiondata_executiondata_proto_rawDescData
}

var file_flow_executiondata_executiondata_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_flow_executiondata_executiondata_proto_goTypes = []any{
	(*GetExecutionDataByBlockIDRequest)(nil),                  // 0: flow.executiondata.GetExecutionDataByBlockIDRequest
	(*GetExecutionDataByBlockIDResponse)(nil),                 // 1: flow.executiondata.GetExecutionDataByBlockIDResponse
	(*SubscribeExecutionDataRequest)(nil),                     // 2: flow.executiondata.SubscribeExecutionDataRequest
	(*SubscribeExecutionDataResponse)(nil),                    // 3: flow.executiondata.SubscribeExecutionDataResponse
	(*SubscribeExecutionDataFromStartBlockIDRequest)(nil),     // 4: flow.executiondata.SubscribeExecutionDataFromStartBlockIDRequest
	(*SubscribeExecutionDataFromStartBlockHeightRequest)(nil), // 5: flow.executiondata.SubscribeExecutionDataFromStartBlockHeightRequest
	(*SubscribeExecutionDataFromLatestRequest)(nil),           // 6: flow.executiondata.SubscribeExecutionDataFromLatestRequest
	(*SubscribeEventsRequest)(nil),                            // 7: flow.executiondata.SubscribeEventsRequest
	(*SubscribeEventsFromStartBlockIDRequest)(nil),            // 8: flow.executiondata.SubscribeEventsFromStartBlockIDRequest
	(*SubscribeEventsFromStartHeightRequest)(nil),             // 9: flow.executiondata.SubscribeEventsFromStartHeightRequest
	(*SubscribeEventsFromLatestRequest)(nil),                  // 10: flow.executiondata.SubscribeEventsFromLatestRequest
	(*SubscribeEventsResponse)(nil),                           // 11: flow.executiondata.SubscribeEventsResponse
	(*EventFilter)(nil),                                       // 12: flow.executiondata.EventFilter
	(*GetRegisterValuesRequest)(nil),                          // 13: flow.executiondata.GetRegisterValuesRequest
	(*GetRegisterValuesResponse)(nil),                         // 14: flow.executiondata.GetRegisterValuesResponse
	(*SubscribeAccountStatusesFromStartBlockIDRequest)(nil),   // 15: flow.executiondata.SubscribeAccountStatusesFromStartBlockIDRequest
	(*SubscribeAccountStatusesFromStartHeightRequest)(nil),    // 16: flow.executiondata.SubscribeAccountStatusesFromStartHeightRequest
	(*SubscribeAccountStatusesFromLatestBlockRequest)(nil),    // 17: flow.executiondata.SubscribeAccountStatusesFromLatestBlockRequest
	(*SubscribeAccountStatusesResponse)(nil),                  // 18: flow.executiondata.SubscribeAccountStatusesResponse
	(*StatusFilter)(nil),                                      // 19: flow.executiondata.StatusFilter
	(*SubscribeAccountStatusesResponse_Result)(nil),           // 20: flow.executiondata.SubscribeAccountStatusesResponse.Result
	(entities.EventEncodingVersion)(0),                        // 21: flow.entities.EventEncodingVersion
	(*entities.ExecutionStateQuery)(nil),                      // 22: flow.entities.ExecutionStateQuery
	(*entities.BlockExecutionData)(nil),                       // 23: flow.entities.BlockExecutionData
	(*entities.ExecutorMetadata)(nil),                         // 24: flow.entities.ExecutorMetadata
	(*timestamppb.Timestamp)(nil),                             // 25: google.protobuf.Timestamp
	(*entities.Event)(nil),                                    // 26: flow.entities.Event
	(*entities.RegisterID)(nil),                               // 27: flow.entities.RegisterID
}
var file_flow_executiondata_executiondata_proto_depIdxs = []int32{
	21, // 0: flow.executiondata.GetExecutionDataByBlockIDRequest.event_encoding_version:type_name -> flow.entities.EventEncodingVersion
	22, // 1: flow.executiondata.GetExecutionDataByBlockIDRequest.execution_state_query:type_name -> flow.entities.ExecutionStateQuery
	23, // 2: flow.executiondata.GetExecutionDataByBlockIDResponse.block_execution_data:type_name -> flow.entities.BlockExecutionData
	24, // 3: flow.executiondata.GetExecutionDataByBlockIDResponse.executor_metadata:type_name -> flow.entities.ExecutorMetadata
	21, // 4: flow.executiondata.SubscribeExecutionDataRequest.event_encoding_version:type_name -> flow.entities.EventEncodingVersion
	22, // 5: flow.executiondata.SubscribeExecutionDataRequest.execution_state_query:type_name -> flow.entities.ExecutionStateQuery
	23, // 6: flow.executiondata.SubscribeExecutionDataResponse.block_execution_data:type_name -> flow.entities.BlockExecutionData
	25, // 7: flow.executiondata.SubscribeExecutionDataResponse.block_timestamp:type_name -> google.protobuf.Timestamp
	24, // 8: flow.executiondata.SubscribeExecutionDataResponse.executor_metadata:type_name -> flow.entities.ExecutorMetadata
	21, // 9: flow.executiondata.SubscribeExecutionDataFromStartBlockIDRequest.event_encoding_version:type_name -> flow.entities.EventEncodingVersion
	22, // 10: flow.executiondata.SubscribeExecutionDataFromStartBlockIDRequest.execution_state_query:type_name -> flow.entities.ExecutionStateQuery
	21, // 11: flow.executiondata.SubscribeExecutionDataFromStartBlockHeightRequest.event_encoding_version:type_name -> flow.entities.EventEncodingVersion
	22, // 12: flow.executiondata.SubscribeExecutionDataFromStartBlockHeightRequest.execution_state_query:type_name -> flow.entities.ExecutionStateQuery
	21, // 13: flow.executiondata.SubscribeExecutionDataFromLatestRequest.event_encoding_version:type_name -> flow.entities.EventEncodingVersion
	22, // 14: flow.executiondata.SubscribeExecutionDataFromLatestRequest.execution_state_query:type_name -> flow.entities.ExecutionStateQuery
	12, // 15: flow.executiondata.SubscribeEventsRequest.filter:type_name -> flow.executiondata.EventFilter
	21, // 16: flow.executiondata.SubscribeEventsRequest.event_encoding_version:type_name -> flow.entities.EventEncodingVersion
	22, // 17: flow.executiondata.SubscribeEventsRequest.execution_state_query:type_name -> flow.entities.ExecutionStateQuery
	12, // 18: flow.executiondata.SubscribeEventsFromStartBlockIDRequest.filter:type_name -> flow.executiondata.EventFilter
	21, // 19: flow.executiondata.SubscribeEventsFromStartBlockIDRequest.event_encoding_version:type_name -> flow.entities.EventEncodingVersion
	22, // 20: flow.executiondata.SubscribeEventsFromStartBlockIDRequest.execution_state_query:type_name -> flow.entities.ExecutionStateQuery
	12, // 21: flow.executiondata.SubscribeEventsFromStartHeightRequest.filter:type_name -> flow.executiondata.EventFilter
	21, // 22: flow.executiondata.SubscribeEventsFromStartHeightRequest.event_encoding_version:type_name -> flow.entities.EventEncodingVersion
	22, // 23: flow.executiondata.SubscribeEventsFromStartHeightRequest.execution_state_query:type_name -> flow.entities.ExecutionStateQuery
	12, // 24: flow.executiondata.SubscribeEventsFromLatestRequest.filter:type_name -> flow.executiondata.EventFilter
	21, // 25: flow.executiondata.SubscribeEventsFromLatestRequest.event_encoding_version:type_name -> flow.entities.EventEncodingVersion
	22, // 26: flow.executiondata.SubscribeEventsFromLatestRequest.execution_state_query:type_name -> flow.entities.ExecutionStateQuery
	26, // 27: flow.executiondata.SubscribeEventsResponse.events:type_name -> flow.entities.Event
	25, // 28: flow.executiondata.SubscribeEventsResponse.block_timestamp:type_name -> google.protobuf.Timestamp
	24, // 29: flow.executiondata.SubscribeEventsResponse.executor_metadata:type_name -> flow.entities.ExecutorMetadata
	27, // 30: flow.executiondata.GetRegisterValuesRequest.register_ids:type_name -> flow.entities.RegisterID
	22, // 31: flow.executiondata.GetRegisterValuesRequest.execution_state_query:type_name -> flow.entities.ExecutionStateQuery
	24, // 32: flow.executiondata.GetRegisterValuesResponse.executor_metadata:type_name -> flow.entities.ExecutorMetadata
	19, // 33: flow.executiondata.SubscribeAccountStatusesFromStartBlockIDRequest.filter:type_name -> flow.executiondata.StatusFilter
	21, // 34: flow.executiondata.SubscribeAccountStatusesFromStartBlockIDRequest.event_encoding_version:type_name -> flow.entities.EventEncodingVersion
	22, // 35: flow.executiondata.SubscribeAccountStatusesFromStartBlockIDRequest.execution_state_query:type_name -> flow.entities.ExecutionStateQuery
	19, // 36: flow.executiondata.SubscribeAccountStatusesFromStartHeightRequest.filter:type_name -> flow.executiondata.StatusFilter
	21, // 37: flow.executiondata.SubscribeAccountStatusesFromStartHeightRequest.event_encoding_version:type_name -> flow.entities.EventEncodingVersion
	22, // 38: flow.executiondata.SubscribeAccountStatusesFromStartHeightRequest.execution_state_query:type_name -> flow.entities.ExecutionStateQuery
	19, // 39: flow.executiondata.SubscribeAccountStatusesFromLatestBlockRequest.filter:type_name -> flow.executiondata.StatusFilter
	21, // 40: flow.executiondata.SubscribeAccountStatusesFromLatestBlockRequest.event_encoding_version:type_name -> flow.entities.EventEncodingVersion
	22, // 41: flow.executiondata.SubscribeAccountStatusesFromLatestBlockRequest.execution_state_query:type_name -> flow.entities.ExecutionStateQuery
	20, // 42: flow.executiondata.SubscribeAccountStatusesResponse.results:type_name -> flow.executiondata.SubscribeAccountStatusesResponse.Result
	24, // 43: flow.executiondata.SubscribeAccountStatusesResponse.executor_metadata:type_name -> flow.entities.ExecutorMetadata
	26, // 44: flow.executiondata.SubscribeAccountStatusesResponse.Result.events:type_name -> flow.entities.Event
	0,  // 45: flow.executiondata.ExecutionDataAPI.GetExecutionDataByBlockID:input_type -> flow.executiondata.GetExecutionDataByBlockIDRequest
	2,  // 46: flow.executiondata.ExecutionDataAPI.SubscribeExecutionData:input_type -> flow.executiondata.SubscribeExecutionDataRequest
	4,  // 47: flow.executiondata.ExecutionDataAPI.SubscribeExecutionDataFromStartBlockID:input_type -> flow.executiondata.SubscribeExecutionDataFromStartBlockIDRequest
	5,  // 48: flow.executiondata.ExecutionDataAPI.SubscribeExecutionDataFromStartBlockHeight:input_type -> flow.executiondata.SubscribeExecutionDataFromStartBlockHeightRequest
	6,  // 49: flow.executiondata.ExecutionDataAPI.SubscribeExecutionDataFromLatest:input_type -> flow.executiondata.SubscribeExecutionDataFromLatestRequest
	7,  // 50: flow.executiondata.ExecutionDataAPI.SubscribeEvents:input_type -> flow.executiondata.SubscribeEventsRequest
	8,  // 51: flow.executiondata.ExecutionDataAPI.SubscribeEventsFromStartBlockID:input_type -> flow.executiondata.SubscribeEventsFromStartBlockIDRequest
	9,  // 52: flow.executiondata.ExecutionDataAPI.SubscribeEventsFromStartHeight:input_type -> flow.executiondata.SubscribeEventsFromStartHeightRequest
	10, // 53: flow.executiondata.ExecutionDataAPI.SubscribeEventsFromLatest:input_type -> flow.executiondata.SubscribeEventsFromLatestRequest
	13, // 54: flow.executiondata.ExecutionDataAPI.GetRegisterValues:input_type -> flow.executiondata.GetRegisterValuesRequest
	15, // 55: flow.executiondata.ExecutionDataAPI.SubscribeAccountStatusesFromStartBlockID:input_type -> flow.executiondata.SubscribeAccountStatusesFromStartBlockIDRequest
	16, // 56: flow.executiondata.ExecutionDataAPI.SubscribeAccountStatusesFromStartHeight:input_type -> flow.executiondata.SubscribeAccountStatusesFromStartHeightRequest
	17, // 57: flow.executiondata.ExecutionDataAPI.SubscribeAccountStatusesFromLatestBlock:input_type -> flow.executiondata.SubscribeAccountStatusesFromLatestBlockRequest
	1,  // 58: flow.executiondata.ExecutionDataAPI.GetExecutionDataByBlockID:output_type -> flow.executiondata.GetExecutionDataByBlockIDResponse
	3,  // 59: flow.executiondata.ExecutionDataAPI.SubscribeExecutionData:output_type -> flow.executiondata.SubscribeExecutionDataResponse
	3,  // 60: flow.executiondata.ExecutionDataAPI.SubscribeExecutionDataFromStartBlockID:output_type -> flow.executiondata.SubscribeExecutionDataResponse
	3,  // 61: flow.executiondata.ExecutionDataAPI.SubscribeExecutionDataFromStartBlockHeight:output_type -> flow.executiondata.SubscribeExecutionDataResponse
	3,  // 62: flow.executiondata.ExecutionDataAPI.SubscribeExecutionDataFromLatest:output_type -> flow.executiondata.SubscribeExecutionDataResponse
	11, // 63: flow.executiondata.ExecutionDataAPI.SubscribeEvents:output_type -> flow.executiondata.SubscribeEventsResponse
	11, // 64: flow.executiondata.ExecutionDataAPI.SubscribeEventsFromStartBlockID:output_type -> flow.executiondata.SubscribeEventsResponse
	11, // 65: flow.executiondata.ExecutionDataAPI.SubscribeEventsFromStartHeight:output_type -> flow.executiondata.SubscribeEventsResponse
	11, // 66: flow.executiondata.ExecutionDataAPI.SubscribeEventsFromLatest:output_type -> flow.executiondata.SubscribeEventsResponse
	14, // 67: flow.executiondata.ExecutionDataAPI.GetRegisterValues:output_type -> flow.executiondata.GetRegisterValuesResponse
	18, // 68: flow.executiondata.ExecutionDataAPI.SubscribeAccountStatusesFromStartBlockID:output_type -> flow.executiondata.SubscribeAccountStatusesResponse
	18, // 69: flow.executiondata.ExecutionDataAPI.SubscribeAccountStatusesFromStartHeight:output_type -> flow.executiondata.SubscribeAccountStatusesResponse
	18, // 70: flow.executiondata.ExecutionDataAPI.SubscribeAccountStatusesFromLatestBlock:output_type -> flow.executiondata.SubscribeAccountStatusesResponse
	58, // [58:71] is the sub-list for method output_type
	45, // [45:58] is the sub-list for method input_type
	45, // [45:45] is the sub-list for extension type_name
	45, // [45:45] is the sub-list for extension extendee
	0,  // [0:45] is the sub-list for field type_name
}

func init() { file_flow_executiondata_executiondata_proto_init() }
func file_flow_executiondata_executiondata_proto_init() {
	if File_flow_executiondata_executiondata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flow_executiondata_executiondata_proto_rawDesc), len(file_flow_executiondata_executiondata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_flow_executiondata_executiondata_proto_goTypes,
		DependencyIndexes: file_flow_executiondata_executiondata_proto_depIdxs,
		MessageInfos:      file_flow_executiondata_executiondata_proto_msgTypes,
	}.Build()
	File_flow_executiondata_executiondata_proto = out.File
	file_flow_executiondata_executiondata_proto_goTypes = nil
	file_flow_executiondata_executiondata_proto_depIdxs = nil
}
