// Code generated by protoc-gen-go. DO NOT EDIT.
// source: flow/entities/block_execution_data.proto

package entities

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BlockExecutionData struct {
	BlockId              []byte                `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	ChunkExecutionData   []*ChunkExecutionData `protobuf:"bytes,2,rep,name=chunk_execution_data,json=chunkExecutionData,proto3" json:"chunk_execution_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *BlockExecutionData) Reset()         { *m = BlockExecutionData{} }
func (m *BlockExecutionData) String() string { return proto.CompactTextString(m) }
func (*BlockExecutionData) ProtoMessage()    {}
func (*BlockExecutionData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0dbfd6581e1d1c72, []int{0}
}

func (m *BlockExecutionData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockExecutionData.Unmarshal(m, b)
}
func (m *BlockExecutionData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockExecutionData.Marshal(b, m, deterministic)
}
func (m *BlockExecutionData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockExecutionData.Merge(m, src)
}
func (m *BlockExecutionData) XXX_Size() int {
	return xxx_messageInfo_BlockExecutionData.Size(m)
}
func (m *BlockExecutionData) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockExecutionData.DiscardUnknown(m)
}

var xxx_messageInfo_BlockExecutionData proto.InternalMessageInfo

func (m *BlockExecutionData) GetBlockId() []byte {
	if m != nil {
		return m.BlockId
	}
	return nil
}

func (m *BlockExecutionData) GetChunkExecutionData() []*ChunkExecutionData {
	if m != nil {
		return m.ChunkExecutionData
	}
	return nil
}

type ChunkExecutionData struct {
	Collection           *Collection   `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Events               []*Event      `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	TrieUpdates          []*TrieUpdate `protobuf:"bytes,4,rep,name=trieUpdates,proto3" json:"trieUpdates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ChunkExecutionData) Reset()         { *m = ChunkExecutionData{} }
func (m *ChunkExecutionData) String() string { return proto.CompactTextString(m) }
func (*ChunkExecutionData) ProtoMessage()    {}
func (*ChunkExecutionData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0dbfd6581e1d1c72, []int{1}
}

func (m *ChunkExecutionData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChunkExecutionData.Unmarshal(m, b)
}
func (m *ChunkExecutionData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChunkExecutionData.Marshal(b, m, deterministic)
}
func (m *ChunkExecutionData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChunkExecutionData.Merge(m, src)
}
func (m *ChunkExecutionData) XXX_Size() int {
	return xxx_messageInfo_ChunkExecutionData.Size(m)
}
func (m *ChunkExecutionData) XXX_DiscardUnknown() {
	xxx_messageInfo_ChunkExecutionData.DiscardUnknown(m)
}

var xxx_messageInfo_ChunkExecutionData proto.InternalMessageInfo

func (m *ChunkExecutionData) GetCollection() *Collection {
	if m != nil {
		return m.Collection
	}
	return nil
}

func (m *ChunkExecutionData) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *ChunkExecutionData) GetTrieUpdates() []*TrieUpdate {
	if m != nil {
		return m.TrieUpdates
	}
	return nil
}

type TrieUpdate struct {
	RootHash             []byte     `protobuf:"bytes,1,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	Paths                [][]byte   `protobuf:"bytes,2,rep,name=paths,proto3" json:"paths,omitempty"`
	Payloads             []*Payload `protobuf:"bytes,3,rep,name=payloads,proto3" json:"payloads,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TrieUpdate) Reset()         { *m = TrieUpdate{} }
func (m *TrieUpdate) String() string { return proto.CompactTextString(m) }
func (*TrieUpdate) ProtoMessage()    {}
func (*TrieUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_0dbfd6581e1d1c72, []int{2}
}

func (m *TrieUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrieUpdate.Unmarshal(m, b)
}
func (m *TrieUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrieUpdate.Marshal(b, m, deterministic)
}
func (m *TrieUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrieUpdate.Merge(m, src)
}
func (m *TrieUpdate) XXX_Size() int {
	return xxx_messageInfo_TrieUpdate.Size(m)
}
func (m *TrieUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_TrieUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_TrieUpdate proto.InternalMessageInfo

func (m *TrieUpdate) GetRootHash() []byte {
	if m != nil {
		return m.RootHash
	}
	return nil
}

func (m *TrieUpdate) GetPaths() [][]byte {
	if m != nil {
		return m.Paths
	}
	return nil
}

func (m *TrieUpdate) GetPayloads() []*Payload {
	if m != nil {
		return m.Payloads
	}
	return nil
}

type Payload struct {
	EncKey               []byte   `protobuf:"bytes,1,opt,name=enc_key,json=encKey,proto3" json:"enc_key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_0dbfd6581e1d1c72, []int{3}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetEncKey() []byte {
	if m != nil {
		return m.EncKey
	}
	return nil
}

func (m *Payload) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*BlockExecutionData)(nil), "flow.entities.BlockExecutionData")
	proto.RegisterType((*ChunkExecutionData)(nil), "flow.entities.ChunkExecutionData")
	proto.RegisterType((*TrieUpdate)(nil), "flow.entities.TrieUpdate")
	proto.RegisterType((*Payload)(nil), "flow.entities.Payload")
}

func init() {
	proto.RegisterFile("flow/entities/block_execution_data.proto", fileDescriptor_0dbfd6581e1d1c72)
}

var fileDescriptor_0dbfd6581e1d1c72 = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0x41, 0x4f, 0xf2, 0x40,
	0x10, 0x86, 0x53, 0xf8, 0x3e, 0xc0, 0x01, 0x2f, 0x1b, 0xa2, 0x05, 0x8d, 0xc1, 0x9e, 0x38, 0x98,
	0xd6, 0xe0, 0x45, 0xe3, 0x0d, 0x25, 0xd1, 0x78, 0x21, 0x55, 0x2f, 0x5e, 0x9a, 0xed, 0x76, 0xa0,
	0x0d, 0xb5, 0xdb, 0xb4, 0x5b, 0x94, 0xbb, 0xbf, 0xca, 0x5f, 0x67, 0xba, 0x5b, 0x0a, 0x2d, 0x97,
	0x26, 0x33, 0xef, 0x33, 0x7d, 0x66, 0x37, 0x0b, 0xe3, 0x45, 0xc8, 0xbf, 0x2c, 0x8c, 0x44, 0x20,
	0x02, 0x4c, 0x2d, 0x37, 0xe4, 0x6c, 0xe5, 0xe0, 0x37, 0xb2, 0x4c, 0x04, 0x3c, 0x72, 0x3c, 0x2a,
	0xa8, 0x19, 0x27, 0x5c, 0x70, 0x72, 0x9c, 0x93, 0xe6, 0x96, 0x1c, 0x5e, 0x54, 0x07, 0x19, 0x0f,
	0x43, 0x64, 0xf9, 0x8c, 0xc2, 0x87, 0x83, 0x6a, 0x8e, 0x6b, 0x8c, 0x84, 0x8a, 0x8c, 0x1f, 0x0d,
	0xc8, 0x34, 0x17, 0xcd, 0xb6, 0x9e, 0x47, 0x2a, 0x28, 0x19, 0x40, 0x47, 0xe9, 0x03, 0x4f, 0xd7,
	0x46, 0xda, 0xb8, 0x67, 0xb7, 0x65, 0xfd, 0xec, 0x91, 0x57, 0xe8, 0x33, 0x3f, 0x8b, 0xea, 0x9b,
	0xe9, 0x8d, 0x51, 0x73, 0xdc, 0x9d, 0x5c, 0x9a, 0x95, 0xd5, 0xcc, 0x87, 0x1c, 0xad, 0xfc, 0xdb,
	0x26, 0xec, 0xa0, 0x67, 0xfc, 0x6a, 0x40, 0x0e, 0x51, 0x72, 0x07, 0xb0, 0x3b, 0x8c, 0x5c, 0xa4,
	0x3b, 0x19, 0xd4, 0x0d, 0x25, 0x60, 0xef, 0xc1, 0xe4, 0x0a, 0x5a, 0xf2, 0x9c, 0x69, 0xb1, 0x58,
	0xbf, 0x36, 0x36, 0xcb, 0x43, 0xbb, 0x60, 0xc8, 0x3d, 0x74, 0x45, 0x12, 0xe0, 0x7b, 0xec, 0x51,
	0x81, 0xa9, 0xfe, 0x4f, 0x8e, 0xd4, 0x4d, 0x6f, 0x25, 0x61, 0xef, 0xd3, 0x46, 0x0a, 0xb0, 0x8b,
	0xc8, 0x19, 0x1c, 0x25, 0x9c, 0x0b, 0xc7, 0xa7, 0xa9, 0x5f, 0xdc, 0x5d, 0x27, 0x6f, 0x3c, 0xd1,
	0xd4, 0x27, 0x7d, 0xf8, 0x1f, 0x53, 0xe1, 0xab, 0xa5, 0x7a, 0xb6, 0x2a, 0xc8, 0x04, 0x3a, 0x31,
	0xdd, 0x84, 0x9c, 0x7a, 0xa9, 0xde, 0x94, 0xea, 0x93, 0x9a, 0x7a, 0xae, 0x62, 0xbb, 0xe4, 0x8c,
	0x5b, 0x68, 0x17, 0x4d, 0x72, 0x0a, 0x6d, 0x8c, 0x98, 0xb3, 0xc2, 0x4d, 0xe1, 0x6b, 0x61, 0xc4,
	0x5e, 0x70, 0x93, 0xdb, 0xd6, 0x34, 0xcc, 0x50, 0x6f, 0xc8, 0xb6, 0x2a, 0xa6, 0x73, 0x38, 0xe7,
	0xc9, 0xd2, 0xe4, 0x91, 0x54, 0xc8, 0x67, 0xe0, 0x66, 0x8b, 0xd2, 0xf5, 0x71, 0xbd, 0x0c, 0x84,
	0x9f, 0xb9, 0x26, 0xe3, 0x9f, 0x96, 0x82, 0x2c, 0xf9, 0xd9, 0x92, 0xd6, 0x92, 0x5b, 0x95, 0x07,
	0xe5, 0xb6, 0x64, 0x74, 0xf3, 0x17, 0x00, 0x00, 0xff, 0xff, 0x4a, 0x02, 0xd9, 0x20, 0xc1, 0x02,
	0x00, 0x00,
}
