// Code generated by protoc-gen-go. DO NOT EDIT.
// source: flow/entities/block_seal.proto

package entities

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BlockSeal struct {
	BlockId                    []byte   `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	ExecutionReceiptId         []byte   `protobuf:"bytes,2,opt,name=execution_receipt_id,json=executionReceiptId,proto3" json:"execution_receipt_id,omitempty"`
	ExecutionReceiptSignatures [][]byte `protobuf:"bytes,3,rep,name=execution_receipt_signatures,json=executionReceiptSignatures,proto3" json:"execution_receipt_signatures,omitempty"`
	ResultApprovalSignatures   [][]byte `protobuf:"bytes,4,rep,name=result_approval_signatures,json=resultApprovalSignatures,proto3" json:"result_approval_signatures,omitempty"`
	XXX_NoUnkeyedLiteral       struct{} `json:"-"`
	XXX_unrecognized           []byte   `json:"-"`
	XXX_sizecache              int32    `json:"-"`
}

func (m *BlockSeal) Reset()         { *m = BlockSeal{} }
func (m *BlockSeal) String() string { return proto.CompactTextString(m) }
func (*BlockSeal) ProtoMessage()    {}
func (*BlockSeal) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5bc0062689af71f, []int{0}
}

func (m *BlockSeal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockSeal.Unmarshal(m, b)
}
func (m *BlockSeal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockSeal.Marshal(b, m, deterministic)
}
func (m *BlockSeal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockSeal.Merge(m, src)
}
func (m *BlockSeal) XXX_Size() int {
	return xxx_messageInfo_BlockSeal.Size(m)
}
func (m *BlockSeal) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockSeal.DiscardUnknown(m)
}

var xxx_messageInfo_BlockSeal proto.InternalMessageInfo

func (m *BlockSeal) GetBlockId() []byte {
	if m != nil {
		return m.BlockId
	}
	return nil
}

func (m *BlockSeal) GetExecutionReceiptId() []byte {
	if m != nil {
		return m.ExecutionReceiptId
	}
	return nil
}

func (m *BlockSeal) GetExecutionReceiptSignatures() [][]byte {
	if m != nil {
		return m.ExecutionReceiptSignatures
	}
	return nil
}

func (m *BlockSeal) GetResultApprovalSignatures() [][]byte {
	if m != nil {
		return m.ResultApprovalSignatures
	}
	return nil
}

func init() {
	proto.RegisterType((*BlockSeal)(nil), "flow.entities.BlockSeal")
}

func init() { proto.RegisterFile("flow/entities/block_seal.proto", fileDescriptor_e5bc0062689af71f) }

var fileDescriptor_e5bc0062689af71f = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0xb1, 0xae, 0x82, 0x30,
	0x18, 0x46, 0xc3, 0xe5, 0xe6, 0x5e, 0x6c, 0x70, 0x69, 0x1c, 0x90, 0x18, 0x43, 0x9c, 0x98, 0xc0,
	0xc4, 0xd5, 0x41, 0xd9, 0x58, 0x61, 0x73, 0x21, 0x05, 0x7e, 0x4d, 0x63, 0x43, 0x9b, 0xb6, 0xa8,
	0x8f, 0xea, 0xe3, 0x18, 0x8a, 0xa0, 0xd1, 0xf1, 0xcb, 0x39, 0x67, 0xf8, 0xd0, 0xf2, 0xc8, 0xf8,
	0x35, 0x86, 0x46, 0x53, 0x4d, 0x41, 0xc5, 0x25, 0xe3, 0xd5, 0xb9, 0x50, 0x40, 0x58, 0x24, 0x24,
	0xd7, 0x1c, 0x4f, 0x3b, 0x1e, 0x0d, 0x7c, 0x75, 0xb7, 0xd0, 0x24, 0xe9, 0x9c, 0x1c, 0x08, 0xc3,
	0x73, 0xe4, 0xf4, 0x01, 0xad, 0x3d, 0x2b, 0xb0, 0x42, 0x37, 0xfb, 0x37, 0x3b, 0xad, 0xf1, 0x1a,
	0xcd, 0xe0, 0x06, 0x55, 0xab, 0x29, 0x6f, 0x0a, 0x09, 0x15, 0x50, 0xa1, 0x3b, 0xed, 0xc7, 0x68,
	0x78, 0x64, 0x59, 0x8f, 0xd2, 0x1a, 0xef, 0xd0, 0xe2, 0xbb, 0x50, 0xf4, 0xd4, 0x10, 0xdd, 0x4a,
	0x50, 0x9e, 0x1d, 0xd8, 0xa1, 0x9b, 0xf9, 0x9f, 0x65, 0x3e, 0x1a, 0x78, 0x8b, 0x7c, 0x09, 0xaa,
	0x65, 0xba, 0x20, 0x42, 0x48, 0x7e, 0x21, 0xec, 0xbd, 0xff, 0x35, 0xbd, 0xd7, 0x1b, 0xfb, 0xa7,
	0xf0, 0xaa, 0x13, 0x74, 0x70, 0x86, 0x9b, 0xe5, 0x9f, 0x39, 0xbf, 0x79, 0x04, 0x00, 0x00, 0xff,
	0xff, 0xda, 0xcb, 0x2a, 0xdb, 0x1e, 0x01, 0x00, 0x00,
}
