// Code generated by protoc-gen-go. DO NOT EDIT.
// source: flow/entities/collection.proto

package entities

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Collection struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TransactionIds       [][]byte `protobuf:"bytes,2,rep,name=transaction_ids,json=transactionIds,proto3" json:"transaction_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Collection) Reset()         { *m = Collection{} }
func (m *Collection) String() string { return proto.CompactTextString(m) }
func (*Collection) ProtoMessage()    {}
func (*Collection) Descriptor() ([]byte, []int) {
	return fileDescriptor_b302551359ed99bf, []int{0}
}

func (m *Collection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Collection.Unmarshal(m, b)
}
func (m *Collection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Collection.Marshal(b, m, deterministic)
}
func (m *Collection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Collection.Merge(m, src)
}
func (m *Collection) XXX_Size() int {
	return xxx_messageInfo_Collection.Size(m)
}
func (m *Collection) XXX_DiscardUnknown() {
	xxx_messageInfo_Collection.DiscardUnknown(m)
}

var xxx_messageInfo_Collection proto.InternalMessageInfo

func (m *Collection) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Collection) GetTransactionIds() [][]byte {
	if m != nil {
		return m.TransactionIds
	}
	return nil
}

type CollectionGuarantee struct {
	CollectionId         []byte   `protobuf:"bytes,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	Signatures           [][]byte `protobuf:"bytes,2,rep,name=signatures,proto3" json:"signatures,omitempty"`
	ReferenceBlockId     []byte   `protobuf:"bytes,3,opt,name=reference_block_id,json=referenceBlockId,proto3" json:"reference_block_id,omitempty"`
	Signature            []byte   `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	SignerIds            [][]byte `protobuf:"bytes,5,rep,name=signer_ids,json=signerIds,proto3" json:"signer_ids,omitempty"`
	SignerIndices        []byte   `protobuf:"bytes,6,opt,name=signer_indices,json=signerIndices,proto3" json:"signer_indices,omitempty"`
	ClusterChainId       []byte   `protobuf:"bytes,7,opt,name=cluster_chain_id,json=clusterChainId,proto3" json:"cluster_chain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollectionGuarantee) Reset()         { *m = CollectionGuarantee{} }
func (m *CollectionGuarantee) String() string { return proto.CompactTextString(m) }
func (*CollectionGuarantee) ProtoMessage()    {}
func (*CollectionGuarantee) Descriptor() ([]byte, []int) {
	return fileDescriptor_b302551359ed99bf, []int{1}
}

func (m *CollectionGuarantee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectionGuarantee.Unmarshal(m, b)
}
func (m *CollectionGuarantee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectionGuarantee.Marshal(b, m, deterministic)
}
func (m *CollectionGuarantee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectionGuarantee.Merge(m, src)
}
func (m *CollectionGuarantee) XXX_Size() int {
	return xxx_messageInfo_CollectionGuarantee.Size(m)
}
func (m *CollectionGuarantee) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectionGuarantee.DiscardUnknown(m)
}

var xxx_messageInfo_CollectionGuarantee proto.InternalMessageInfo

func (m *CollectionGuarantee) GetCollectionId() []byte {
	if m != nil {
		return m.CollectionId
	}
	return nil
}

func (m *CollectionGuarantee) GetSignatures() [][]byte {
	if m != nil {
		return m.Signatures
	}
	return nil
}

func (m *CollectionGuarantee) GetReferenceBlockId() []byte {
	if m != nil {
		return m.ReferenceBlockId
	}
	return nil
}

func (m *CollectionGuarantee) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *CollectionGuarantee) GetSignerIds() [][]byte {
	if m != nil {
		return m.SignerIds
	}
	return nil
}

func (m *CollectionGuarantee) GetSignerIndices() []byte {
	if m != nil {
		return m.SignerIndices
	}
	return nil
}

func (m *CollectionGuarantee) GetClusterChainId() []byte {
	if m != nil {
		return m.ClusterChainId
	}
	return nil
}

func init() {
	proto.RegisterType((*Collection)(nil), "flow.entities.Collection")
	proto.RegisterType((*CollectionGuarantee)(nil), "flow.entities.CollectionGuarantee")
}

func init() { proto.RegisterFile("flow/entities/collection.proto", fileDescriptor_b302551359ed99bf) }

var fileDescriptor_b302551359ed99bf = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xc1, 0x4e, 0xeb, 0x30,
	0x10, 0x45, 0xd5, 0xf4, 0xbd, 0xa2, 0x8e, 0xda, 0x50, 0x99, 0x4d, 0x16, 0xa5, 0xaa, 0x8a, 0x10,
	0x5d, 0xa0, 0x18, 0x89, 0x3f, 0x68, 0x85, 0x50, 0x76, 0xa8, 0x4b, 0x36, 0x91, 0x63, 0x4f, 0x53,
	0x8b, 0x60, 0x23, 0xdb, 0x11, 0x7f, 0xc2, 0xf7, 0xa2, 0x4c, 0x9a, 0xa4, 0x6c, 0xb2, 0x38, 0xe7,
	0xe6, 0x8e, 0xed, 0x81, 0xd5, 0xb1, 0xb2, 0xdf, 0x1c, 0x4d, 0xd0, 0x41, 0xa3, 0xe7, 0xd2, 0x56,
	0x15, 0xca, 0xa0, 0xad, 0x49, 0xbf, 0x9c, 0x0d, 0x96, 0xcd, 0x1b, 0x9f, 0x76, 0x7e, 0xf3, 0x02,
	0xb0, 0xef, 0x23, 0x2c, 0x86, 0x48, 0xab, 0x64, 0xb4, 0x1e, 0x6d, 0x67, 0x87, 0x48, 0x2b, 0xf6,
	0x00, 0xd7, 0xc1, 0x09, 0xe3, 0x05, 0xe9, 0x5c, 0x2b, 0x9f, 0x44, 0xeb, 0xf1, 0x76, 0x76, 0x88,
	0x2f, 0x70, 0xa6, 0xfc, 0xe6, 0x27, 0x82, 0x9b, 0xa1, 0xe7, 0xb5, 0x16, 0x4e, 0x98, 0x80, 0xc8,
	0xee, 0x60, 0x3e, 0x9c, 0x20, 0xef, 0xbb, 0x67, 0x03, 0xcc, 0x14, 0x5b, 0x01, 0x78, 0x5d, 0x1a,
	0x11, 0x6a, 0x87, 0xdd, 0x80, 0x0b, 0xc2, 0x1e, 0x81, 0x39, 0x3c, 0xa2, 0x43, 0x23, 0x31, 0x2f,
	0x2a, 0x2b, 0x3f, 0x9a, 0xa6, 0x31, 0x35, 0x2d, 0x7a, 0xb3, 0x6b, 0x44, 0xa6, 0xd8, 0x12, 0xa6,
	0xfd, 0xbf, 0xc9, 0x3f, 0x0a, 0x0d, 0x80, 0xdd, 0xb6, 0xb3, 0xd0, 0xd1, 0x65, 0xfe, 0xd3, 0xac,
	0x69, 0x4b, 0x32, 0xe5, 0xd9, 0x3d, 0xc4, 0x9d, 0x36, 0x4a, 0x4b, 0xf4, 0xc9, 0x84, 0x1a, 0xe6,
	0xe7, 0x48, 0x0b, 0xd9, 0x16, 0x16, 0xb2, 0xaa, 0x7d, 0x40, 0x97, 0xcb, 0x93, 0xd0, 0x74, 0xb3,
	0x2b, 0x0a, 0xc6, 0x67, 0xbe, 0x6f, 0x70, 0xa6, 0x76, 0x6f, 0xb0, 0xb4, 0xae, 0x4c, 0xad, 0xa1,
	0x67, 0xa7, 0x15, 0x14, 0xf5, 0xb1, 0x7f, 0xff, 0xf7, 0xa7, 0x52, 0x87, 0x53, 0x5d, 0xa4, 0xd2,
	0x7e, 0xf2, 0x36, 0xc4, 0xe9, 0xd3, 0x25, 0x79, 0x69, 0xf9, 0x9f, 0x8d, 0x16, 0x13, 0x52, 0xcf,
	0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x69, 0xd9, 0xb3, 0x36, 0xe9, 0x01, 0x00, 0x00,
}
