// Code generated by protoc-gen-go. DO NOT EDIT.
// source: flow/entities/event.proto

package entities

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	TransactionId        []byte   `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	TransactionIndex     uint32   `protobuf:"varint,3,opt,name=transaction_index,json=transactionIndex,proto3" json:"transaction_index,omitempty"`
	EventIndex           uint32   `protobuf:"varint,4,opt,name=event_index,json=eventIndex,proto3" json:"event_index,omitempty"`
	Payload              []byte   `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcb08ee6f360364f, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Event) GetTransactionId() []byte {
	if m != nil {
		return m.TransactionId
	}
	return nil
}

func (m *Event) GetTransactionIndex() uint32 {
	if m != nil {
		return m.TransactionIndex
	}
	return 0
}

func (m *Event) GetEventIndex() uint32 {
	if m != nil {
		return m.EventIndex
	}
	return 0
}

func (m *Event) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type BlockEvents struct {
	BlockId              []byte   `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	BlockHeight          uint64   `protobuf:"varint,2,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	Events               []*Event `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockEvents) Reset()         { *m = BlockEvents{} }
func (m *BlockEvents) String() string { return proto.CompactTextString(m) }
func (*BlockEvents) ProtoMessage()    {}
func (*BlockEvents) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcb08ee6f360364f, []int{1}
}

func (m *BlockEvents) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockEvents.Unmarshal(m, b)
}
func (m *BlockEvents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockEvents.Marshal(b, m, deterministic)
}
func (m *BlockEvents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockEvents.Merge(m, src)
}
func (m *BlockEvents) XXX_Size() int {
	return xxx_messageInfo_BlockEvents.Size(m)
}
func (m *BlockEvents) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockEvents.DiscardUnknown(m)
}

var xxx_messageInfo_BlockEvents proto.InternalMessageInfo

func (m *BlockEvents) GetBlockId() []byte {
	if m != nil {
		return m.BlockId
	}
	return nil
}

func (m *BlockEvents) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *BlockEvents) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func init() {
	proto.RegisterType((*Event)(nil), "entities.Event")
	proto.RegisterType((*BlockEvents)(nil), "entities.BlockEvents")
}

func init() { proto.RegisterFile("flow/entities/event.proto", fileDescriptor_dcb08ee6f360364f) }

var fileDescriptor_dcb08ee6f360364f = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xdd, 0x4a, 0x03, 0x31,
	0x10, 0x85, 0x89, 0xbb, 0xad, 0x75, 0xb6, 0xf5, 0x67, 0xae, 0xd2, 0x2b, 0xd7, 0x82, 0x18, 0x10,
	0xb6, 0xa0, 0x6f, 0x20, 0x08, 0xf6, 0x36, 0x2f, 0x20, 0x69, 0x13, 0x6d, 0x70, 0x49, 0x96, 0x66,
	0x50, 0xfb, 0x4a, 0x3e, 0xa5, 0x64, 0xb6, 0x0b, 0xed, 0x5d, 0xe6, 0x3b, 0x1f, 0x99, 0xc3, 0xc0,
	0xfc, 0xa3, 0x8d, 0x3f, 0x4b, 0x17, 0xc8, 0x93, 0x77, 0x69, 0xe9, 0xbe, 0x5d, 0xa0, 0xa6, 0xdb,
	0x45, 0x8a, 0x38, 0x19, 0xe8, 0xe2, 0x4f, 0xc0, 0xe8, 0x35, 0x27, 0x88, 0x50, 0xd2, 0xbe, 0x73,
	0x52, 0xd4, 0x42, 0x5d, 0x68, 0x7e, 0xe3, 0x3d, 0x5c, 0xd2, 0xce, 0x84, 0x64, 0x36, 0xe4, 0x63,
	0x78, 0xf7, 0x56, 0x9e, 0xd5, 0x42, 0x4d, 0xf5, 0xec, 0x88, 0xae, 0x2c, 0x3e, 0xc2, 0xcd, 0x89,
	0x16, 0xac, 0xfb, 0x95, 0x45, 0x2d, 0xd4, 0x4c, 0x5f, 0x1f, 0x9b, 0x99, 0xe3, 0x2d, 0x54, 0x5c,
	0xe5, 0xa0, 0x95, 0xac, 0x01, 0xa3, 0x5e, 0x90, 0x70, 0xde, 0x99, 0x7d, 0x1b, 0x8d, 0x95, 0x23,
	0xde, 0x36, 0x8c, 0x0b, 0x82, 0xea, 0xa5, 0x8d, 0x9b, 0x2f, 0x2e, 0x9c, 0x70, 0x0e, 0x93, 0x75,
	0x1e, 0x73, 0x2f, 0xd1, 0x9b, 0x3c, 0xaf, 0x2c, 0xde, 0xc1, 0xb4, 0x8f, 0xb6, 0xce, 0x7f, 0x6e,
	0x89, 0x6b, 0x97, 0xba, 0x62, 0xf6, 0xc6, 0x08, 0x1f, 0x60, 0xcc, 0x4b, 0x93, 0x2c, 0xea, 0x42,
	0x55, 0x4f, 0x57, 0xcd, 0x70, 0x94, 0x86, 0xff, 0xd7, 0x87, 0x78, 0x3d, 0xe6, 0x9b, 0x3d, 0xff,
	0x07, 0x00, 0x00, 0xff, 0xff, 0x30, 0x24, 0x98, 0x73, 0x50, 0x01, 0x00, 0x00,
}
