// Code generated by protoc-gen-go. DO NOT EDIT.
// source: flow/entities/metadata.proto

package entities

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ExecutorMetadata contains data about the execution result used to serve the
// request.
type ExecutorMetadata struct {
	// ID of the ExecutionResult used to serve the request
	ExecutionResultId []byte `protobuf:"bytes,1,opt,name=execution_result_id,json=executionResultId,proto3" json:"execution_result_id,omitempty"`
	// Node IDs of Execution nodes that produced the result
	ExecutorId           [][]byte `protobuf:"bytes,2,rep,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecutorMetadata) Reset()         { *m = ExecutorMetadata{} }
func (m *ExecutorMetadata) String() string { return proto.CompactTextString(m) }
func (*ExecutorMetadata) ProtoMessage()    {}
func (*ExecutorMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6b3c67afa624bc0, []int{0}
}

func (m *ExecutorMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecutorMetadata.Unmarshal(m, b)
}
func (m *ExecutorMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecutorMetadata.Marshal(b, m, deterministic)
}
func (m *ExecutorMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecutorMetadata.Merge(m, src)
}
func (m *ExecutorMetadata) XXX_Size() int {
	return xxx_messageInfo_ExecutorMetadata.Size(m)
}
func (m *ExecutorMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecutorMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ExecutorMetadata proto.InternalMessageInfo

func (m *ExecutorMetadata) GetExecutionResultId() []byte {
	if m != nil {
		return m.ExecutionResultId
	}
	return nil
}

func (m *ExecutorMetadata) GetExecutorId() [][]byte {
	if m != nil {
		return m.ExecutorId
	}
	return nil
}

// Metadata contains data about the node's state at the time of the request.
type Metadata struct {
	// Block ID of the latest finalized block
	LatestFinalizedBlockId []byte `protobuf:"bytes,1,opt,name=latest_finalized_block_id,json=latestFinalizedBlockId,proto3" json:"latest_finalized_block_id,omitempty"`
	// Height of the latest finalized block
	LatestFinalizedHeight uint64 `protobuf:"varint,2,opt,name=latest_finalized_height,json=latestFinalizedHeight,proto3" json:"latest_finalized_height,omitempty"`
	// Node's unique ID
	NodeId []byte `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Height of the latest block who's execution state data is fully indexed
	HighestIndexedHeight uint64 `protobuf:"varint,4,opt,name=highest_indexed_height,json=highestIndexedHeight,proto3" json:"highest_indexed_height,omitempty"`
	// Metadata about the execution result used to serve the request.
	ExecutionStateQuery  *ExecutorMetadata `protobuf:"bytes,5,opt,name=execution_state_query,json=executionStateQuery,proto3" json:"execution_state_query,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6b3c67afa624bc0, []int{1}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetLatestFinalizedBlockId() []byte {
	if m != nil {
		return m.LatestFinalizedBlockId
	}
	return nil
}

func (m *Metadata) GetLatestFinalizedHeight() uint64 {
	if m != nil {
		return m.LatestFinalizedHeight
	}
	return 0
}

func (m *Metadata) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *Metadata) GetHighestIndexedHeight() uint64 {
	if m != nil {
		return m.HighestIndexedHeight
	}
	return 0
}

func (m *Metadata) GetExecutionStateQuery() *ExecutorMetadata {
	if m != nil {
		return m.ExecutionStateQuery
	}
	return nil
}

func init() {
	proto.RegisterType((*ExecutorMetadata)(nil), "flow.entities.ExecutorMetadata")
	proto.RegisterType((*Metadata)(nil), "flow.entities.Metadata")
}

func init() { proto.RegisterFile("flow/entities/metadata.proto", fileDescriptor_f6b3c67afa624bc0) }

var fileDescriptor_f6b3c67afa624bc0 = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x4d, 0x4b, 0xf3, 0x40,
	0x14, 0x85, 0x49, 0xdb, 0xb7, 0xaf, 0xdc, 0x56, 0xd0, 0x68, 0x3f, 0x84, 0x42, 0x43, 0x57, 0x59,
	0x4d, 0x44, 0x45, 0x70, 0x5b, 0x50, 0xcc, 0x42, 0xd0, 0x74, 0xe7, 0x26, 0x24, 0x99, 0xdb, 0x64,
	0x30, 0xcd, 0x68, 0x72, 0x83, 0xd5, 0x7f, 0xe3, 0x3f, 0x95, 0x99, 0xe6, 0x83, 0xd6, 0xcd, 0xc0,
	0xdc, 0xe7, 0x9c, 0x73, 0xe1, 0x5c, 0x98, 0xad, 0x53, 0xf9, 0xe9, 0x60, 0x46, 0x82, 0x04, 0x16,
	0xce, 0x06, 0x29, 0xe0, 0x01, 0x05, 0xec, 0x3d, 0x97, 0x24, 0xcd, 0x63, 0x45, 0x59, 0x4d, 0x17,
	0x11, 0x9c, 0xdc, 0x6f, 0x31, 0x2a, 0x49, 0xe6, 0x4f, 0x95, 0xd0, 0x64, 0x70, 0x86, 0x7a, 0x26,
	0x64, 0xe6, 0xe7, 0x58, 0x94, 0x29, 0xf9, 0x82, 0x4f, 0x0d, 0xcb, 0xb0, 0x87, 0xde, 0x69, 0x83,
	0x3c, 0x4d, 0x5c, 0x6e, 0xce, 0x61, 0x80, 0x55, 0x86, 0xd2, 0x75, 0xac, 0xae, 0x3d, 0xf4, 0xa0,
	0x1e, 0xb9, 0x7c, 0xf1, 0xd3, 0x81, 0xa3, 0x26, 0xfd, 0x0e, 0x2e, 0xd2, 0x80, 0xb0, 0x20, 0x7f,
	0x2d, 0xb2, 0x20, 0x15, 0xdf, 0xc8, 0xfd, 0x30, 0x95, 0xd1, 0x5b, 0xbb, 0x63, 0xbc, 0x13, 0x3c,
	0xd4, 0x7c, 0xa9, 0xb0, 0xcb, 0xcd, 0x5b, 0x98, 0xfc, 0xb1, 0x26, 0x28, 0xe2, 0x84, 0xa6, 0x1d,
	0xcb, 0xb0, 0x7b, 0xde, 0xe8, 0xc0, 0xf8, 0xa8, 0xa1, 0x39, 0x81, 0xff, 0x99, 0xe4, 0xa8, 0x16,
	0x74, 0xf5, 0x82, 0xbe, 0xfa, 0xba, 0xdc, 0xbc, 0x81, 0x71, 0x22, 0xe2, 0x44, 0x25, 0x8a, 0x8c,
	0xe3, 0xb6, 0xcd, 0xeb, 0xe9, 0xbc, 0xf3, 0x8a, 0xba, 0x3b, 0x58, 0xc5, 0xad, 0x60, 0xd4, 0xf6,
	0x53, 0x50, 0x40, 0xe8, 0x7f, 0x94, 0x98, 0x7f, 0x4d, 0xff, 0x59, 0x86, 0x3d, 0xb8, 0x9a, 0xb3,
	0xbd, 0x8a, 0xd9, 0x61, 0xbf, 0x5e, 0xdb, 0xee, 0x4a, 0x99, 0x5f, 0x94, 0x77, 0xf9, 0x0c, 0x33,
	0x99, 0xc7, 0x4c, 0x66, 0xda, 0xac, 0x6f, 0x15, 0x96, 0xeb, 0x26, 0xe5, 0xf5, 0x32, 0x16, 0x94,
	0x94, 0x21, 0x8b, 0xe4, 0xc6, 0xd9, 0x89, 0x1c, 0xfd, 0xd4, 0x4a, 0x27, 0x96, 0xce, 0xde, 0xe1,
	0xc3, 0xbe, 0x46, 0xd7, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc1, 0x67, 0xef, 0xf8, 0x10, 0x02,
	0x00, 0x00,
}
