// Code generated by protoc-gen-go. DO NOT EDIT.
// source: flow/entities/node_version_info.proto

package entities

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NodeVersionInfo struct {
	// The currently running node software version.
	Semver string `protobuf:"bytes,1,opt,name=semver,proto3" json:"semver,omitempty"`
	// The git commit hash of the currently running node software.
	Commit string `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	// The unique identifier for the node's network within the current spork.
	SporkId []byte `protobuf:"bytes,3,opt,name=spork_id,json=sporkId,proto3" json:"spork_id,omitempty"`
	// The protocol version of the currently running node software.
	ProtocolVersion uint64 `protobuf:"varint,4,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// The spork root block height. This is the height of the first sealed block in the spork network.
	SporkRootBlockHeight uint64 `protobuf:"varint,5,opt,name=spork_root_block_height,json=sporkRootBlockHeight,proto3" json:"spork_root_block_height,omitempty"`
	// The node's root block height. This is the first sealed block in the node's protocol database.
	// If the node started at the beginning of the spork, it is the same as the spork root block height.
	// If the node started after the beginning of the spork, it is the height of the first sealed block
	// indexed.
	NodeRootBlockHeight uint64 `protobuf:"varint,6,opt,name=node_root_block_height,json=nodeRootBlockHeight,proto3" json:"node_root_block_height,omitempty"`
	// The first block that the node's version supports.
	StartHeight uint64 `protobuf:"varint,7,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"`
	// The last block the node's version supports.
	EndHeight            uint64   `protobuf:"varint,8,opt,name=end_height,json=endHeight,proto3" json:"end_height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeVersionInfo) Reset()         { *m = NodeVersionInfo{} }
func (m *NodeVersionInfo) String() string { return proto.CompactTextString(m) }
func (*NodeVersionInfo) ProtoMessage()    {}
func (*NodeVersionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff9e447351cb4a8a, []int{0}
}

func (m *NodeVersionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeVersionInfo.Unmarshal(m, b)
}
func (m *NodeVersionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeVersionInfo.Marshal(b, m, deterministic)
}
func (m *NodeVersionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeVersionInfo.Merge(m, src)
}
func (m *NodeVersionInfo) XXX_Size() int {
	return xxx_messageInfo_NodeVersionInfo.Size(m)
}
func (m *NodeVersionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeVersionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NodeVersionInfo proto.InternalMessageInfo

func (m *NodeVersionInfo) GetSemver() string {
	if m != nil {
		return m.Semver
	}
	return ""
}

func (m *NodeVersionInfo) GetCommit() string {
	if m != nil {
		return m.Commit
	}
	return ""
}

func (m *NodeVersionInfo) GetSporkId() []byte {
	if m != nil {
		return m.SporkId
	}
	return nil
}

func (m *NodeVersionInfo) GetProtocolVersion() uint64 {
	if m != nil {
		return m.ProtocolVersion
	}
	return 0
}

func (m *NodeVersionInfo) GetSporkRootBlockHeight() uint64 {
	if m != nil {
		return m.SporkRootBlockHeight
	}
	return 0
}

func (m *NodeVersionInfo) GetNodeRootBlockHeight() uint64 {
	if m != nil {
		return m.NodeRootBlockHeight
	}
	return 0
}

func (m *NodeVersionInfo) GetStartHeight() uint64 {
	if m != nil {
		return m.StartHeight
	}
	return 0
}

func (m *NodeVersionInfo) GetEndHeight() uint64 {
	if m != nil {
		return m.EndHeight
	}
	return 0
}

func init() {
	proto.RegisterType((*NodeVersionInfo)(nil), "flow.entities.NodeVersionInfo")
}

func init() {
	proto.RegisterFile("flow/entities/node_version_info.proto", fileDescriptor_ff9e447351cb4a8a)
}

var fileDescriptor_ff9e447351cb4a8a = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xdf, 0x4a, 0xc3, 0x30,
	0x14, 0xc6, 0xe9, 0x9c, 0xfb, 0x73, 0x9c, 0x4c, 0xa2, 0xcc, 0x0a, 0x0a, 0x53, 0x10, 0xea, 0x4d,
	0x23, 0x0c, 0x5f, 0x60, 0x57, 0xee, 0x46, 0xa4, 0x17, 0x5e, 0x78, 0x53, 0x6c, 0x93, 0xb6, 0x61,
	0x6d, 0xce, 0x48, 0xb3, 0xf9, 0x64, 0xbe, 0x9f, 0xf4, 0xa4, 0x11, 0xd4, 0x9b, 0xc0, 0xf9, 0xbe,
	0xdf, 0x97, 0x93, 0x73, 0x02, 0xf7, 0x45, 0x8d, 0x9f, 0x5c, 0x6a, 0xab, 0xac, 0x92, 0x2d, 0xd7,
	0x28, 0x64, 0x7a, 0x90, 0xa6, 0x55, 0xa8, 0x53, 0xa5, 0x0b, 0x8c, 0x77, 0x06, 0x2d, 0xb2, 0xd3,
	0x0e, 0x8b, 0x3d, 0x76, 0xf7, 0x35, 0x80, 0xf9, 0x0b, 0x0a, 0xf9, 0xe6, 0xc8, 0x8d, 0x2e, 0x90,
	0x2d, 0x60, 0xd4, 0xca, 0xe6, 0x20, 0x4d, 0x18, 0x2c, 0x83, 0x68, 0x9a, 0xf4, 0x55, 0xa7, 0xe7,
	0xd8, 0x34, 0xca, 0x86, 0x03, 0xa7, 0xbb, 0x8a, 0x5d, 0xc1, 0xa4, 0xdd, 0xa1, 0xd9, 0xa6, 0x4a,
	0x84, 0x47, 0xcb, 0x20, 0x9a, 0x25, 0x63, 0xaa, 0x37, 0x82, 0x3d, 0xc0, 0x19, 0xb5, 0xcd, 0xb1,
	0xf6, 0x8f, 0x09, 0x87, 0xcb, 0x20, 0x1a, 0x26, 0x73, 0xaf, 0xf7, 0x9d, 0xd9, 0x13, 0x5c, 0xba,
	0x5b, 0x0c, 0xa2, 0x4d, 0xb3, 0x1a, 0xf3, 0x6d, 0x5a, 0x49, 0x55, 0x56, 0x36, 0x3c, 0xa6, 0xc4,
	0x05, 0xd9, 0x09, 0xa2, 0x5d, 0x77, 0xe6, 0x33, 0x79, 0x6c, 0x05, 0x0b, 0x1a, 0xf5, 0x7f, 0x6a,
	0x44, 0xa9, 0xf3, 0xce, 0xfd, 0x1b, 0xba, 0x85, 0x59, 0x6b, 0x3f, 0x8c, 0xf5, 0xe8, 0x98, 0xd0,
	0x13, 0xd2, 0x7a, 0xe4, 0x06, 0x40, 0x6a, 0xe1, 0x81, 0x09, 0x01, 0x53, 0xa9, 0x85, 0xb3, 0xd7,
	0xaf, 0x70, 0x8d, 0xa6, 0x8c, 0x51, 0xd3, 0x3a, 0x69, 0x96, 0x6c, 0x5f, 0xfc, 0xec, 0xf5, 0xfd,
	0xb1, 0x54, 0xb6, 0xda, 0x67, 0x71, 0x8e, 0x0d, 0x77, 0x10, 0xa7, 0xc3, 0x93, 0xbc, 0x44, 0xfe,
	0xeb, 0xc3, 0xb2, 0x11, 0x59, 0xab, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x76, 0xe9, 0x03, 0x44,
	0xc8, 0x01, 0x00, 0x00,
}
