// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: flow/entities/node_version_info.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompatibleRange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The first block that the version supports.
	StartHeight uint64 `protobuf:"varint,1,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"`
	// The last block that the version supports.
	EndHeight     uint64 `protobuf:"varint,2,opt,name=end_height,json=endHeight,proto3" json:"end_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompatibleRange) Reset() {
	*x = CompatibleRange{}
	mi := &file_flow_entities_node_version_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompatibleRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompatibleRange) ProtoMessage() {}

func (x *CompatibleRange) ProtoReflect() protoreflect.Message {
	mi := &file_flow_entities_node_version_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompatibleRange.ProtoReflect.Descriptor instead.
func (*CompatibleRange) Descriptor() ([]byte, []int) {
	return file_flow_entities_node_version_info_proto_rawDescGZIP(), []int{0}
}

func (x *CompatibleRange) GetStartHeight() uint64 {
	if x != nil {
		return x.StartHeight
	}
	return 0
}

func (x *CompatibleRange) GetEndHeight() uint64 {
	if x != nil {
		return x.EndHeight
	}
	return 0
}

type NodeVersionInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The currently running node software version.
	Semver string `protobuf:"bytes,1,opt,name=semver,proto3" json:"semver,omitempty"`
	// The git commit hash of the currently running node software.
	Commit string `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	// The unique identifier for the node's network within the current spork.
	SporkId []byte `protobuf:"bytes,3,opt,name=spork_id,json=sporkId,proto3" json:"spork_id,omitempty"`
	// The deprecated protocol version number.
	// Previously this referred to the major software version as of the most
	// recent spork. Replaced by protocol_state_version.
	//
	// Deprecated: Marked as deprecated in flow/entities/node_version_info.proto.
	ProtocolVersion uint64 `protobuf:"varint,4,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// The spork root block height. This is the height of the first sealed block
	// in the spork network.
	SporkRootBlockHeight uint64 `protobuf:"varint,5,opt,name=spork_root_block_height,json=sporkRootBlockHeight,proto3" json:"spork_root_block_height,omitempty"`
	// The node's root block height. This is the first sealed block in the node's
	// protocol database. If the node started at the beginning of the spork, it is
	// the same as the spork root block height. If the node started after the
	// beginning of the spork, it is the height of the first sealed block indexed.
	NodeRootBlockHeight uint64 `protobuf:"varint,6,opt,name=node_root_block_height,json=nodeRootBlockHeight,proto3" json:"node_root_block_height,omitempty"`
	// The compatible version range.
	CompatibleRange *CompatibleRange `protobuf:"bytes,7,opt,name=compatible_range,json=compatibleRange,proto3" json:"compatible_range,omitempty"`
	// The Protocol State version as of the latest finalized block.
	// This tracks the schema version of the Protocol State and is used to
	// coordinate breaking changes in the Protocol. Version numbers are
	// monotonically increasing.
	ProtocolStateVersion uint64 `protobuf:"varint,8,opt,name=protocol_state_version,json=protocolStateVersion,proto3" json:"protocol_state_version,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *NodeVersionInfo) Reset() {
	*x = NodeVersionInfo{}
	mi := &file_flow_entities_node_version_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeVersionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeVersionInfo) ProtoMessage() {}

func (x *NodeVersionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_flow_entities_node_version_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeVersionInfo.ProtoReflect.Descriptor instead.
func (*NodeVersionInfo) Descriptor() ([]byte, []int) {
	return file_flow_entities_node_version_info_proto_rawDescGZIP(), []int{1}
}

func (x *NodeVersionInfo) GetSemver() string {
	if x != nil {
		return x.Semver
	}
	return ""
}

func (x *NodeVersionInfo) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *NodeVersionInfo) GetSporkId() []byte {
	if x != nil {
		return x.SporkId
	}
	return nil
}

// Deprecated: Marked as deprecated in flow/entities/node_version_info.proto.
func (x *NodeVersionInfo) GetProtocolVersion() uint64 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *NodeVersionInfo) GetSporkRootBlockHeight() uint64 {
	if x != nil {
		return x.SporkRootBlockHeight
	}
	return 0
}

func (x *NodeVersionInfo) GetNodeRootBlockHeight() uint64 {
	if x != nil {
		return x.NodeRootBlockHeight
	}
	return 0
}

func (x *NodeVersionInfo) GetCompatibleRange() *CompatibleRange {
	if x != nil {
		return x.CompatibleRange
	}
	return nil
}

func (x *NodeVersionInfo) GetProtocolStateVersion() uint64 {
	if x != nil {
		return x.ProtocolStateVersion
	}
	return 0
}

var File_flow_entities_node_version_info_proto protoreflect.FileDescriptor

const file_flow_entities_node_version_info_proto_rawDesc = "" +
	"\n" +
	"%flow/entities/node_version_info.proto\x12\rflow.entities\"S\n" +
	"\x0fCompatibleRange\x12!\n" +
	"\fstart_height\x18\x01 \x01(\x04R\vstartHeight\x12\x1d\n" +
	"\n" +
	"end_height\x18\x02 \x01(\x04R\tendHeight\"\xf8\x02\n" +
	"\x0fNodeVersionInfo\x12\x16\n" +
	"\x06semver\x18\x01 \x01(\tR\x06semver\x12\x16\n" +
	"\x06commit\x18\x02 \x01(\tR\x06commit\x12\x19\n" +
	"\bspork_id\x18\x03 \x01(\fR\asporkId\x12-\n" +
	"\x10protocol_version\x18\x04 \x01(\x04B\x02\x18\x01R\x0fprotocolVersion\x125\n" +
	"\x17spork_root_block_height\x18\x05 \x01(\x04R\x14sporkRootBlockHeight\x123\n" +
	"\x16node_root_block_height\x18\x06 \x01(\x04R\x13nodeRootBlockHeight\x12I\n" +
	"\x10compatible_range\x18\a \x01(\v2\x1e.flow.entities.CompatibleRangeR\x0fcompatibleRange\x124\n" +
	"\x16protocol_state_version\x18\b \x01(\x04R\x14protocolStateVersionBP\n" +
	"\x1corg.onflow.protobuf.entitiesZ0github.com/onflow/flow/protobuf/go/flow/entitiesb\x06proto3"

var (
	file_flow_entities_node_version_info_proto_rawDescOnce sync.Once
	file_flow_entities_node_version_info_proto_rawDescData []byte
)

func file_flow_entities_node_version_info_proto_rawDescGZIP() []byte {
	file_flow_entities_node_version_info_proto_rawDescOnce.Do(func() {
		file_flow_entities_node_version_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flow_entities_node_version_info_proto_rawDesc), len(file_flow_entities_node_version_info_proto_rawDesc)))
	})
	return file_flow_entities_node_version_info_proto_rawDescData
}

var file_flow_entities_node_version_info_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_flow_entities_node_version_info_proto_goTypes = []any{
	(*CompatibleRange)(nil), // 0: flow.entities.CompatibleRange
	(*NodeVersionInfo)(nil), // 1: flow.entities.NodeVersionInfo
}
var file_flow_entities_node_version_info_proto_depIdxs = []int32{
	0, // 0: flow.entities.NodeVersionInfo.compatible_range:type_name -> flow.entities.CompatibleRange
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_flow_entities_node_version_info_proto_init() }
func file_flow_entities_node_version_info_proto_init() {
	if File_flow_entities_node_version_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flow_entities_node_version_info_proto_rawDesc), len(file_flow_entities_node_version_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_flow_entities_node_version_info_proto_goTypes,
		DependencyIndexes: file_flow_entities_node_version_info_proto_depIdxs,
		MessageInfos:      file_flow_entities_node_version_info_proto_msgTypes,
	}.Build()
	File_flow_entities_node_version_info_proto = out.File
	file_flow_entities_node_version_info_proto_goTypes = nil
	file_flow_entities_node_version_info_proto_depIdxs = nil
}
