// Code generated by protoc-gen-go. DO NOT EDIT.
// source: flow/entities/register.proto

package entities

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterID struct {
	Owner                []byte   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterID) Reset()         { *m = RegisterID{} }
func (m *RegisterID) String() string { return proto.CompactTextString(m) }
func (*RegisterID) ProtoMessage()    {}
func (*RegisterID) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a0154cacbb20826, []int{0}
}

func (m *RegisterID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterID.Unmarshal(m, b)
}
func (m *RegisterID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterID.Marshal(b, m, deterministic)
}
func (m *RegisterID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterID.Merge(m, src)
}
func (m *RegisterID) XXX_Size() int {
	return xxx_messageInfo_RegisterID.Size(m)
}
func (m *RegisterID) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterID.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterID proto.InternalMessageInfo

func (m *RegisterID) GetOwner() []byte {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *RegisterID) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func init() {
	proto.RegisterType((*RegisterID)(nil), "flow.entities.RegisterID")
}

func init() { proto.RegisterFile("flow/entities/register.proto", fileDescriptor_6a0154cacbb20826) }

var fileDescriptor_6a0154cacbb20826 = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x49, 0xcb, 0xc9, 0x2f,
	0xd7, 0x4f, 0xcd, 0x2b, 0xc9, 0x2c, 0xc9, 0x4c, 0x2d, 0xd6, 0x2f, 0x4a, 0x4d, 0xcf, 0x2c, 0x2e,
	0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x05, 0xc9, 0xea, 0xc1, 0x64, 0x95,
	0x4c, 0xb8, 0xb8, 0x82, 0xa0, 0x0a, 0x3c, 0x5d, 0x84, 0x44, 0xb8, 0x58, 0xf3, 0xcb, 0xf3, 0x52,
	0x8b, 0x24, 0x18, 0x15, 0x18, 0x35, 0x78, 0x82, 0x20, 0x1c, 0x21, 0x01, 0x2e, 0xe6, 0xec, 0xd4,
	0x4a, 0x09, 0x26, 0xb0, 0x18, 0x88, 0xe9, 0x14, 0xc0, 0x25, 0x93, 0x5f, 0x94, 0xae, 0x97, 0x9f,
	0x07, 0x36, 0x0c, 0x6c, 0x70, 0x52, 0x69, 0x1a, 0xdc, 0xd4, 0x28, 0x83, 0xf4, 0xcc, 0x92, 0x8c,
	0xd2, 0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0x7d, 0x88, 0x22, 0x7d, 0x30, 0x01, 0x53, 0xa9, 0x9f, 0x9e,
	0xaf, 0x8f, 0xe2, 0xca, 0x24, 0x36, 0xb0, 0x94, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x29, 0xce,
	0xb4, 0xc0, 0xbd, 0x00, 0x00, 0x00,
}
