// Code generated by protoc-gen-go. DO NOT EDIT.
// source: flow/entities/transaction.proto

package entities

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TransactionStatus int32

const (
	TransactionStatus_UNKNOWN   TransactionStatus = 0
	TransactionStatus_PENDING   TransactionStatus = 1
	TransactionStatus_FINALIZED TransactionStatus = 2
	TransactionStatus_EXECUTE   TransactionStatus = 3
	TransactionStatus_SEALED    TransactionStatus = 4
)

var TransactionStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "PENDING",
	2: "FINALIZED",
	3: "EXECUTE",
	4: "SEALED",
}

var TransactionStatus_value = map[string]int32{
	"UNKNOWN":   0,
	"PENDING":   1,
	"FINALIZED": 2,
	"EXECUTE":   3,
	"SEALED":    4,
}

func (x TransactionStatus) String() string {
	return proto.EnumName(TransactionStatus_name, int32(x))
}

func (TransactionStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_84361b1ad2e0936e, []int{0}
}

type Transaction struct {
	Script               []byte                   `protobuf:"bytes,1,opt,name=script,proto3" json:"script,omitempty"`
	ReferenceBlockId     []byte                   `protobuf:"bytes,2,opt,name=reference_block_id,json=referenceBlockId,proto3" json:"reference_block_id,omitempty"`
	GasLimit             uint64                   `protobuf:"varint,3,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	ProposalKey          *Transaction_ProposalKey `protobuf:"bytes,4,opt,name=proposal_key,json=proposalKey,proto3" json:"proposal_key,omitempty"`
	Payer                []byte                   `protobuf:"bytes,5,opt,name=payer,proto3" json:"payer,omitempty"`
	Authorizers          [][]byte                 `protobuf:"bytes,6,rep,name=authorizers,proto3" json:"authorizers,omitempty"`
	PayloadSignatures    []*Transaction_Signature `protobuf:"bytes,7,rep,name=payload_signatures,json=payloadSignatures,proto3" json:"payload_signatures,omitempty"`
	EnvelopeSignatures   []*Transaction_Signature `protobuf:"bytes,8,rep,name=envelope_signatures,json=envelopeSignatures,proto3" json:"envelope_signatures,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_84361b1ad2e0936e, []int{0}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetScript() []byte {
	if m != nil {
		return m.Script
	}
	return nil
}

func (m *Transaction) GetReferenceBlockId() []byte {
	if m != nil {
		return m.ReferenceBlockId
	}
	return nil
}

func (m *Transaction) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *Transaction) GetProposalKey() *Transaction_ProposalKey {
	if m != nil {
		return m.ProposalKey
	}
	return nil
}

func (m *Transaction) GetPayer() []byte {
	if m != nil {
		return m.Payer
	}
	return nil
}

func (m *Transaction) GetAuthorizers() [][]byte {
	if m != nil {
		return m.Authorizers
	}
	return nil
}

func (m *Transaction) GetPayloadSignatures() []*Transaction_Signature {
	if m != nil {
		return m.PayloadSignatures
	}
	return nil
}

func (m *Transaction) GetEnvelopeSignatures() []*Transaction_Signature {
	if m != nil {
		return m.EnvelopeSignatures
	}
	return nil
}

type Transaction_ProposalKey struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	KeyId                uint32   `protobuf:"varint,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	SequenceNumber       uint64   `protobuf:"varint,3,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction_ProposalKey) Reset()         { *m = Transaction_ProposalKey{} }
func (m *Transaction_ProposalKey) String() string { return proto.CompactTextString(m) }
func (*Transaction_ProposalKey) ProtoMessage()    {}
func (*Transaction_ProposalKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_84361b1ad2e0936e, []int{0, 0}
}

func (m *Transaction_ProposalKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction_ProposalKey.Unmarshal(m, b)
}
func (m *Transaction_ProposalKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction_ProposalKey.Marshal(b, m, deterministic)
}
func (m *Transaction_ProposalKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction_ProposalKey.Merge(m, src)
}
func (m *Transaction_ProposalKey) XXX_Size() int {
	return xxx_messageInfo_Transaction_ProposalKey.Size(m)
}
func (m *Transaction_ProposalKey) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction_ProposalKey.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction_ProposalKey proto.InternalMessageInfo

func (m *Transaction_ProposalKey) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Transaction_ProposalKey) GetKeyId() uint32 {
	if m != nil {
		return m.KeyId
	}
	return 0
}

func (m *Transaction_ProposalKey) GetSequenceNumber() uint64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

type Transaction_Signature struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	KeyId                uint32   `protobuf:"varint,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Signature            []byte   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction_Signature) Reset()         { *m = Transaction_Signature{} }
func (m *Transaction_Signature) String() string { return proto.CompactTextString(m) }
func (*Transaction_Signature) ProtoMessage()    {}
func (*Transaction_Signature) Descriptor() ([]byte, []int) {
	return fileDescriptor_84361b1ad2e0936e, []int{0, 1}
}

func (m *Transaction_Signature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction_Signature.Unmarshal(m, b)
}
func (m *Transaction_Signature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction_Signature.Marshal(b, m, deterministic)
}
func (m *Transaction_Signature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction_Signature.Merge(m, src)
}
func (m *Transaction_Signature) XXX_Size() int {
	return xxx_messageInfo_Transaction_Signature.Size(m)
}
func (m *Transaction_Signature) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction_Signature.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction_Signature proto.InternalMessageInfo

func (m *Transaction_Signature) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Transaction_Signature) GetKeyId() uint32 {
	if m != nil {
		return m.KeyId
	}
	return 0
}

func (m *Transaction_Signature) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterEnum("entities.TransactionStatus", TransactionStatus_name, TransactionStatus_value)
	proto.RegisterType((*Transaction)(nil), "entities.Transaction")
	proto.RegisterType((*Transaction_ProposalKey)(nil), "entities.Transaction.ProposalKey")
	proto.RegisterType((*Transaction_Signature)(nil), "entities.Transaction.Signature")
}

func init() { proto.RegisterFile("flow/entities/transaction.proto", fileDescriptor_84361b1ad2e0936e) }

var fileDescriptor_84361b1ad2e0936e = []byte{
	// 424 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x5d, 0x6f, 0xd3, 0x40,
	0x10, 0xc4, 0x4d, 0xe2, 0x24, 0xeb, 0x14, 0xdc, 0xe5, 0x43, 0x56, 0x41, 0xaa, 0xe1, 0x05, 0x0b,
	0xa1, 0x54, 0x2a, 0xbf, 0xa0, 0x10, 0x83, 0xac, 0x46, 0x26, 0x72, 0x1a, 0x81, 0xfa, 0x62, 0x5d,
	0xe2, 0x6d, 0x38, 0xc5, 0xf5, 0x99, 0xbb, 0x33, 0xc8, 0xfc, 0x4f, 0xfe, 0x0f, 0x8a, 0xb1, 0x63,
	0x3f, 0xf0, 0x40, 0x1f, 0x67, 0x66, 0x6f, 0x77, 0x46, 0x73, 0x70, 0x76, 0x9b, 0x8a, 0x9f, 0xe7,
	0x94, 0x69, 0xae, 0x39, 0xa9, 0x73, 0x2d, 0x59, 0xa6, 0xd8, 0x46, 0x73, 0x91, 0x4d, 0x73, 0x29,
	0xb4, 0xc0, 0x51, 0xa3, 0xbd, 0xfa, 0xdd, 0x07, 0xeb, 0xba, 0xd5, 0xf1, 0x19, 0x98, 0x6a, 0x23,
	0x79, 0xae, 0x1d, 0xc3, 0x35, 0xbc, 0x49, 0x54, 0x23, 0x7c, 0x0b, 0x28, 0xe9, 0x96, 0x24, 0x65,
	0x1b, 0x8a, 0xd7, 0xa9, 0xd8, 0xec, 0x62, 0x9e, 0x38, 0x47, 0xd5, 0x8c, 0x7d, 0x50, 0xde, 0xef,
	0x85, 0x20, 0xc1, 0xe7, 0x30, 0xde, 0x32, 0x15, 0xa7, 0xfc, 0x8e, 0x6b, 0xa7, 0xe7, 0x1a, 0x5e,
	0x3f, 0x1a, 0x6d, 0x99, 0x9a, 0xef, 0x31, 0xce, 0x60, 0x92, 0x4b, 0x91, 0x0b, 0xc5, 0xd2, 0x78,
	0x47, 0xa5, 0xd3, 0x77, 0x0d, 0xcf, 0xba, 0x78, 0x39, 0x6d, 0x3c, 0x4d, 0x3b, 0x7e, 0xa6, 0x8b,
	0x7a, 0xf2, 0x8a, 0xca, 0xc8, 0xca, 0x5b, 0x80, 0x4f, 0x60, 0x90, 0xb3, 0x92, 0xa4, 0x33, 0xa8,
	0x3c, 0xfc, 0x05, 0xe8, 0x82, 0xc5, 0x0a, 0xfd, 0x4d, 0x48, 0xfe, 0x8b, 0xa4, 0x72, 0x4c, 0xb7,
	0xe7, 0x4d, 0xa2, 0x2e, 0x85, 0x21, 0x60, 0xce, 0xca, 0x54, 0xb0, 0x24, 0x56, 0x7c, 0x9b, 0x31,
	0x5d, 0x48, 0x52, 0xce, 0xd0, 0xed, 0x79, 0xd6, 0xc5, 0xd9, 0xbf, 0x3d, 0x2c, 0x9b, 0xb9, 0xe8,
	0xa4, 0x7e, 0x7a, 0x60, 0x14, 0x2e, 0xe0, 0x31, 0x65, 0x3f, 0x28, 0x15, 0x39, 0x75, 0x17, 0x8e,
	0xfe, 0x6f, 0x21, 0x36, 0x6f, 0xdb, 0x8d, 0xa7, 0x5b, 0xb0, 0x3a, 0xa9, 0xd1, 0x81, 0x21, 0x4b,
	0x12, 0x49, 0x4a, 0xd5, 0x95, 0x34, 0x10, 0x9f, 0x82, 0xb9, 0xa3, 0xb2, 0xe9, 0xe1, 0x38, 0x1a,
	0xec, 0xa8, 0x0c, 0x12, 0x7c, 0x0d, 0x8f, 0x14, 0x7d, 0x2f, 0xaa, 0xa6, 0xb2, 0xe2, 0x6e, 0x4d,
	0xb2, 0xae, 0xe0, 0x61, 0x43, 0x87, 0x15, 0x7b, 0x7a, 0x03, 0xe3, 0xc3, 0xd9, 0xfb, 0x9f, 0x79,
	0x01, 0xe3, 0x43, 0xde, 0xea, 0xc0, 0x24, 0x6a, 0x89, 0x37, 0x2b, 0x38, 0xe9, 0x24, 0x5e, 0x6a,
	0xa6, 0x0b, 0x85, 0x16, 0x0c, 0x57, 0xe1, 0x55, 0xf8, 0xf9, 0x4b, 0x68, 0x3f, 0xd8, 0x83, 0x85,
	0x1f, 0xce, 0x82, 0xf0, 0x93, 0x6d, 0xe0, 0x31, 0x8c, 0x3f, 0x06, 0xe1, 0xe5, 0x3c, 0xb8, 0xf1,
	0x67, 0xf6, 0xd1, 0x5e, 0xf3, 0xbf, 0xfa, 0x1f, 0x56, 0xd7, 0xbe, 0xdd, 0x43, 0x00, 0x73, 0xe9,
	0x5f, 0xce, 0xfd, 0x99, 0xdd, 0x5f, 0x9b, 0xd5, 0xff, 0x7d, 0xf7, 0x27, 0x00, 0x00, 0xff, 0xff,
	0x31, 0x64, 0x67, 0xfb, 0xe2, 0x02, 0x00, 0x00,
}
