// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flow/entities/block.proto

package entities;

public final class BlockOuterClass {
  private BlockOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BlockOrBuilder extends
      // @@protoc_insertion_point(interface_extends:entities.Block)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes id = 1;</code>
     */
    com.google.protobuf.ByteString getId();

    /**
     * <code>bytes parent_id = 2;</code>
     */
    com.google.protobuf.ByteString getParentId();

    /**
     * <code>uint64 height = 3;</code>
     */
    long getHeight();

    /**
     * <code>.google.protobuf.Timestamp timestamp = 4;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>.google.protobuf.Timestamp timestamp = 4;</code>
     */
    com.google.protobuf.Timestamp getTimestamp();
    /**
     * <code>.google.protobuf.Timestamp timestamp = 4;</code>
     */
    com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();

    /**
     * <code>repeated .entities.CollectionGuarantee collection_guarantees = 5;</code>
     */
    java.util.List<entities.CollectionOuterClass.CollectionGuarantee> 
        getCollectionGuaranteesList();
    /**
     * <code>repeated .entities.CollectionGuarantee collection_guarantees = 5;</code>
     */
    entities.CollectionOuterClass.CollectionGuarantee getCollectionGuarantees(int index);
    /**
     * <code>repeated .entities.CollectionGuarantee collection_guarantees = 5;</code>
     */
    int getCollectionGuaranteesCount();
    /**
     * <code>repeated .entities.CollectionGuarantee collection_guarantees = 5;</code>
     */
    java.util.List<? extends entities.CollectionOuterClass.CollectionGuaranteeOrBuilder> 
        getCollectionGuaranteesOrBuilderList();
    /**
     * <code>repeated .entities.CollectionGuarantee collection_guarantees = 5;</code>
     */
    entities.CollectionOuterClass.CollectionGuaranteeOrBuilder getCollectionGuaranteesOrBuilder(
        int index);

    /**
     * <code>repeated .entities.BlockSeal block_seals = 6;</code>
     */
    java.util.List<entities.BlockSealOuterClass.BlockSeal> 
        getBlockSealsList();
    /**
     * <code>repeated .entities.BlockSeal block_seals = 6;</code>
     */
    entities.BlockSealOuterClass.BlockSeal getBlockSeals(int index);
    /**
     * <code>repeated .entities.BlockSeal block_seals = 6;</code>
     */
    int getBlockSealsCount();
    /**
     * <code>repeated .entities.BlockSeal block_seals = 6;</code>
     */
    java.util.List<? extends entities.BlockSealOuterClass.BlockSealOrBuilder> 
        getBlockSealsOrBuilderList();
    /**
     * <code>repeated .entities.BlockSeal block_seals = 6;</code>
     */
    entities.BlockSealOuterClass.BlockSealOrBuilder getBlockSealsOrBuilder(
        int index);

    /**
     * <code>repeated bytes signatures = 7;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getSignaturesList();
    /**
     * <code>repeated bytes signatures = 7;</code>
     */
    int getSignaturesCount();
    /**
     * <code>repeated bytes signatures = 7;</code>
     */
    com.google.protobuf.ByteString getSignatures(int index);
  }
  /**
   * Protobuf type {@code entities.Block}
   */
  public  static final class Block extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:entities.Block)
      BlockOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Block.newBuilder() to construct.
    private Block(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Block() {
      id_ = com.google.protobuf.ByteString.EMPTY;
      parentId_ = com.google.protobuf.ByteString.EMPTY;
      collectionGuarantees_ = java.util.Collections.emptyList();
      blockSeals_ = java.util.Collections.emptyList();
      signatures_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Block();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Block(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              id_ = input.readBytes();
              break;
            }
            case 18: {

              parentId_ = input.readBytes();
              break;
            }
            case 24: {

              height_ = input.readUInt64();
              break;
            }
            case 34: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (timestamp_ != null) {
                subBuilder = timestamp_.toBuilder();
              }
              timestamp_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(timestamp_);
                timestamp_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                collectionGuarantees_ = new java.util.ArrayList<entities.CollectionOuterClass.CollectionGuarantee>();
                mutable_bitField0_ |= 0x00000001;
              }
              collectionGuarantees_.add(
                  input.readMessage(entities.CollectionOuterClass.CollectionGuarantee.parser(), extensionRegistry));
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                blockSeals_ = new java.util.ArrayList<entities.BlockSealOuterClass.BlockSeal>();
                mutable_bitField0_ |= 0x00000002;
              }
              blockSeals_.add(
                  input.readMessage(entities.BlockSealOuterClass.BlockSeal.parser(), extensionRegistry));
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                signatures_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000004;
              }
              signatures_.add(input.readBytes());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          collectionGuarantees_ = java.util.Collections.unmodifiableList(collectionGuarantees_);
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          blockSeals_ = java.util.Collections.unmodifiableList(blockSeals_);
        }
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          signatures_ = java.util.Collections.unmodifiableList(signatures_); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return entities.BlockOuterClass.internal_static_entities_Block_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return entities.BlockOuterClass.internal_static_entities_Block_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              entities.BlockOuterClass.Block.class, entities.BlockOuterClass.Block.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString id_;
    /**
     * <code>bytes id = 1;</code>
     */
    public com.google.protobuf.ByteString getId() {
      return id_;
    }

    public static final int PARENT_ID_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString parentId_;
    /**
     * <code>bytes parent_id = 2;</code>
     */
    public com.google.protobuf.ByteString getParentId() {
      return parentId_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 3;
    private long height_;
    /**
     * <code>uint64 height = 3;</code>
     */
    public long getHeight() {
      return height_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private com.google.protobuf.Timestamp timestamp_;
    /**
     * <code>.google.protobuf.Timestamp timestamp = 4;</code>
     */
    public boolean hasTimestamp() {
      return timestamp_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 4;</code>
     */
    public com.google.protobuf.Timestamp getTimestamp() {
      return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 4;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      return getTimestamp();
    }

    public static final int COLLECTION_GUARANTEES_FIELD_NUMBER = 5;
    private java.util.List<entities.CollectionOuterClass.CollectionGuarantee> collectionGuarantees_;
    /**
     * <code>repeated .entities.CollectionGuarantee collection_guarantees = 5;</code>
     */
    public java.util.List<entities.CollectionOuterClass.CollectionGuarantee> getCollectionGuaranteesList() {
      return collectionGuarantees_;
    }
    /**
     * <code>repeated .entities.CollectionGuarantee collection_guarantees = 5;</code>
     */
    public java.util.List<? extends entities.CollectionOuterClass.CollectionGuaranteeOrBuilder> 
        getCollectionGuaranteesOrBuilderList() {
      return collectionGuarantees_;
    }
    /**
     * <code>repeated .entities.CollectionGuarantee collection_guarantees = 5;</code>
     */
    public int getCollectionGuaranteesCount() {
      return collectionGuarantees_.size();
    }
    /**
     * <code>repeated .entities.CollectionGuarantee collection_guarantees = 5;</code>
     */
    public entities.CollectionOuterClass.CollectionGuarantee getCollectionGuarantees(int index) {
      return collectionGuarantees_.get(index);
    }
    /**
     * <code>repeated .entities.CollectionGuarantee collection_guarantees = 5;</code>
     */
    public entities.CollectionOuterClass.CollectionGuaranteeOrBuilder getCollectionGuaranteesOrBuilder(
        int index) {
      return collectionGuarantees_.get(index);
    }

    public static final int BLOCK_SEALS_FIELD_NUMBER = 6;
    private java.util.List<entities.BlockSealOuterClass.BlockSeal> blockSeals_;
    /**
     * <code>repeated .entities.BlockSeal block_seals = 6;</code>
     */
    public java.util.List<entities.BlockSealOuterClass.BlockSeal> getBlockSealsList() {
      return blockSeals_;
    }
    /**
     * <code>repeated .entities.BlockSeal block_seals = 6;</code>
     */
    public java.util.List<? extends entities.BlockSealOuterClass.BlockSealOrBuilder> 
        getBlockSealsOrBuilderList() {
      return blockSeals_;
    }
    /**
     * <code>repeated .entities.BlockSeal block_seals = 6;</code>
     */
    public int getBlockSealsCount() {
      return blockSeals_.size();
    }
    /**
     * <code>repeated .entities.BlockSeal block_seals = 6;</code>
     */
    public entities.BlockSealOuterClass.BlockSeal getBlockSeals(int index) {
      return blockSeals_.get(index);
    }
    /**
     * <code>repeated .entities.BlockSeal block_seals = 6;</code>
     */
    public entities.BlockSealOuterClass.BlockSealOrBuilder getBlockSealsOrBuilder(
        int index) {
      return blockSeals_.get(index);
    }

    public static final int SIGNATURES_FIELD_NUMBER = 7;
    private java.util.List<com.google.protobuf.ByteString> signatures_;
    /**
     * <code>repeated bytes signatures = 7;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getSignaturesList() {
      return signatures_;
    }
    /**
     * <code>repeated bytes signatures = 7;</code>
     */
    public int getSignaturesCount() {
      return signatures_.size();
    }
    /**
     * <code>repeated bytes signatures = 7;</code>
     */
    public com.google.protobuf.ByteString getSignatures(int index) {
      return signatures_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!id_.isEmpty()) {
        output.writeBytes(1, id_);
      }
      if (!parentId_.isEmpty()) {
        output.writeBytes(2, parentId_);
      }
      if (height_ != 0L) {
        output.writeUInt64(3, height_);
      }
      if (timestamp_ != null) {
        output.writeMessage(4, getTimestamp());
      }
      for (int i = 0; i < collectionGuarantees_.size(); i++) {
        output.writeMessage(5, collectionGuarantees_.get(i));
      }
      for (int i = 0; i < blockSeals_.size(); i++) {
        output.writeMessage(6, blockSeals_.get(i));
      }
      for (int i = 0; i < signatures_.size(); i++) {
        output.writeBytes(7, signatures_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!id_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, id_);
      }
      if (!parentId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, parentId_);
      }
      if (height_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, height_);
      }
      if (timestamp_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getTimestamp());
      }
      for (int i = 0; i < collectionGuarantees_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, collectionGuarantees_.get(i));
      }
      for (int i = 0; i < blockSeals_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, blockSeals_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < signatures_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(signatures_.get(i));
        }
        size += dataSize;
        size += 1 * getSignaturesList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof entities.BlockOuterClass.Block)) {
        return super.equals(obj);
      }
      entities.BlockOuterClass.Block other = (entities.BlockOuterClass.Block) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getParentId()
          .equals(other.getParentId())) return false;
      if (getHeight()
          != other.getHeight()) return false;
      if (hasTimestamp() != other.hasTimestamp()) return false;
      if (hasTimestamp()) {
        if (!getTimestamp()
            .equals(other.getTimestamp())) return false;
      }
      if (!getCollectionGuaranteesList()
          .equals(other.getCollectionGuaranteesList())) return false;
      if (!getBlockSealsList()
          .equals(other.getBlockSealsList())) return false;
      if (!getSignaturesList()
          .equals(other.getSignaturesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + PARENT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getParentId().hashCode();
      hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getHeight());
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimestamp().hashCode();
      }
      if (getCollectionGuaranteesCount() > 0) {
        hash = (37 * hash) + COLLECTION_GUARANTEES_FIELD_NUMBER;
        hash = (53 * hash) + getCollectionGuaranteesList().hashCode();
      }
      if (getBlockSealsCount() > 0) {
        hash = (37 * hash) + BLOCK_SEALS_FIELD_NUMBER;
        hash = (53 * hash) + getBlockSealsList().hashCode();
      }
      if (getSignaturesCount() > 0) {
        hash = (37 * hash) + SIGNATURES_FIELD_NUMBER;
        hash = (53 * hash) + getSignaturesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static entities.BlockOuterClass.Block parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static entities.BlockOuterClass.Block parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static entities.BlockOuterClass.Block parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static entities.BlockOuterClass.Block parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static entities.BlockOuterClass.Block parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static entities.BlockOuterClass.Block parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static entities.BlockOuterClass.Block parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static entities.BlockOuterClass.Block parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static entities.BlockOuterClass.Block parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static entities.BlockOuterClass.Block parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static entities.BlockOuterClass.Block parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static entities.BlockOuterClass.Block parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(entities.BlockOuterClass.Block prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code entities.Block}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:entities.Block)
        entities.BlockOuterClass.BlockOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return entities.BlockOuterClass.internal_static_entities_Block_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return entities.BlockOuterClass.internal_static_entities_Block_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                entities.BlockOuterClass.Block.class, entities.BlockOuterClass.Block.Builder.class);
      }

      // Construct using entities.BlockOuterClass.Block.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCollectionGuaranteesFieldBuilder();
          getBlockSealsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = com.google.protobuf.ByteString.EMPTY;

        parentId_ = com.google.protobuf.ByteString.EMPTY;

        height_ = 0L;

        if (timestampBuilder_ == null) {
          timestamp_ = null;
        } else {
          timestamp_ = null;
          timestampBuilder_ = null;
        }
        if (collectionGuaranteesBuilder_ == null) {
          collectionGuarantees_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          collectionGuaranteesBuilder_.clear();
        }
        if (blockSealsBuilder_ == null) {
          blockSeals_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          blockSealsBuilder_.clear();
        }
        signatures_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return entities.BlockOuterClass.internal_static_entities_Block_descriptor;
      }

      @java.lang.Override
      public entities.BlockOuterClass.Block getDefaultInstanceForType() {
        return entities.BlockOuterClass.Block.getDefaultInstance();
      }

      @java.lang.Override
      public entities.BlockOuterClass.Block build() {
        entities.BlockOuterClass.Block result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public entities.BlockOuterClass.Block buildPartial() {
        entities.BlockOuterClass.Block result = new entities.BlockOuterClass.Block(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.parentId_ = parentId_;
        result.height_ = height_;
        if (timestampBuilder_ == null) {
          result.timestamp_ = timestamp_;
        } else {
          result.timestamp_ = timestampBuilder_.build();
        }
        if (collectionGuaranteesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            collectionGuarantees_ = java.util.Collections.unmodifiableList(collectionGuarantees_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.collectionGuarantees_ = collectionGuarantees_;
        } else {
          result.collectionGuarantees_ = collectionGuaranteesBuilder_.build();
        }
        if (blockSealsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            blockSeals_ = java.util.Collections.unmodifiableList(blockSeals_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.blockSeals_ = blockSeals_;
        } else {
          result.blockSeals_ = blockSealsBuilder_.build();
        }
        if (((bitField0_ & 0x00000004) != 0)) {
          signatures_ = java.util.Collections.unmodifiableList(signatures_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.signatures_ = signatures_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof entities.BlockOuterClass.Block) {
          return mergeFrom((entities.BlockOuterClass.Block)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(entities.BlockOuterClass.Block other) {
        if (other == entities.BlockOuterClass.Block.getDefaultInstance()) return this;
        if (other.getId() != com.google.protobuf.ByteString.EMPTY) {
          setId(other.getId());
        }
        if (other.getParentId() != com.google.protobuf.ByteString.EMPTY) {
          setParentId(other.getParentId());
        }
        if (other.getHeight() != 0L) {
          setHeight(other.getHeight());
        }
        if (other.hasTimestamp()) {
          mergeTimestamp(other.getTimestamp());
        }
        if (collectionGuaranteesBuilder_ == null) {
          if (!other.collectionGuarantees_.isEmpty()) {
            if (collectionGuarantees_.isEmpty()) {
              collectionGuarantees_ = other.collectionGuarantees_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCollectionGuaranteesIsMutable();
              collectionGuarantees_.addAll(other.collectionGuarantees_);
            }
            onChanged();
          }
        } else {
          if (!other.collectionGuarantees_.isEmpty()) {
            if (collectionGuaranteesBuilder_.isEmpty()) {
              collectionGuaranteesBuilder_.dispose();
              collectionGuaranteesBuilder_ = null;
              collectionGuarantees_ = other.collectionGuarantees_;
              bitField0_ = (bitField0_ & ~0x00000001);
              collectionGuaranteesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCollectionGuaranteesFieldBuilder() : null;
            } else {
              collectionGuaranteesBuilder_.addAllMessages(other.collectionGuarantees_);
            }
          }
        }
        if (blockSealsBuilder_ == null) {
          if (!other.blockSeals_.isEmpty()) {
            if (blockSeals_.isEmpty()) {
              blockSeals_ = other.blockSeals_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureBlockSealsIsMutable();
              blockSeals_.addAll(other.blockSeals_);
            }
            onChanged();
          }
        } else {
          if (!other.blockSeals_.isEmpty()) {
            if (blockSealsBuilder_.isEmpty()) {
              blockSealsBuilder_.dispose();
              blockSealsBuilder_ = null;
              blockSeals_ = other.blockSeals_;
              bitField0_ = (bitField0_ & ~0x00000002);
              blockSealsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBlockSealsFieldBuilder() : null;
            } else {
              blockSealsBuilder_.addAllMessages(other.blockSeals_);
            }
          }
        }
        if (!other.signatures_.isEmpty()) {
          if (signatures_.isEmpty()) {
            signatures_ = other.signatures_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureSignaturesIsMutable();
            signatures_.addAll(other.signatures_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        entities.BlockOuterClass.Block parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (entities.BlockOuterClass.Block) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString id_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes id = 1;</code>
       */
      public com.google.protobuf.ByteString getId() {
        return id_;
      }
      /**
       * <code>bytes id = 1;</code>
       */
      public Builder setId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString parentId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes parent_id = 2;</code>
       */
      public com.google.protobuf.ByteString getParentId() {
        return parentId_;
      }
      /**
       * <code>bytes parent_id = 2;</code>
       */
      public Builder setParentId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        parentId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes parent_id = 2;</code>
       */
      public Builder clearParentId() {
        
        parentId_ = getDefaultInstance().getParentId();
        onChanged();
        return this;
      }

      private long height_ ;
      /**
       * <code>uint64 height = 3;</code>
       */
      public long getHeight() {
        return height_;
      }
      /**
       * <code>uint64 height = 3;</code>
       */
      public Builder setHeight(long value) {
        
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 height = 3;</code>
       */
      public Builder clearHeight() {
        
        height_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp timestamp_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampBuilder_;
      /**
       * <code>.google.protobuf.Timestamp timestamp = 4;</code>
       */
      public boolean hasTimestamp() {
        return timestampBuilder_ != null || timestamp_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 4;</code>
       */
      public com.google.protobuf.Timestamp getTimestamp() {
        if (timestampBuilder_ == null) {
          return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
        } else {
          return timestampBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 4;</code>
       */
      public Builder setTimestamp(com.google.protobuf.Timestamp value) {
        if (timestampBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          timestamp_ = value;
          onChanged();
        } else {
          timestampBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 4;</code>
       */
      public Builder setTimestamp(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (timestampBuilder_ == null) {
          timestamp_ = builderForValue.build();
          onChanged();
        } else {
          timestampBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 4;</code>
       */
      public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
        if (timestampBuilder_ == null) {
          if (timestamp_ != null) {
            timestamp_ =
              com.google.protobuf.Timestamp.newBuilder(timestamp_).mergeFrom(value).buildPartial();
          } else {
            timestamp_ = value;
          }
          onChanged();
        } else {
          timestampBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 4;</code>
       */
      public Builder clearTimestamp() {
        if (timestampBuilder_ == null) {
          timestamp_ = null;
          onChanged();
        } else {
          timestamp_ = null;
          timestampBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 4;</code>
       */
      public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
        
        onChanged();
        return getTimestampFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 4;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
        if (timestampBuilder_ != null) {
          return timestampBuilder_.getMessageOrBuilder();
        } else {
          return timestamp_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getTimestampFieldBuilder() {
        if (timestampBuilder_ == null) {
          timestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getTimestamp(),
                  getParentForChildren(),
                  isClean());
          timestamp_ = null;
        }
        return timestampBuilder_;
      }

      private java.util.List<entities.CollectionOuterClass.CollectionGuarantee> collectionGuarantees_ =
        java.util.Collections.emptyList();
      private void ensureCollectionGuaranteesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          collectionGuarantees_ = new java.util.ArrayList<entities.CollectionOuterClass.CollectionGuarantee>(collectionGuarantees_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          entities.CollectionOuterClass.CollectionGuarantee, entities.CollectionOuterClass.CollectionGuarantee.Builder, entities.CollectionOuterClass.CollectionGuaranteeOrBuilder> collectionGuaranteesBuilder_;

      /**
       * <code>repeated .entities.CollectionGuarantee collection_guarantees = 5;</code>
       */
      public java.util.List<entities.CollectionOuterClass.CollectionGuarantee> getCollectionGuaranteesList() {
        if (collectionGuaranteesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(collectionGuarantees_);
        } else {
          return collectionGuaranteesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .entities.CollectionGuarantee collection_guarantees = 5;</code>
       */
      public int getCollectionGuaranteesCount() {
        if (collectionGuaranteesBuilder_ == null) {
          return collectionGuarantees_.size();
        } else {
          return collectionGuaranteesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .entities.CollectionGuarantee collection_guarantees = 5;</code>
       */
      public entities.CollectionOuterClass.CollectionGuarantee getCollectionGuarantees(int index) {
        if (collectionGuaranteesBuilder_ == null) {
          return collectionGuarantees_.get(index);
        } else {
          return collectionGuaranteesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .entities.CollectionGuarantee collection_guarantees = 5;</code>
       */
      public Builder setCollectionGuarantees(
          int index, entities.CollectionOuterClass.CollectionGuarantee value) {
        if (collectionGuaranteesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCollectionGuaranteesIsMutable();
          collectionGuarantees_.set(index, value);
          onChanged();
        } else {
          collectionGuaranteesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .entities.CollectionGuarantee collection_guarantees = 5;</code>
       */
      public Builder setCollectionGuarantees(
          int index, entities.CollectionOuterClass.CollectionGuarantee.Builder builderForValue) {
        if (collectionGuaranteesBuilder_ == null) {
          ensureCollectionGuaranteesIsMutable();
          collectionGuarantees_.set(index, builderForValue.build());
          onChanged();
        } else {
          collectionGuaranteesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .entities.CollectionGuarantee collection_guarantees = 5;</code>
       */
      public Builder addCollectionGuarantees(entities.CollectionOuterClass.CollectionGuarantee value) {
        if (collectionGuaranteesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCollectionGuaranteesIsMutable();
          collectionGuarantees_.add(value);
          onChanged();
        } else {
          collectionGuaranteesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .entities.CollectionGuarantee collection_guarantees = 5;</code>
       */
      public Builder addCollectionGuarantees(
          int index, entities.CollectionOuterClass.CollectionGuarantee value) {
        if (collectionGuaranteesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCollectionGuaranteesIsMutable();
          collectionGuarantees_.add(index, value);
          onChanged();
        } else {
          collectionGuaranteesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .entities.CollectionGuarantee collection_guarantees = 5;</code>
       */
      public Builder addCollectionGuarantees(
          entities.CollectionOuterClass.CollectionGuarantee.Builder builderForValue) {
        if (collectionGuaranteesBuilder_ == null) {
          ensureCollectionGuaranteesIsMutable();
          collectionGuarantees_.add(builderForValue.build());
          onChanged();
        } else {
          collectionGuaranteesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .entities.CollectionGuarantee collection_guarantees = 5;</code>
       */
      public Builder addCollectionGuarantees(
          int index, entities.CollectionOuterClass.CollectionGuarantee.Builder builderForValue) {
        if (collectionGuaranteesBuilder_ == null) {
          ensureCollectionGuaranteesIsMutable();
          collectionGuarantees_.add(index, builderForValue.build());
          onChanged();
        } else {
          collectionGuaranteesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .entities.CollectionGuarantee collection_guarantees = 5;</code>
       */
      public Builder addAllCollectionGuarantees(
          java.lang.Iterable<? extends entities.CollectionOuterClass.CollectionGuarantee> values) {
        if (collectionGuaranteesBuilder_ == null) {
          ensureCollectionGuaranteesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, collectionGuarantees_);
          onChanged();
        } else {
          collectionGuaranteesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .entities.CollectionGuarantee collection_guarantees = 5;</code>
       */
      public Builder clearCollectionGuarantees() {
        if (collectionGuaranteesBuilder_ == null) {
          collectionGuarantees_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          collectionGuaranteesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .entities.CollectionGuarantee collection_guarantees = 5;</code>
       */
      public Builder removeCollectionGuarantees(int index) {
        if (collectionGuaranteesBuilder_ == null) {
          ensureCollectionGuaranteesIsMutable();
          collectionGuarantees_.remove(index);
          onChanged();
        } else {
          collectionGuaranteesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .entities.CollectionGuarantee collection_guarantees = 5;</code>
       */
      public entities.CollectionOuterClass.CollectionGuarantee.Builder getCollectionGuaranteesBuilder(
          int index) {
        return getCollectionGuaranteesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .entities.CollectionGuarantee collection_guarantees = 5;</code>
       */
      public entities.CollectionOuterClass.CollectionGuaranteeOrBuilder getCollectionGuaranteesOrBuilder(
          int index) {
        if (collectionGuaranteesBuilder_ == null) {
          return collectionGuarantees_.get(index);  } else {
          return collectionGuaranteesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .entities.CollectionGuarantee collection_guarantees = 5;</code>
       */
      public java.util.List<? extends entities.CollectionOuterClass.CollectionGuaranteeOrBuilder> 
           getCollectionGuaranteesOrBuilderList() {
        if (collectionGuaranteesBuilder_ != null) {
          return collectionGuaranteesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(collectionGuarantees_);
        }
      }
      /**
       * <code>repeated .entities.CollectionGuarantee collection_guarantees = 5;</code>
       */
      public entities.CollectionOuterClass.CollectionGuarantee.Builder addCollectionGuaranteesBuilder() {
        return getCollectionGuaranteesFieldBuilder().addBuilder(
            entities.CollectionOuterClass.CollectionGuarantee.getDefaultInstance());
      }
      /**
       * <code>repeated .entities.CollectionGuarantee collection_guarantees = 5;</code>
       */
      public entities.CollectionOuterClass.CollectionGuarantee.Builder addCollectionGuaranteesBuilder(
          int index) {
        return getCollectionGuaranteesFieldBuilder().addBuilder(
            index, entities.CollectionOuterClass.CollectionGuarantee.getDefaultInstance());
      }
      /**
       * <code>repeated .entities.CollectionGuarantee collection_guarantees = 5;</code>
       */
      public java.util.List<entities.CollectionOuterClass.CollectionGuarantee.Builder> 
           getCollectionGuaranteesBuilderList() {
        return getCollectionGuaranteesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          entities.CollectionOuterClass.CollectionGuarantee, entities.CollectionOuterClass.CollectionGuarantee.Builder, entities.CollectionOuterClass.CollectionGuaranteeOrBuilder> 
          getCollectionGuaranteesFieldBuilder() {
        if (collectionGuaranteesBuilder_ == null) {
          collectionGuaranteesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              entities.CollectionOuterClass.CollectionGuarantee, entities.CollectionOuterClass.CollectionGuarantee.Builder, entities.CollectionOuterClass.CollectionGuaranteeOrBuilder>(
                  collectionGuarantees_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          collectionGuarantees_ = null;
        }
        return collectionGuaranteesBuilder_;
      }

      private java.util.List<entities.BlockSealOuterClass.BlockSeal> blockSeals_ =
        java.util.Collections.emptyList();
      private void ensureBlockSealsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          blockSeals_ = new java.util.ArrayList<entities.BlockSealOuterClass.BlockSeal>(blockSeals_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          entities.BlockSealOuterClass.BlockSeal, entities.BlockSealOuterClass.BlockSeal.Builder, entities.BlockSealOuterClass.BlockSealOrBuilder> blockSealsBuilder_;

      /**
       * <code>repeated .entities.BlockSeal block_seals = 6;</code>
       */
      public java.util.List<entities.BlockSealOuterClass.BlockSeal> getBlockSealsList() {
        if (blockSealsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(blockSeals_);
        } else {
          return blockSealsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .entities.BlockSeal block_seals = 6;</code>
       */
      public int getBlockSealsCount() {
        if (blockSealsBuilder_ == null) {
          return blockSeals_.size();
        } else {
          return blockSealsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .entities.BlockSeal block_seals = 6;</code>
       */
      public entities.BlockSealOuterClass.BlockSeal getBlockSeals(int index) {
        if (blockSealsBuilder_ == null) {
          return blockSeals_.get(index);
        } else {
          return blockSealsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .entities.BlockSeal block_seals = 6;</code>
       */
      public Builder setBlockSeals(
          int index, entities.BlockSealOuterClass.BlockSeal value) {
        if (blockSealsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBlockSealsIsMutable();
          blockSeals_.set(index, value);
          onChanged();
        } else {
          blockSealsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .entities.BlockSeal block_seals = 6;</code>
       */
      public Builder setBlockSeals(
          int index, entities.BlockSealOuterClass.BlockSeal.Builder builderForValue) {
        if (blockSealsBuilder_ == null) {
          ensureBlockSealsIsMutable();
          blockSeals_.set(index, builderForValue.build());
          onChanged();
        } else {
          blockSealsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .entities.BlockSeal block_seals = 6;</code>
       */
      public Builder addBlockSeals(entities.BlockSealOuterClass.BlockSeal value) {
        if (blockSealsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBlockSealsIsMutable();
          blockSeals_.add(value);
          onChanged();
        } else {
          blockSealsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .entities.BlockSeal block_seals = 6;</code>
       */
      public Builder addBlockSeals(
          int index, entities.BlockSealOuterClass.BlockSeal value) {
        if (blockSealsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBlockSealsIsMutable();
          blockSeals_.add(index, value);
          onChanged();
        } else {
          blockSealsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .entities.BlockSeal block_seals = 6;</code>
       */
      public Builder addBlockSeals(
          entities.BlockSealOuterClass.BlockSeal.Builder builderForValue) {
        if (blockSealsBuilder_ == null) {
          ensureBlockSealsIsMutable();
          blockSeals_.add(builderForValue.build());
          onChanged();
        } else {
          blockSealsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .entities.BlockSeal block_seals = 6;</code>
       */
      public Builder addBlockSeals(
          int index, entities.BlockSealOuterClass.BlockSeal.Builder builderForValue) {
        if (blockSealsBuilder_ == null) {
          ensureBlockSealsIsMutable();
          blockSeals_.add(index, builderForValue.build());
          onChanged();
        } else {
          blockSealsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .entities.BlockSeal block_seals = 6;</code>
       */
      public Builder addAllBlockSeals(
          java.lang.Iterable<? extends entities.BlockSealOuterClass.BlockSeal> values) {
        if (blockSealsBuilder_ == null) {
          ensureBlockSealsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, blockSeals_);
          onChanged();
        } else {
          blockSealsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .entities.BlockSeal block_seals = 6;</code>
       */
      public Builder clearBlockSeals() {
        if (blockSealsBuilder_ == null) {
          blockSeals_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          blockSealsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .entities.BlockSeal block_seals = 6;</code>
       */
      public Builder removeBlockSeals(int index) {
        if (blockSealsBuilder_ == null) {
          ensureBlockSealsIsMutable();
          blockSeals_.remove(index);
          onChanged();
        } else {
          blockSealsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .entities.BlockSeal block_seals = 6;</code>
       */
      public entities.BlockSealOuterClass.BlockSeal.Builder getBlockSealsBuilder(
          int index) {
        return getBlockSealsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .entities.BlockSeal block_seals = 6;</code>
       */
      public entities.BlockSealOuterClass.BlockSealOrBuilder getBlockSealsOrBuilder(
          int index) {
        if (blockSealsBuilder_ == null) {
          return blockSeals_.get(index);  } else {
          return blockSealsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .entities.BlockSeal block_seals = 6;</code>
       */
      public java.util.List<? extends entities.BlockSealOuterClass.BlockSealOrBuilder> 
           getBlockSealsOrBuilderList() {
        if (blockSealsBuilder_ != null) {
          return blockSealsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(blockSeals_);
        }
      }
      /**
       * <code>repeated .entities.BlockSeal block_seals = 6;</code>
       */
      public entities.BlockSealOuterClass.BlockSeal.Builder addBlockSealsBuilder() {
        return getBlockSealsFieldBuilder().addBuilder(
            entities.BlockSealOuterClass.BlockSeal.getDefaultInstance());
      }
      /**
       * <code>repeated .entities.BlockSeal block_seals = 6;</code>
       */
      public entities.BlockSealOuterClass.BlockSeal.Builder addBlockSealsBuilder(
          int index) {
        return getBlockSealsFieldBuilder().addBuilder(
            index, entities.BlockSealOuterClass.BlockSeal.getDefaultInstance());
      }
      /**
       * <code>repeated .entities.BlockSeal block_seals = 6;</code>
       */
      public java.util.List<entities.BlockSealOuterClass.BlockSeal.Builder> 
           getBlockSealsBuilderList() {
        return getBlockSealsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          entities.BlockSealOuterClass.BlockSeal, entities.BlockSealOuterClass.BlockSeal.Builder, entities.BlockSealOuterClass.BlockSealOrBuilder> 
          getBlockSealsFieldBuilder() {
        if (blockSealsBuilder_ == null) {
          blockSealsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              entities.BlockSealOuterClass.BlockSeal, entities.BlockSealOuterClass.BlockSeal.Builder, entities.BlockSealOuterClass.BlockSealOrBuilder>(
                  blockSeals_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          blockSeals_ = null;
        }
        return blockSealsBuilder_;
      }

      private java.util.List<com.google.protobuf.ByteString> signatures_ = java.util.Collections.emptyList();
      private void ensureSignaturesIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          signatures_ = new java.util.ArrayList<com.google.protobuf.ByteString>(signatures_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated bytes signatures = 7;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getSignaturesList() {
        return ((bitField0_ & 0x00000004) != 0) ?
                 java.util.Collections.unmodifiableList(signatures_) : signatures_;
      }
      /**
       * <code>repeated bytes signatures = 7;</code>
       */
      public int getSignaturesCount() {
        return signatures_.size();
      }
      /**
       * <code>repeated bytes signatures = 7;</code>
       */
      public com.google.protobuf.ByteString getSignatures(int index) {
        return signatures_.get(index);
      }
      /**
       * <code>repeated bytes signatures = 7;</code>
       */
      public Builder setSignatures(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSignaturesIsMutable();
        signatures_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes signatures = 7;</code>
       */
      public Builder addSignatures(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSignaturesIsMutable();
        signatures_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes signatures = 7;</code>
       */
      public Builder addAllSignatures(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureSignaturesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, signatures_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes signatures = 7;</code>
       */
      public Builder clearSignatures() {
        signatures_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:entities.Block)
    }

    // @@protoc_insertion_point(class_scope:entities.Block)
    private static final entities.BlockOuterClass.Block DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new entities.BlockOuterClass.Block();
    }

    public static entities.BlockOuterClass.Block getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Block>
        PARSER = new com.google.protobuf.AbstractParser<Block>() {
      @java.lang.Override
      public Block parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Block(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Block> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Block> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public entities.BlockOuterClass.Block getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_entities_Block_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_entities_Block_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031flow/entities/block.proto\022\010entities\032\037g" +
      "oogle/protobuf/timestamp.proto\032\036flow/ent" +
      "ities/collection.proto\032\036flow/entities/bl" +
      "ock_seal.proto\"\341\001\n\005Block\022\n\n\002id\030\001 \001(\014\022\021\n\t" +
      "parent_id\030\002 \001(\014\022\016\n\006height\030\003 \001(\004\022-\n\ttimes" +
      "tamp\030\004 \001(\0132\032.google.protobuf.Timestamp\022<" +
      "\n\025collection_guarantees\030\005 \003(\0132\035.entities" +
      ".CollectionGuarantee\022(\n\013block_seals\030\006 \003(" +
      "\0132\023.entities.BlockSeal\022\022\n\nsignatures\030\007 \003" +
      "(\014b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          entities.CollectionOuterClass.getDescriptor(),
          entities.BlockSealOuterClass.getDescriptor(),
        });
    internal_static_entities_Block_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_entities_Block_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_entities_Block_descriptor,
        new java.lang.String[] { "Id", "ParentId", "Height", "Timestamp", "CollectionGuarantees", "BlockSeals", "Signatures", });
    com.google.protobuf.TimestampProto.getDescriptor();
    entities.CollectionOuterClass.getDescriptor();
    entities.BlockSealOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
