# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from flow.access import access_pb2 as flow_dot_access_dot_access__pb2


class AccessAPIStub(object):
    """AccessAPI is the public-facing API provided by access nodes.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/flow.access.AccessAPI/Ping',
                request_serializer=flow_dot_access_dot_access__pb2.PingRequest.SerializeToString,
                response_deserializer=flow_dot_access_dot_access__pb2.PingResponse.FromString,
                )
        self.GetLatestBlockHeader = channel.unary_unary(
                '/flow.access.AccessAPI/GetLatestBlockHeader',
                request_serializer=flow_dot_access_dot_access__pb2.GetLatestBlockHeaderRequest.SerializeToString,
                response_deserializer=flow_dot_access_dot_access__pb2.BlockHeaderResponse.FromString,
                )
        self.GetBlockHeaderByID = channel.unary_unary(
                '/flow.access.AccessAPI/GetBlockHeaderByID',
                request_serializer=flow_dot_access_dot_access__pb2.GetBlockHeaderByIDRequest.SerializeToString,
                response_deserializer=flow_dot_access_dot_access__pb2.BlockHeaderResponse.FromString,
                )
        self.GetBlockHeaderByHeight = channel.unary_unary(
                '/flow.access.AccessAPI/GetBlockHeaderByHeight',
                request_serializer=flow_dot_access_dot_access__pb2.GetBlockHeaderByHeightRequest.SerializeToString,
                response_deserializer=flow_dot_access_dot_access__pb2.BlockHeaderResponse.FromString,
                )
        self.GetLatestBlock = channel.unary_unary(
                '/flow.access.AccessAPI/GetLatestBlock',
                request_serializer=flow_dot_access_dot_access__pb2.GetLatestBlockRequest.SerializeToString,
                response_deserializer=flow_dot_access_dot_access__pb2.BlockResponse.FromString,
                )
        self.GetBlockByID = channel.unary_unary(
                '/flow.access.AccessAPI/GetBlockByID',
                request_serializer=flow_dot_access_dot_access__pb2.GetBlockByIDRequest.SerializeToString,
                response_deserializer=flow_dot_access_dot_access__pb2.BlockResponse.FromString,
                )
        self.GetBlockByHeight = channel.unary_unary(
                '/flow.access.AccessAPI/GetBlockByHeight',
                request_serializer=flow_dot_access_dot_access__pb2.GetBlockByHeightRequest.SerializeToString,
                response_deserializer=flow_dot_access_dot_access__pb2.BlockResponse.FromString,
                )
        self.GetCollectionByID = channel.unary_unary(
                '/flow.access.AccessAPI/GetCollectionByID',
                request_serializer=flow_dot_access_dot_access__pb2.GetCollectionByIDRequest.SerializeToString,
                response_deserializer=flow_dot_access_dot_access__pb2.CollectionResponse.FromString,
                )
        self.SendTransaction = channel.unary_unary(
                '/flow.access.AccessAPI/SendTransaction',
                request_serializer=flow_dot_access_dot_access__pb2.SendTransactionRequest.SerializeToString,
                response_deserializer=flow_dot_access_dot_access__pb2.SendTransactionResponse.FromString,
                )
        self.GetTransaction = channel.unary_unary(
                '/flow.access.AccessAPI/GetTransaction',
                request_serializer=flow_dot_access_dot_access__pb2.GetTransactionRequest.SerializeToString,
                response_deserializer=flow_dot_access_dot_access__pb2.TransactionResponse.FromString,
                )
        self.GetTransactionResult = channel.unary_unary(
                '/flow.access.AccessAPI/GetTransactionResult',
                request_serializer=flow_dot_access_dot_access__pb2.GetTransactionRequest.SerializeToString,
                response_deserializer=flow_dot_access_dot_access__pb2.TransactionResultResponse.FromString,
                )
        self.GetAccount = channel.unary_unary(
                '/flow.access.AccessAPI/GetAccount',
                request_serializer=flow_dot_access_dot_access__pb2.GetAccountRequest.SerializeToString,
                response_deserializer=flow_dot_access_dot_access__pb2.GetAccountResponse.FromString,
                )
        self.GetAccountAtLatestBlock = channel.unary_unary(
                '/flow.access.AccessAPI/GetAccountAtLatestBlock',
                request_serializer=flow_dot_access_dot_access__pb2.GetAccountAtLatestBlockRequest.SerializeToString,
                response_deserializer=flow_dot_access_dot_access__pb2.AccountResponse.FromString,
                )
        self.GetAccountAtBlockHeight = channel.unary_unary(
                '/flow.access.AccessAPI/GetAccountAtBlockHeight',
                request_serializer=flow_dot_access_dot_access__pb2.GetAccountAtBlockHeightRequest.SerializeToString,
                response_deserializer=flow_dot_access_dot_access__pb2.AccountResponse.FromString,
                )
        self.ExecuteScriptAtLatestBlock = channel.unary_unary(
                '/flow.access.AccessAPI/ExecuteScriptAtLatestBlock',
                request_serializer=flow_dot_access_dot_access__pb2.ExecuteScriptAtLatestBlockRequest.SerializeToString,
                response_deserializer=flow_dot_access_dot_access__pb2.ExecuteScriptResponse.FromString,
                )
        self.ExecuteScriptAtBlockID = channel.unary_unary(
                '/flow.access.AccessAPI/ExecuteScriptAtBlockID',
                request_serializer=flow_dot_access_dot_access__pb2.ExecuteScriptAtBlockIDRequest.SerializeToString,
                response_deserializer=flow_dot_access_dot_access__pb2.ExecuteScriptResponse.FromString,
                )
        self.ExecuteScriptAtBlockHeight = channel.unary_unary(
                '/flow.access.AccessAPI/ExecuteScriptAtBlockHeight',
                request_serializer=flow_dot_access_dot_access__pb2.ExecuteScriptAtBlockHeightRequest.SerializeToString,
                response_deserializer=flow_dot_access_dot_access__pb2.ExecuteScriptResponse.FromString,
                )
        self.GetEventsForHeightRange = channel.unary_unary(
                '/flow.access.AccessAPI/GetEventsForHeightRange',
                request_serializer=flow_dot_access_dot_access__pb2.GetEventsForHeightRangeRequest.SerializeToString,
                response_deserializer=flow_dot_access_dot_access__pb2.EventsResponse.FromString,
                )
        self.GetEventsForBlockIDs = channel.unary_unary(
                '/flow.access.AccessAPI/GetEventsForBlockIDs',
                request_serializer=flow_dot_access_dot_access__pb2.GetEventsForBlockIDsRequest.SerializeToString,
                response_deserializer=flow_dot_access_dot_access__pb2.EventsResponse.FromString,
                )
        self.GetNetworkParameters = channel.unary_unary(
                '/flow.access.AccessAPI/GetNetworkParameters',
                request_serializer=flow_dot_access_dot_access__pb2.GetNetworkParametersRequest.SerializeToString,
                response_deserializer=flow_dot_access_dot_access__pb2.GetNetworkParametersResponse.FromString,
                )
        self.GetLatestProtocolStateSnapshot = channel.unary_unary(
                '/flow.access.AccessAPI/GetLatestProtocolStateSnapshot',
                request_serializer=flow_dot_access_dot_access__pb2.GetLatestProtocolStateSnapshotRequest.SerializeToString,
                response_deserializer=flow_dot_access_dot_access__pb2.ProtocolStateSnapshotResponse.FromString,
                )


class AccessAPIServicer(object):
    """AccessAPI is the public-facing API provided by access nodes.
    """

    def Ping(self, request, context):
        """Ping is used to check if the access node is alive and healthy.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLatestBlockHeader(self, request, context):
        """Block Headers

        GetLatestBlockHeader gets the latest sealed or unsealed block header.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBlockHeaderByID(self, request, context):
        """GetBlockHeaderByID gets a block header by ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBlockHeaderByHeight(self, request, context):
        """GetBlockHeaderByHeight gets a block header by height.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLatestBlock(self, request, context):
        """Blocks

        GetLatestBlock gets the full payload of the latest sealed or unsealed block.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBlockByID(self, request, context):
        """GetBlockByID gets a full block by ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBlockByHeight(self, request, context):
        """GetBlockByHeight gets a full block by height.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCollectionByID(self, request, context):
        """Collections

        GetCollectionByID gets a collection by ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendTransaction(self, request, context):
        """Transactions

        SendTransaction submits a transaction to the network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransaction(self, request, context):
        """GetTransaction gets a transaction by ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransactionResult(self, request, context):
        """GetTransactionResult gets the result of a transaction.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccount(self, request, context):
        """Accounts

        GetAccount is an alias for GetAccountAtLatestBlock.

        Warning: this function is deprecated. It behaves identically to GetAccountAtLatestBlock and will be removed in a future version.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccountAtLatestBlock(self, request, context):
        """GetAccountAtLatestBlock gets an account by address from the latest sealed execution state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccountAtBlockHeight(self, request, context):
        """GetAccountAtBlockHeight gets an account by address at the given block height
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteScriptAtLatestBlock(self, request, context):
        """Scripts

        ExecuteScriptAtLatestBlock executes a read-only Cadence script against the latest sealed execution state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteScriptAtBlockID(self, request, context):
        """ExecuteScriptAtBlockID executes a ready-only Cadence script against the execution state at the block with the given ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteScriptAtBlockHeight(self, request, context):
        """ExecuteScriptAtBlockHeight executes a ready-only Cadence script against the execution state at the given block height.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEventsForHeightRange(self, request, context):
        """Events

        GetEventsForHeightRange retrieves events emitted within the specified block range.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEventsForBlockIDs(self, request, context):
        """GetEventsForBlockIDs retrieves events for the specified block IDs and event type.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNetworkParameters(self, request, context):
        """NetworkParameters

        GetNetworkParameters retrieves the Flow network details
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLatestProtocolStateSnapshot(self, request, context):
        """ProtocolState

        GetLatestProtocolStateSnapshot retrieves the latest sealed protocol state snapshot.
        Used by Flow nodes joining the network to bootstrap a space-efficient local state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccessAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=flow_dot_access_dot_access__pb2.PingRequest.FromString,
                    response_serializer=flow_dot_access_dot_access__pb2.PingResponse.SerializeToString,
            ),
            'GetLatestBlockHeader': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatestBlockHeader,
                    request_deserializer=flow_dot_access_dot_access__pb2.GetLatestBlockHeaderRequest.FromString,
                    response_serializer=flow_dot_access_dot_access__pb2.BlockHeaderResponse.SerializeToString,
            ),
            'GetBlockHeaderByID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBlockHeaderByID,
                    request_deserializer=flow_dot_access_dot_access__pb2.GetBlockHeaderByIDRequest.FromString,
                    response_serializer=flow_dot_access_dot_access__pb2.BlockHeaderResponse.SerializeToString,
            ),
            'GetBlockHeaderByHeight': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBlockHeaderByHeight,
                    request_deserializer=flow_dot_access_dot_access__pb2.GetBlockHeaderByHeightRequest.FromString,
                    response_serializer=flow_dot_access_dot_access__pb2.BlockHeaderResponse.SerializeToString,
            ),
            'GetLatestBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatestBlock,
                    request_deserializer=flow_dot_access_dot_access__pb2.GetLatestBlockRequest.FromString,
                    response_serializer=flow_dot_access_dot_access__pb2.BlockResponse.SerializeToString,
            ),
            'GetBlockByID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBlockByID,
                    request_deserializer=flow_dot_access_dot_access__pb2.GetBlockByIDRequest.FromString,
                    response_serializer=flow_dot_access_dot_access__pb2.BlockResponse.SerializeToString,
            ),
            'GetBlockByHeight': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBlockByHeight,
                    request_deserializer=flow_dot_access_dot_access__pb2.GetBlockByHeightRequest.FromString,
                    response_serializer=flow_dot_access_dot_access__pb2.BlockResponse.SerializeToString,
            ),
            'GetCollectionByID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCollectionByID,
                    request_deserializer=flow_dot_access_dot_access__pb2.GetCollectionByIDRequest.FromString,
                    response_serializer=flow_dot_access_dot_access__pb2.CollectionResponse.SerializeToString,
            ),
            'SendTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTransaction,
                    request_deserializer=flow_dot_access_dot_access__pb2.SendTransactionRequest.FromString,
                    response_serializer=flow_dot_access_dot_access__pb2.SendTransactionResponse.SerializeToString,
            ),
            'GetTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransaction,
                    request_deserializer=flow_dot_access_dot_access__pb2.GetTransactionRequest.FromString,
                    response_serializer=flow_dot_access_dot_access__pb2.TransactionResponse.SerializeToString,
            ),
            'GetTransactionResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransactionResult,
                    request_deserializer=flow_dot_access_dot_access__pb2.GetTransactionRequest.FromString,
                    response_serializer=flow_dot_access_dot_access__pb2.TransactionResultResponse.SerializeToString,
            ),
            'GetAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccount,
                    request_deserializer=flow_dot_access_dot_access__pb2.GetAccountRequest.FromString,
                    response_serializer=flow_dot_access_dot_access__pb2.GetAccountResponse.SerializeToString,
            ),
            'GetAccountAtLatestBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountAtLatestBlock,
                    request_deserializer=flow_dot_access_dot_access__pb2.GetAccountAtLatestBlockRequest.FromString,
                    response_serializer=flow_dot_access_dot_access__pb2.AccountResponse.SerializeToString,
            ),
            'GetAccountAtBlockHeight': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountAtBlockHeight,
                    request_deserializer=flow_dot_access_dot_access__pb2.GetAccountAtBlockHeightRequest.FromString,
                    response_serializer=flow_dot_access_dot_access__pb2.AccountResponse.SerializeToString,
            ),
            'ExecuteScriptAtLatestBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteScriptAtLatestBlock,
                    request_deserializer=flow_dot_access_dot_access__pb2.ExecuteScriptAtLatestBlockRequest.FromString,
                    response_serializer=flow_dot_access_dot_access__pb2.ExecuteScriptResponse.SerializeToString,
            ),
            'ExecuteScriptAtBlockID': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteScriptAtBlockID,
                    request_deserializer=flow_dot_access_dot_access__pb2.ExecuteScriptAtBlockIDRequest.FromString,
                    response_serializer=flow_dot_access_dot_access__pb2.ExecuteScriptResponse.SerializeToString,
            ),
            'ExecuteScriptAtBlockHeight': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteScriptAtBlockHeight,
                    request_deserializer=flow_dot_access_dot_access__pb2.ExecuteScriptAtBlockHeightRequest.FromString,
                    response_serializer=flow_dot_access_dot_access__pb2.ExecuteScriptResponse.SerializeToString,
            ),
            'GetEventsForHeightRange': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEventsForHeightRange,
                    request_deserializer=flow_dot_access_dot_access__pb2.GetEventsForHeightRangeRequest.FromString,
                    response_serializer=flow_dot_access_dot_access__pb2.EventsResponse.SerializeToString,
            ),
            'GetEventsForBlockIDs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEventsForBlockIDs,
                    request_deserializer=flow_dot_access_dot_access__pb2.GetEventsForBlockIDsRequest.FromString,
                    response_serializer=flow_dot_access_dot_access__pb2.EventsResponse.SerializeToString,
            ),
            'GetNetworkParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNetworkParameters,
                    request_deserializer=flow_dot_access_dot_access__pb2.GetNetworkParametersRequest.FromString,
                    response_serializer=flow_dot_access_dot_access__pb2.GetNetworkParametersResponse.SerializeToString,
            ),
            'GetLatestProtocolStateSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatestProtocolStateSnapshot,
                    request_deserializer=flow_dot_access_dot_access__pb2.GetLatestProtocolStateSnapshotRequest.FromString,
                    response_serializer=flow_dot_access_dot_access__pb2.ProtocolStateSnapshotResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'flow.access.AccessAPI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AccessAPI(object):
    """AccessAPI is the public-facing API provided by access nodes.
    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flow.access.AccessAPI/Ping',
            flow_dot_access_dot_access__pb2.PingRequest.SerializeToString,
            flow_dot_access_dot_access__pb2.PingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLatestBlockHeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flow.access.AccessAPI/GetLatestBlockHeader',
            flow_dot_access_dot_access__pb2.GetLatestBlockHeaderRequest.SerializeToString,
            flow_dot_access_dot_access__pb2.BlockHeaderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBlockHeaderByID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flow.access.AccessAPI/GetBlockHeaderByID',
            flow_dot_access_dot_access__pb2.GetBlockHeaderByIDRequest.SerializeToString,
            flow_dot_access_dot_access__pb2.BlockHeaderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBlockHeaderByHeight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flow.access.AccessAPI/GetBlockHeaderByHeight',
            flow_dot_access_dot_access__pb2.GetBlockHeaderByHeightRequest.SerializeToString,
            flow_dot_access_dot_access__pb2.BlockHeaderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLatestBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flow.access.AccessAPI/GetLatestBlock',
            flow_dot_access_dot_access__pb2.GetLatestBlockRequest.SerializeToString,
            flow_dot_access_dot_access__pb2.BlockResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBlockByID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flow.access.AccessAPI/GetBlockByID',
            flow_dot_access_dot_access__pb2.GetBlockByIDRequest.SerializeToString,
            flow_dot_access_dot_access__pb2.BlockResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBlockByHeight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flow.access.AccessAPI/GetBlockByHeight',
            flow_dot_access_dot_access__pb2.GetBlockByHeightRequest.SerializeToString,
            flow_dot_access_dot_access__pb2.BlockResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCollectionByID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flow.access.AccessAPI/GetCollectionByID',
            flow_dot_access_dot_access__pb2.GetCollectionByIDRequest.SerializeToString,
            flow_dot_access_dot_access__pb2.CollectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flow.access.AccessAPI/SendTransaction',
            flow_dot_access_dot_access__pb2.SendTransactionRequest.SerializeToString,
            flow_dot_access_dot_access__pb2.SendTransactionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flow.access.AccessAPI/GetTransaction',
            flow_dot_access_dot_access__pb2.GetTransactionRequest.SerializeToString,
            flow_dot_access_dot_access__pb2.TransactionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTransactionResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flow.access.AccessAPI/GetTransactionResult',
            flow_dot_access_dot_access__pb2.GetTransactionRequest.SerializeToString,
            flow_dot_access_dot_access__pb2.TransactionResultResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flow.access.AccessAPI/GetAccount',
            flow_dot_access_dot_access__pb2.GetAccountRequest.SerializeToString,
            flow_dot_access_dot_access__pb2.GetAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAccountAtLatestBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flow.access.AccessAPI/GetAccountAtLatestBlock',
            flow_dot_access_dot_access__pb2.GetAccountAtLatestBlockRequest.SerializeToString,
            flow_dot_access_dot_access__pb2.AccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAccountAtBlockHeight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flow.access.AccessAPI/GetAccountAtBlockHeight',
            flow_dot_access_dot_access__pb2.GetAccountAtBlockHeightRequest.SerializeToString,
            flow_dot_access_dot_access__pb2.AccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExecuteScriptAtLatestBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flow.access.AccessAPI/ExecuteScriptAtLatestBlock',
            flow_dot_access_dot_access__pb2.ExecuteScriptAtLatestBlockRequest.SerializeToString,
            flow_dot_access_dot_access__pb2.ExecuteScriptResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExecuteScriptAtBlockID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flow.access.AccessAPI/ExecuteScriptAtBlockID',
            flow_dot_access_dot_access__pb2.ExecuteScriptAtBlockIDRequest.SerializeToString,
            flow_dot_access_dot_access__pb2.ExecuteScriptResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExecuteScriptAtBlockHeight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flow.access.AccessAPI/ExecuteScriptAtBlockHeight',
            flow_dot_access_dot_access__pb2.ExecuteScriptAtBlockHeightRequest.SerializeToString,
            flow_dot_access_dot_access__pb2.ExecuteScriptResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEventsForHeightRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flow.access.AccessAPI/GetEventsForHeightRange',
            flow_dot_access_dot_access__pb2.GetEventsForHeightRangeRequest.SerializeToString,
            flow_dot_access_dot_access__pb2.EventsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEventsForBlockIDs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flow.access.AccessAPI/GetEventsForBlockIDs',
            flow_dot_access_dot_access__pb2.GetEventsForBlockIDsRequest.SerializeToString,
            flow_dot_access_dot_access__pb2.EventsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNetworkParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flow.access.AccessAPI/GetNetworkParameters',
            flow_dot_access_dot_access__pb2.GetNetworkParametersRequest.SerializeToString,
            flow_dot_access_dot_access__pb2.GetNetworkParametersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLatestProtocolStateSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flow.access.AccessAPI/GetLatestProtocolStateSnapshot',
            flow_dot_access_dot_access__pb2.GetLatestProtocolStateSnapshotRequest.SerializeToString,
            flow_dot_access_dot_access__pb2.ProtocolStateSnapshotResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
