// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: flow/legacy/entities/block_seal.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlockSeal struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	BlockId                    []byte                 `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	ExecutionReceiptId         []byte                 `protobuf:"bytes,2,opt,name=execution_receipt_id,json=executionReceiptId,proto3" json:"execution_receipt_id,omitempty"`
	ExecutionReceiptSignatures [][]byte               `protobuf:"bytes,3,rep,name=execution_receipt_signatures,json=executionReceiptSignatures,proto3" json:"execution_receipt_signatures,omitempty"`
	ResultApprovalSignatures   [][]byte               `protobuf:"bytes,4,rep,name=result_approval_signatures,json=resultApprovalSignatures,proto3" json:"result_approval_signatures,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *BlockSeal) Reset() {
	*x = BlockSeal{}
	mi := &file_flow_legacy_entities_block_seal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockSeal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockSeal) ProtoMessage() {}

func (x *BlockSeal) ProtoReflect() protoreflect.Message {
	mi := &file_flow_legacy_entities_block_seal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockSeal.ProtoReflect.Descriptor instead.
func (*BlockSeal) Descriptor() ([]byte, []int) {
	return file_flow_legacy_entities_block_seal_proto_rawDescGZIP(), []int{0}
}

func (x *BlockSeal) GetBlockId() []byte {
	if x != nil {
		return x.BlockId
	}
	return nil
}

func (x *BlockSeal) GetExecutionReceiptId() []byte {
	if x != nil {
		return x.ExecutionReceiptId
	}
	return nil
}

func (x *BlockSeal) GetExecutionReceiptSignatures() [][]byte {
	if x != nil {
		return x.ExecutionReceiptSignatures
	}
	return nil
}

func (x *BlockSeal) GetResultApprovalSignatures() [][]byte {
	if x != nil {
		return x.ResultApprovalSignatures
	}
	return nil
}

var File_flow_legacy_entities_block_seal_proto protoreflect.FileDescriptor

const file_flow_legacy_entities_block_seal_proto_rawDesc = "" +
	"\n" +
	"%flow/legacy/entities/block_seal.proto\x12\bentities\"\xd8\x01\n" +
	"\tBlockSeal\x12\x19\n" +
	"\bblock_id\x18\x01 \x01(\fR\ablockId\x120\n" +
	"\x14execution_receipt_id\x18\x02 \x01(\fR\x12executionReceiptId\x12@\n" +
	"\x1cexecution_receipt_signatures\x18\x03 \x03(\fR\x1aexecutionReceiptSignatures\x12<\n" +
	"\x1aresult_approval_signatures\x18\x04 \x03(\fR\x18resultApprovalSignaturesB^\n" +
	"#org.onflow.protobuf.legacy.entitiesZ7github.com/onflow/flow/protobuf/go/flow/legacy/entitiesb\x06proto3"

var (
	file_flow_legacy_entities_block_seal_proto_rawDescOnce sync.Once
	file_flow_legacy_entities_block_seal_proto_rawDescData []byte
)

func file_flow_legacy_entities_block_seal_proto_rawDescGZIP() []byte {
	file_flow_legacy_entities_block_seal_proto_rawDescOnce.Do(func() {
		file_flow_legacy_entities_block_seal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flow_legacy_entities_block_seal_proto_rawDesc), len(file_flow_legacy_entities_block_seal_proto_rawDesc)))
	})
	return file_flow_legacy_entities_block_seal_proto_rawDescData
}

var file_flow_legacy_entities_block_seal_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_flow_legacy_entities_block_seal_proto_goTypes = []any{
	(*BlockSeal)(nil), // 0: entities.BlockSeal
}
var file_flow_legacy_entities_block_seal_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_flow_legacy_entities_block_seal_proto_init() }
func file_flow_legacy_entities_block_seal_proto_init() {
	if File_flow_legacy_entities_block_seal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flow_legacy_entities_block_seal_proto_rawDesc), len(file_flow_legacy_entities_block_seal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_flow_legacy_entities_block_seal_proto_goTypes,
		DependencyIndexes: file_flow_legacy_entities_block_seal_proto_depIdxs,
		MessageInfos:      file_flow_legacy_entities_block_seal_proto_msgTypes,
	}.Build()
	File_flow_legacy_entities_block_seal_proto = out.File
	file_flow_legacy_entities_block_seal_proto_goTypes = nil
	file_flow_legacy_entities_block_seal_proto_depIdxs = nil
}
